# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_TaskGui(object):
    def setupUi(self, TaskGui):
        if not TaskGui.objectName():
            TaskGui.setObjectName(u"TaskGui")
        TaskGui.resize(1600, 916)
        self.actionAdaptive_sensorimotor_decision_making_task = QAction(TaskGui)
        self.actionAdaptive_sensorimotor_decision_making_task.setObjectName(u"actionAdaptive_sensorimotor_decision_making_task")
        self.actionAdaptive_sensorimotor_decision_making_task_2 = QAction(TaskGui)
        self.actionAdaptive_sensorimotor_decision_making_task_2.setObjectName(u"actionAdaptive_sensorimotor_decision_making_task_2")
        self.centralwidget = QWidget(TaskGui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.Boxes = QTabWidget(self.centralwidget)
        self.Boxes.setObjectName(u"Boxes")
        self.Boxes.setGeometry(QRect(-1, 9, 1591, 871))
        font = QFont()
        font.setPointSize(10)
        self.Boxes.setFont(font)
        self.Box = QWidget()
        self.Box.setObjectName(u"Box")
        self.Box.setEnabled(True)
        font1 = QFont()
        font1.setPointSize(14)
        self.Box.setFont(font1)
        self.TaskSettings = QWidget(self.Box)
        self.TaskSettings.setObjectName(u"TaskSettings")
        self.TaskSettings.setGeometry(QRect(10, 30, 501, 801))
        self.TaskSettings.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.lbl_AnimalID = QLabel(self.TaskSettings)
        self.lbl_AnimalID.setObjectName(u"lbl_AnimalID")
        self.lbl_AnimalID.setGeometry(QRect(20, 78, 61, 20))
        font2 = QFont()
        font2.setPointSize(8)
        self.lbl_AnimalID.setFont(font2)
        self.btn_Start = QPushButton(self.TaskSettings)
        self.btn_Start.setObjectName(u"btn_Start")
        self.btn_Start.setGeometry(QRect(349, 20, 61, 31))
        self.btn_Start.setStyleSheet(u"background-color: rgb(216, 244, 211);\n"
"font: 700 8pt \"Segoe UI\";")
        self.btn_Stop = QPushButton(self.TaskSettings)
        self.btn_Stop.setObjectName(u"btn_Stop")
        self.btn_Stop.setGeometry(QRect(420, 20, 61, 31))
        self.btn_Stop.setStyleSheet(u"font: 700 8pt \"Segoe UI\";\n"
"background-color: rgb(255, 203, 198);")
        self.ddm_Animal_ID = QComboBox(self.TaskSettings)
        self.ddm_Animal_ID.setObjectName(u"ddm_Animal_ID")
        self.ddm_Animal_ID.setGeometry(QRect(100, 78, 110, 21))
        font3 = QFont()
        font3.setPointSize(12)
        self.ddm_Animal_ID.setFont(font3)
        self.ddm_Animal_ID.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ddm_Animal_ID.setEditable(True)
        self.ddm_Task = QComboBox(self.TaskSettings)
        self.ddm_Task.setObjectName(u"ddm_Task")
        self.ddm_Task.setGeometry(QRect(60, 119, 261, 31))
        self.ddm_Task.setFont(font3)
        self.ddm_Task.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ddm_Task.setEditable(True)
        self.ddm_Task.setFrame(True)
        self.lbl_Task = QLabel(self.TaskSettings)
        self.lbl_Task.setObjectName(u"lbl_Task")
        self.lbl_Task.setGeometry(QRect(20, 125, 41, 19))
        self.lbl_Task.setFont(font2)
        self.lbl_TaskTimeline = QLabel(self.TaskSettings)
        self.lbl_TaskTimeline.setObjectName(u"lbl_TaskTimeline")
        self.lbl_TaskTimeline.setGeometry(QRect(20, 324, 131, 19))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setUnderline(True)
        self.lbl_TaskTimeline.setFont(font4)
        self.lbl_TaskTimeline.setStyleSheet(u"")
        self.lbl_RigParams = QLabel(self.TaskSettings)
        self.lbl_RigParams.setObjectName(u"lbl_RigParams")
        self.lbl_RigParams.setGeometry(QRect(20, 177, 131, 19))
        self.lbl_RigParams.setFont(font4)
        self.chk_BlueLED = QRadioButton(self.TaskSettings)
        self.chk_BlueLED.setObjectName(u"chk_BlueLED")
        self.chk_BlueLED.setGeometry(QRect(20, 209, 89, 20))
        font5 = QFont()
        font5.setPointSize(9)
        self.chk_BlueLED.setFont(font5)
        self.chk_WhiteLED_Left = QRadioButton(self.TaskSettings)
        self.chk_WhiteLED_Left.setObjectName(u"chk_WhiteLED_Left")
        self.chk_WhiteLED_Left.setGeometry(QRect(20, 239, 111, 20))
        self.chk_WhiteLED_Left.setFont(font5)
        self.chk_10Tone = QRadioButton(self.TaskSettings)
        self.chk_10Tone.setObjectName(u"chk_10Tone")
        self.chk_10Tone.setGeometry(QRect(179, 209, 101, 20))
        self.chk_10Tone.setFont(font5)
        self.chk_5Tone = QRadioButton(self.TaskSettings)
        self.chk_5Tone.setObjectName(u"chk_5Tone")
        self.chk_5Tone.setGeometry(QRect(179, 239, 89, 20))
        self.chk_5Tone.setFont(font5)
        self.chk_Reward_right = QRadioButton(self.TaskSettings)
        self.chk_Reward_right.setObjectName(u"chk_Reward_right")
        self.chk_Reward_right.setGeometry(QRect(331, 209, 151, 20))
        self.chk_Reward_right.setFont(font5)
        self.chk_Punishment = QRadioButton(self.TaskSettings)
        self.chk_Punishment.setObjectName(u"chk_Punishment")
        self.chk_Punishment.setGeometry(QRect(331, 239, 121, 20))
        self.chk_Punishment.setFont(font5)
        self.lbl_QuietWindow = QLabel(self.TaskSettings)
        self.lbl_QuietWindow.setObjectName(u"lbl_QuietWindow")
        self.lbl_QuietWindow.setGeometry(QRect(23, 360, 90, 20))
        self.lbl_QuietWindow.setFont(font5)
        self.txt_QuietWindow = QLineEdit(self.TaskSettings)
        self.txt_QuietWindow.setObjectName(u"txt_QuietWindow")
        self.txt_QuietWindow.setGeometry(QRect(110, 359, 51, 22))
        self.txt_QuietWindow.setFont(font5)
        self.lbl_QW_s = QLabel(self.TaskSettings)
        self.lbl_QW_s.setObjectName(u"lbl_QW_s")
        self.lbl_QW_s.setGeometry(QRect(173, 360, 41, 20))
        self.lbl_QW_s.setFont(font5)
        self.lbl_RW_s = QLabel(self.TaskSettings)
        self.lbl_RW_s.setObjectName(u"lbl_RW_s")
        self.lbl_RW_s.setGeometry(QRect(193, 398, 41, 20))
        self.lbl_RW_s.setFont(font5)
        self.txt_ResponseWindow = QLineEdit(self.TaskSettings)
        self.txt_ResponseWindow.setObjectName(u"txt_ResponseWindow")
        self.txt_ResponseWindow.setGeometry(QRect(130, 397, 51, 22))
        self.txt_ResponseWindow.setFont(font5)
        self.lbl_ResponseWindow = QLabel(self.TaskSettings)
        self.lbl_ResponseWindow.setObjectName(u"lbl_ResponseWindow")
        self.lbl_ResponseWindow.setGeometry(QRect(24, 398, 101, 20))
        self.lbl_ResponseWindow.setFont(font5)
        self.txt_ITImin = QLineEdit(self.TaskSettings)
        self.txt_ITImin.setObjectName(u"txt_ITImin")
        self.txt_ITImin.setGeometry(QRect(80, 436, 51, 22))
        self.txt_ITImin.setFont(font5)
        self.lbl_ITI = QLabel(self.TaskSettings)
        self.lbl_ITI.setObjectName(u"lbl_ITI")
        self.lbl_ITI.setGeometry(QRect(25, 438, 21, 20))
        self.lbl_ITI.setFont(font5)
        self.lbl_TD_s = QLabel(self.TaskSettings)
        self.lbl_TD_s.setObjectName(u"lbl_TD_s")
        self.lbl_TD_s.setGeometry(QRect(134, 437, 16, 20))
        self.lbl_TD_s.setFont(font5)
        self.lbl_RewardParams = QLabel(self.TaskSettings)
        self.lbl_RewardParams.setObjectName(u"lbl_RewardParams")
        self.lbl_RewardParams.setGeometry(QRect(20, 609, 131, 19))
        self.lbl_RewardParams.setFont(font4)
        self.lbl_RewardParams.setStyleSheet(u"")
        self.lbl_VO_ms = QLabel(self.TaskSettings)
        self.lbl_VO_ms.setObjectName(u"lbl_VO_ms")
        self.lbl_VO_ms.setGeometry(QRect(173, 643, 41, 20))
        self.lbl_VO_ms.setFont(font5)
        self.txt_ValveOpening = QLineEdit(self.TaskSettings)
        self.txt_ValveOpening.setObjectName(u"txt_ValveOpening")
        self.txt_ValveOpening.setGeometry(QRect(110, 642, 51, 22))
        self.txt_ValveOpening.setFont(font5)
        self.lbl_ValveOpening = QLabel(self.TaskSettings)
        self.lbl_ValveOpening.setObjectName(u"lbl_ValveOpening")
        self.lbl_ValveOpening.setGeometry(QRect(23, 643, 90, 20))
        self.lbl_ValveOpening.setFont(font5)
        self.lbl_OptoProtocols = QLabel(self.TaskSettings)
        self.lbl_OptoProtocols.setObjectName(u"lbl_OptoProtocols")
        self.lbl_OptoProtocols.setGeometry(QRect(20, 687, 131, 19))
        self.lbl_OptoProtocols.setFont(font4)
        self.chk_OptoShort = QCheckBox(self.TaskSettings)
        self.chk_OptoShort.setObjectName(u"chk_OptoShort")
        self.chk_OptoShort.setGeometry(QRect(20, 722, 161, 20))
        self.chk_OptoShort.setFont(font5)
        self.chk_OptoLong = QCheckBox(self.TaskSettings)
        self.chk_OptoLong.setObjectName(u"chk_OptoLong")
        self.chk_OptoLong.setGeometry(QRect(21, 752, 161, 20))
        self.chk_OptoLong.setFont(font5)
        self.chk_WhiteLED_Right = QRadioButton(self.TaskSettings)
        self.chk_WhiteLED_Right.setObjectName(u"chk_WhiteLED_Right")
        self.chk_WhiteLED_Right.setGeometry(QRect(20, 270, 121, 20))
        self.chk_WhiteLED_Right.setFont(font5)
        self.txt_Date = QLabel(self.TaskSettings)
        self.txt_Date.setObjectName(u"txt_Date")
        self.txt_Date.setGeometry(QRect(60, 20, 91, 16))
        self.txt_Date.setFont(font2)
        self.lbl_Date = QLabel(self.TaskSettings)
        self.lbl_Date.setObjectName(u"lbl_Date")
        self.lbl_Date.setGeometry(QRect(20, 18, 31, 20))
        self.lbl_Date.setFont(font2)
        self.btn_Update = QPushButton(self.TaskSettings)
        self.btn_Update.setObjectName(u"btn_Update")
        self.btn_Update.setGeometry(QRect(378, 120, 71, 31))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(True)
        self.btn_Update.setFont(font6)
        self.btn_Update.setStyleSheet(u"background-color: rgb(255, 225, 205);\n"
"border-color: rgb(227, 153, 100);")
        self.chk_Reward_left = QRadioButton(self.TaskSettings)
        self.chk_Reward_left.setObjectName(u"chk_Reward_left")
        self.chk_Reward_left.setGeometry(QRect(179, 269, 141, 20))
        self.chk_Reward_left.setFont(font5)
        self.lbl_AssociationTrials = QLabel(self.TaskSettings)
        self.lbl_AssociationTrials.setObjectName(u"lbl_AssociationTrials")
        self.lbl_AssociationTrials.setGeometry(QRect(21, 487, 131, 19))
        self.lbl_AssociationTrials.setFont(font4)
        self.lbl_AssociationTrials.setStyleSheet(u"")
        self.chk_AutomaticRewards = QCheckBox(self.TaskSettings)
        self.chk_AutomaticRewards.setObjectName(u"chk_AutomaticRewards")
        self.chk_AutomaticRewards.setGeometry(QRect(22, 517, 161, 20))
        self.chk_AutomaticRewards.setFont(font5)
        self.lbl_Box = QLabel(self.TaskSettings)
        self.lbl_Box.setObjectName(u"lbl_Box")
        self.lbl_Box.setGeometry(QRect(251, 76, 31, 20))
        self.lbl_Box.setFont(font2)
        self.ddm_Box = QComboBox(self.TaskSettings)
        self.ddm_Box.setObjectName(u"ddm_Box")
        self.ddm_Box.setGeometry(QRect(281, 76, 71, 21))
        self.ddm_Box.setFont(font3)
        self.ddm_Box.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ddm_Box.setEditable(True)
        self.chk_NoPunishment = QCheckBox(self.TaskSettings)
        self.chk_NoPunishment.setObjectName(u"chk_NoPunishment")
        self.chk_NoPunishment.setGeometry(QRect(22, 537, 160, 30))
        self.chk_NoPunishment.setFont(font5)
        self.lbl_AssociationTrials_2 = QLabel(self.TaskSettings)
        self.lbl_AssociationTrials_2.setObjectName(u"lbl_AssociationTrials_2")
        self.lbl_AssociationTrials_2.setGeometry(QRect(278, 496, 40, 19))
        self.lbl_AssociationTrials_2.setFont(font4)
        self.lbl_AssociationTrials_2.setStyleSheet(u"color: rgb(171, 78, 15);")
        self.lbl_QuietWindow_2 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_2.setObjectName(u"lbl_QuietWindow_2")
        self.lbl_QuietWindow_2.setGeometry(QRect(248, 518, 101, 21))
        self.lbl_QuietWindow_2.setFont(font2)
        self.lbl_QuietWindow_2.setStyleSheet(u"color: rgb(171, 78, 15);")
        self.lbl_QuietWindow_3 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_3.setObjectName(u"lbl_QuietWindow_3")
        self.lbl_QuietWindow_3.setGeometry(QRect(248, 538, 101, 21))
        self.lbl_QuietWindow_3.setFont(font2)
        self.lbl_QuietWindow_3.setStyleSheet(u"color: rgb(171, 78, 15);")
        self.lbl_QuietWindow_4 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_4.setObjectName(u"lbl_QuietWindow_4")
        self.lbl_QuietWindow_4.setGeometry(QRect(248, 558, 101, 21))
        self.lbl_QuietWindow_4.setFont(font2)
        self.lbl_QuietWindow_4.setStyleSheet(u"color: rgb(171, 78, 15);")
        self.lbl_AssociationTrials_3 = QLabel(self.TaskSettings)
        self.lbl_AssociationTrials_3.setObjectName(u"lbl_AssociationTrials_3")
        self.lbl_AssociationTrials_3.setGeometry(QRect(396, 495, 40, 19))
        self.lbl_AssociationTrials_3.setFont(font4)
        self.lbl_AssociationTrials_3.setStyleSheet(u"color: rgb(32, 95, 95);")
        self.lbl_QuietWindow_5 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_5.setObjectName(u"lbl_QuietWindow_5")
        self.lbl_QuietWindow_5.setGeometry(QRect(374, 518, 101, 21))
        self.lbl_QuietWindow_5.setFont(font2)
        self.lbl_QuietWindow_5.setStyleSheet(u"color: rgb(32, 95, 95);")
        self.lbl_QuietWindow_7 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_7.setObjectName(u"lbl_QuietWindow_7")
        self.lbl_QuietWindow_7.setGeometry(QRect(374, 538, 101, 21))
        self.lbl_QuietWindow_7.setFont(font2)
        self.lbl_QuietWindow_7.setStyleSheet(u"color: rgb(32, 95, 95);")
        self.chk_IgnoreLicksWW = QCheckBox(self.TaskSettings)
        self.chk_IgnoreLicksWW.setObjectName(u"chk_IgnoreLicksWW")
        self.chk_IgnoreLicksWW.setGeometry(QRect(23, 564, 191, 30))
        self.chk_IgnoreLicksWW.setFont(font5)
        self.lbl_TrialDuration_2 = QLabel(self.TaskSettings)
        self.lbl_TrialDuration_2.setObjectName(u"lbl_TrialDuration_2")
        self.lbl_TrialDuration_2.setGeometry(QRect(54, 437, 21, 20))
        self.lbl_TrialDuration_2.setFont(font5)
        self.lbl_TrialDuration_2.setStyleSheet(u"color: rgb(107, 107, 107);")
        self.lbl_TrialDuration_3 = QLabel(self.TaskSettings)
        self.lbl_TrialDuration_3.setObjectName(u"lbl_TrialDuration_3")
        self.lbl_TrialDuration_3.setGeometry(QRect(154, 437, 16, 20))
        self.lbl_TrialDuration_3.setFont(font5)
        self.lbl_TD_s_2 = QLabel(self.TaskSettings)
        self.lbl_TD_s_2.setObjectName(u"lbl_TD_s_2")
        self.lbl_TD_s_2.setGeometry(QRect(224, 437, 16, 20))
        self.lbl_TD_s_2.setFont(font5)
        self.txt_ITImax = QLineEdit(self.TaskSettings)
        self.txt_ITImax.setObjectName(u"txt_ITImax")
        self.txt_ITImax.setGeometry(QRect(170, 436, 51, 22))
        self.txt_ITImax.setFont(font5)
        self.lbl_TrialDuration_4 = QLabel(self.TaskSettings)
        self.lbl_TrialDuration_4.setObjectName(u"lbl_TrialDuration_4")
        self.lbl_TrialDuration_4.setGeometry(QRect(242, 437, 31, 20))
        self.lbl_TrialDuration_4.setFont(font5)
        self.lbl_TrialDuration_4.setStyleSheet(u"color: rgb(107, 107, 107);")
        self.lbl_TaskSettings = QLabel(self.Box)
        self.lbl_TaskSettings.setObjectName(u"lbl_TaskSettings")
        self.lbl_TaskSettings.setGeometry(QRect(20, 6, 111, 20))
        font7 = QFont()
        font7.setPointSize(10)
        font7.setBold(True)
        self.lbl_TaskSettings.setFont(font7)
        self.lbl_TaskSettings.setStyleSheet(u"color: rgb(217, 112, 7);")
        self.lbl_TaskSettings.setFrameShape(QFrame.NoFrame)
        self.lbl_TaskSettings.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_Visualization = QLabel(self.Box)
        self.lbl_Visualization.setObjectName(u"lbl_Visualization")
        self.lbl_Visualization.setGeometry(QRect(559, 6, 111, 20))
        self.lbl_Visualization.setFont(font7)
        self.lbl_Visualization.setStyleSheet(u"\n"
"color: rgb(73, 192, 203);")
        self.lbl_Visualization.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.line = QFrame(self.Box)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(520, 10, 20, 821))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_AnimalPerformance = QLabel(self.Box)
        self.lbl_AnimalPerformance.setObjectName(u"lbl_AnimalPerformance")
        self.lbl_AnimalPerformance.setGeometry(QRect(1131, 15, 131, 20))
        self.lbl_AnimalPerformance.setFont(font)
        self.lbl_AnimalPerformance.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_LickTrace_right = QLabel(self.Box)
        self.lbl_LickTrace_right.setObjectName(u"lbl_LickTrace_right")
        self.lbl_LickTrace_right.setGeometry(QRect(1130, 302, 141, 20))
        self.lbl_LickTrace_right.setFont(font)
        self.lbl_LickTrace_right.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_LickTrace_left = QLabel(self.Box)
        self.lbl_LickTrace_left.setObjectName(u"lbl_LickTrace_left")
        self.lbl_LickTrace_left.setGeometry(QRect(1130, 570, 131, 20))
        self.lbl_LickTrace_left.setFont(font)
        self.lbl_LickTrace_left.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_Time = QLabel(self.Box)
        self.lbl_Time.setObjectName(u"lbl_Time")
        self.lbl_Time.setGeometry(QRect(693, 35, 41, 20))
        self.lbl_Time.setFont(font7)
        self.bkg_Blocks = QWidget(self.Box)
        self.bkg_Blocks.setObjectName(u"bkg_Blocks")
        self.bkg_Blocks.setGeometry(QRect(574, 433, 471, 31))
        self.bkg_Blocks.setStyleSheet(u"background-color: rgb(214, 236, 238);")
        self.layoutWidget_2 = QWidget(self.bkg_Blocks)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(8, 4, 451, 20))
        self.Layout_B1_Blocks = QHBoxLayout(self.layoutWidget_2)
        self.Layout_B1_Blocks.setSpacing(16)
        self.Layout_B1_Blocks.setObjectName(u"Layout_B1_Blocks")
        self.Layout_B1_Blocks.setContentsMargins(0, 0, 0, 0)
        self.label_58 = QLabel(self.layoutWidget_2)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setFont(font)
        self.label_58.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_58)

        self.label_59 = QLabel(self.layoutWidget_2)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setFont(font)
        self.label_59.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_59)

        self.label_60 = QLabel(self.layoutWidget_2)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setFont(font)
        self.label_60.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_60)

        self.label_91 = QLabel(self.layoutWidget_2)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setFont(font)
        self.label_91.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_91)

        self.label_92 = QLabel(self.layoutWidget_2)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setFont(font)
        self.label_92.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_92)

        self.label_93 = QLabel(self.layoutWidget_2)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setFont(font)
        self.label_93.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_93)

        self.label_94 = QLabel(self.layoutWidget_2)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setFont(font)
        self.label_94.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_94)

        self.label_95 = QLabel(self.layoutWidget_2)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setFont(font)
        self.label_95.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_95)

        self.label_96 = QLabel(self.layoutWidget_2)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setFont(font)
        self.label_96.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_96)

        self.label_97 = QLabel(self.layoutWidget_2)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setFont(font)
        self.label_97.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_97)

        self.label_98 = QLabel(self.layoutWidget_2)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setFont(font)
        self.label_98.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_98)

        self.label_99 = QLabel(self.layoutWidget_2)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setFont(font)
        self.label_99.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_99)

        self.label_100 = QLabel(self.layoutWidget_2)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setFont(font)
        self.label_100.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_100)

        self.label_101 = QLabel(self.layoutWidget_2)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setFont(font)
        self.label_101.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_101)

        self.label_102 = QLabel(self.layoutWidget_2)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setFont(font)
        self.label_102.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_102)

        self.bkg_LeftSpout = QWidget(self.Box)
        self.bkg_LeftSpout.setObjectName(u"bkg_LeftSpout")
        self.bkg_LeftSpout.setGeometry(QRect(574, 467, 471, 30))
        self.bkg_LeftSpout.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.layoutWidget = QWidget(self.bkg_LeftSpout)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 9, 448, 20))
        self.Layout_B1_LeftSpout = QHBoxLayout(self.layoutWidget)
        self.Layout_B1_LeftSpout.setSpacing(19)
        self.Layout_B1_LeftSpout.setObjectName(u"Layout_B1_LeftSpout")
        self.Layout_B1_LeftSpout.setSizeConstraint(QLayout.SetNoConstraint)
        self.Layout_B1_LeftSpout.setContentsMargins(0, 0, 0, 0)
        self.label_76 = QLabel(self.layoutWidget)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_76)

        self.label_77 = QLabel(self.layoutWidget)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_77)

        self.label_78 = QLabel(self.layoutWidget)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_78)

        self.label_79 = QLabel(self.layoutWidget)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_79)

        self.label_80 = QLabel(self.layoutWidget)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_80)

        self.label_81 = QLabel(self.layoutWidget)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_81)

        self.label_82 = QLabel(self.layoutWidget)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_82)

        self.label_83 = QLabel(self.layoutWidget)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_83)

        self.label_84 = QLabel(self.layoutWidget)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_84)

        self.label_85 = QLabel(self.layoutWidget)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_85)

        self.label_86 = QLabel(self.layoutWidget)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_86)

        self.label_87 = QLabel(self.layoutWidget)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_87)

        self.label_88 = QLabel(self.layoutWidget)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_88)

        self.label_89 = QLabel(self.layoutWidget)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_89)

        self.label_90 = QLabel(self.layoutWidget)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_90)

        self.bkg_RightSpout = QWidget(self.Box)
        self.bkg_RightSpout.setObjectName(u"bkg_RightSpout")
        self.bkg_RightSpout.setGeometry(QRect(574, 502, 471, 31))
        self.bkg_RightSpout.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.layoutWidget1 = QWidget(self.bkg_RightSpout)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 9, 448, 20))
        self.Layout_B1_RightSpout = QHBoxLayout(self.layoutWidget1)
        self.Layout_B1_RightSpout.setSpacing(19)
        self.Layout_B1_RightSpout.setObjectName(u"Layout_B1_RightSpout")
        self.Layout_B1_RightSpout.setSizeConstraint(QLayout.SetNoConstraint)
        self.Layout_B1_RightSpout.setContentsMargins(0, 0, 0, 0)
        self.label_61 = QLabel(self.layoutWidget1)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_61)

        self.label_62 = QLabel(self.layoutWidget1)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_62)

        self.label_63 = QLabel(self.layoutWidget1)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_63)

        self.label_64 = QLabel(self.layoutWidget1)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_64)

        self.label_65 = QLabel(self.layoutWidget1)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_65)

        self.label_66 = QLabel(self.layoutWidget1)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_66)

        self.label_67 = QLabel(self.layoutWidget1)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_67)

        self.label_68 = QLabel(self.layoutWidget1)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_68)

        self.label_69 = QLabel(self.layoutWidget1)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_69)

        self.label_70 = QLabel(self.layoutWidget1)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_70)

        self.label_71 = QLabel(self.layoutWidget1)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_71)

        self.label_72 = QLabel(self.layoutWidget1)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_72)

        self.label_73 = QLabel(self.layoutWidget1)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_73)

        self.label_74 = QLabel(self.layoutWidget1)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_74)

        self.label_75 = QLabel(self.layoutWidget1)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_75)

        self.bkg_Trials = QWidget(self.Box)
        self.bkg_Trials.setObjectName(u"bkg_Trials")
        self.bkg_Trials.setGeometry(QRect(574, 537, 471, 31))
        self.bkg_Trials.setStyleSheet(u"background-color: rgb(235, 235, 235);")
        self.layoutWidget_3 = QWidget(self.bkg_Trials)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(9, 8, 451, 20))
        self.Layout_B1_Trials = QHBoxLayout(self.layoutWidget_3)
        self.Layout_B1_Trials.setSpacing(17)
        self.Layout_B1_Trials.setObjectName(u"Layout_B1_Trials")
        self.Layout_B1_Trials.setContentsMargins(0, 0, 0, 0)
        self.label_103 = QLabel(self.layoutWidget_3)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setFont(font)
        self.label_103.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_103)

        self.label_104 = QLabel(self.layoutWidget_3)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setFont(font)
        self.label_104.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_104)

        self.label_105 = QLabel(self.layoutWidget_3)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setFont(font)
        self.label_105.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_105)

        self.label_106 = QLabel(self.layoutWidget_3)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setFont(font)
        self.label_106.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_106)

        self.label_107 = QLabel(self.layoutWidget_3)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setFont(font)
        self.label_107.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_107)

        self.label_108 = QLabel(self.layoutWidget_3)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setFont(font)
        self.label_108.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_108)

        self.label_109 = QLabel(self.layoutWidget_3)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setFont(font)
        self.label_109.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_109)

        self.label_110 = QLabel(self.layoutWidget_3)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setFont(font)
        self.label_110.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_110)

        self.label_111 = QLabel(self.layoutWidget_3)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setFont(font)
        self.label_111.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_111)

        self.label_112 = QLabel(self.layoutWidget_3)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setFont(font)
        self.label_112.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_112)

        self.label_113 = QLabel(self.layoutWidget_3)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setFont(font)
        self.label_113.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_113)

        self.label_114 = QLabel(self.layoutWidget_3)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setFont(font)
        self.label_114.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_114)

        self.label_115 = QLabel(self.layoutWidget_3)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setFont(font)
        self.label_115.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_115)

        self.label_116 = QLabel(self.layoutWidget_3)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setFont(font)
        self.label_116.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_116)

        self.label_117 = QLabel(self.layoutWidget_3)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setFont(font)
        self.label_117.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_117)

        self.line_3 = QFrame(self.bkg_Trials)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 0, 16, 10))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font8 = QFont()
        font8.setPointSize(9)
        font8.setBold(True)
        self.line_3.setFont(font8)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.bkg_Trials)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(40, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFont(font8)
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.bkg_Trials)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(70, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFont(font8)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.bkg_Trials)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(101, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFont(font8)
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(self.bkg_Trials)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(133, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFont(font8)
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(self.bkg_Trials)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(164, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFont(font8)
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(self.bkg_Trials)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(195, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFont(font8)
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_10 = QFrame(self.bkg_Trials)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(227, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFont(font8)
        self.line_10.setFrameShape(QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_11 = QFrame(self.bkg_Trials)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(258, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_11.sizePolicy().hasHeightForWidth())
        self.line_11.setSizePolicy(sizePolicy)
        self.line_11.setFont(font8)
        self.line_11.setFrameShape(QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_12 = QFrame(self.bkg_Trials)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(288, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setFont(font8)
        self.line_12.setFrameShape(QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_13 = QFrame(self.bkg_Trials)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(319, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setFont(font8)
        self.line_13.setFrameShape(QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_15 = QFrame(self.bkg_Trials)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(348, 0, 20, 11))
        sizePolicy.setHeightForWidth(self.line_15.sizePolicy().hasHeightForWidth())
        self.line_15.setSizePolicy(sizePolicy)
        self.line_15.setFont(font8)
        self.line_15.setFrameShape(QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_14 = QFrame(self.bkg_Trials)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(381, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_14.sizePolicy().hasHeightForWidth())
        self.line_14.setSizePolicy(sizePolicy)
        self.line_14.setFont(font8)
        self.line_14.setFrameShape(QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_16 = QFrame(self.bkg_Trials)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(413, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_16.sizePolicy().hasHeightForWidth())
        self.line_16.setSizePolicy(sizePolicy)
        self.line_16.setFont(font8)
        self.line_16.setFrameShape(QFrame.Shape.VLine)
        self.line_16.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_17 = QFrame(self.bkg_Trials)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(444, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        self.line_17.setFont(font8)
        self.line_17.setFrameShape(QFrame.Shape.VLine)
        self.line_17.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_TrialMonitor = QLabel(self.Box)
        self.lbl_TrialMonitor.setObjectName(u"lbl_TrialMonitor")
        self.lbl_TrialMonitor.setGeometry(QRect(734, 378, 131, 20))
        font9 = QFont()
        font9.setPointSize(11)
        self.lbl_TrialMonitor.setFont(font9)
        self.lbl_TrialMonitor.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_LegendTrialMonitor = QLabel(self.Box)
        self.lbl_LegendTrialMonitor.setObjectName(u"lbl_LegendTrialMonitor")
        self.lbl_LegendTrialMonitor.setGeometry(QRect(580, 406, 451, 20))
        font10 = QFont()
        font10.setPointSize(7)
        self.lbl_LegendTrialMonitor.setFont(font10)
        self.lbl_LegendTrialMonitor.setStyleSheet(u"\n"
"color: rgb(112, 112, 112);")
        self.lbl_LegendTrialMonitor.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_Blocks = QLabel(self.Box)
        self.lbl_Blocks.setObjectName(u"lbl_Blocks")
        self.lbl_Blocks.setGeometry(QRect(550, 439, 20, 20))
        self.lbl_Blocks.setFont(font7)
        self.lbl_Blocks.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_LeftSpout = QLabel(self.Box)
        self.lbl_LeftSpout.setObjectName(u"lbl_LeftSpout")
        self.lbl_LeftSpout.setGeometry(QRect(556, 473, 10, 20))
        self.lbl_LeftSpout.setFont(font7)
        self.lbl_LeftSpout.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_RightSpout = QLabel(self.Box)
        self.lbl_RightSpout.setObjectName(u"lbl_RightSpout")
        self.lbl_RightSpout.setGeometry(QRect(551, 509, 20, 20))
        self.lbl_RightSpout.setFont(font7)
        self.lbl_RightSpout.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_Trials = QLabel(self.Box)
        self.lbl_Trials.setObjectName(u"lbl_Trials")
        self.lbl_Trials.setGeometry(QRect(551, 546, 20, 20))
        self.lbl_Trials.setFont(font7)
        self.lbl_Trials.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_AutomRewards = QLabel(self.Box)
        self.lbl_AutomRewards.setObjectName(u"lbl_AutomRewards")
        self.lbl_AutomRewards.setGeometry(QRect(573, 674, 61, 16))
        self.lbl_AutomRewards.setFont(font)
        self.lbl_CorrectTrials = QLabel(self.Box)
        self.lbl_CorrectTrials.setObjectName(u"lbl_CorrectTrials")
        self.lbl_CorrectTrials.setGeometry(QRect(744, 674, 81, 16))
        self.lbl_CorrectTrials.setFont(font)
        self.lbl_IncorrectTrials = QLabel(self.Box)
        self.lbl_IncorrectTrials.setObjectName(u"lbl_IncorrectTrials")
        self.lbl_IncorrectTrials.setGeometry(QRect(737, 715, 91, 16))
        self.lbl_IncorrectTrials.setFont(font)
        self.box_Omissions = QLabel(self.Box)
        self.box_Omissions.setObjectName(u"box_Omissions")
        self.box_Omissions.setGeometry(QRect(648, 714, 41, 20))
        font11 = QFont()
        font11.setPointSize(10)
        font11.setBold(False)
        self.box_Omissions.setFont(font11)
        self.box_Omissions.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Omissions.setAlignment(Qt.AlignCenter)
        self.lbl_Omissions = QLabel(self.Box)
        self.lbl_Omissions.setObjectName(u"lbl_Omissions")
        self.lbl_Omissions.setGeometry(QRect(571, 712, 71, 20))
        self.lbl_Omissions.setFont(font)
        self.lbl_EarlyLicks = QLabel(self.Box)
        self.lbl_EarlyLicks.setObjectName(u"lbl_EarlyLicks")
        self.lbl_EarlyLicks.setGeometry(QRect(573, 752, 61, 20))
        self.lbl_EarlyLicks.setFont(font)
        self.box_EarlyLicks = QLabel(self.Box)
        self.box_EarlyLicks.setObjectName(u"box_EarlyLicks")
        self.box_EarlyLicks.setGeometry(QRect(648, 754, 41, 20))
        self.box_EarlyLicks.setFont(font11)
        self.box_EarlyLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_EarlyLicks.setAlignment(Qt.AlignCenter)
        self.box_AutomRewards = QLabel(self.Box)
        self.box_AutomRewards.setObjectName(u"box_AutomRewards")
        self.box_AutomRewards.setGeometry(QRect(648, 674, 41, 20))
        self.box_AutomRewards.setFont(font11)
        self.box_AutomRewards.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_AutomRewards.setAlignment(Qt.AlignCenter)
        self.box_IncorrectTrials = QLabel(self.Box)
        self.box_IncorrectTrials.setObjectName(u"box_IncorrectTrials")
        self.box_IncorrectTrials.setGeometry(QRect(837, 715, 41, 20))
        self.box_IncorrectTrials.setFont(font11)
        self.box_IncorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_IncorrectTrials.setAlignment(Qt.AlignCenter)
        self.box_CorrectTrials = QLabel(self.Box)
        self.box_CorrectTrials.setObjectName(u"box_CorrectTrials")
        self.box_CorrectTrials.setGeometry(QRect(836, 673, 41, 20))
        self.box_CorrectTrials.setFont(font11)
        self.box_CorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_CorrectTrials.setAlignment(Qt.AlignCenter)
        self.box_SoundBlocks = QLabel(self.Box)
        self.box_SoundBlocks.setObjectName(u"box_SoundBlocks")
        self.box_SoundBlocks.setGeometry(QRect(837, 755, 41, 20))
        self.box_SoundBlocks.setFont(font11)
        self.box_SoundBlocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_SoundBlocks.setAlignment(Qt.AlignCenter)
        self.lbl_SoundBlocks = QLabel(self.Box)
        self.lbl_SoundBlocks.setObjectName(u"lbl_SoundBlocks")
        self.lbl_SoundBlocks.setGeometry(QRect(745, 755, 81, 16))
        self.lbl_SoundBlocks.setFont(font)
        self.box_Action_L_blocks = QLabel(self.Box)
        self.box_Action_L_blocks.setObjectName(u"box_Action_L_blocks")
        self.box_Action_L_blocks.setGeometry(QRect(1015, 675, 41, 20))
        self.box_Action_L_blocks.setFont(font11)
        self.box_Action_L_blocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Action_L_blocks.setAlignment(Qt.AlignCenter)
        self.lbl_ActionLBlocks = QLabel(self.Box)
        self.lbl_ActionLBlocks.setObjectName(u"lbl_ActionLBlocks")
        self.lbl_ActionLBlocks.setGeometry(QRect(917, 675, 91, 16))
        self.lbl_ActionLBlocks.setFont(font)
        self.box_Action_R_blocks = QLabel(self.Box)
        self.box_Action_R_blocks.setObjectName(u"box_Action_R_blocks")
        self.box_Action_R_blocks.setGeometry(QRect(1015, 715, 41, 20))
        self.box_Action_R_blocks.setFont(font11)
        self.box_Action_R_blocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Action_R_blocks.setAlignment(Qt.AlignCenter)
        self.lbl_ActionRBlocks = QLabel(self.Box)
        self.lbl_ActionRBlocks.setObjectName(u"lbl_ActionRBlocks")
        self.lbl_ActionRBlocks.setGeometry(QRect(917, 715, 91, 16))
        self.lbl_ActionRBlocks.setFont(font)
        self.txt_Chronometer = QLabel(self.Box)
        self.txt_Chronometer.setObjectName(u"txt_Chronometer")
        self.txt_Chronometer.setGeometry(QRect(737, 34, 160, 21))
        self.txt_Chronometer.setFont(font1)
        self.txt_Chronometer.setAlignment(Qt.AlignCenter)
        self.lbl_Bias = QLabel(self.Box)
        self.lbl_Bias.setObjectName(u"lbl_Bias")
        self.lbl_Bias.setGeometry(QRect(980, 755, 31, 16))
        self.lbl_Bias.setFont(font)
        self.box_Bias = QLabel(self.Box)
        self.box_Bias.setObjectName(u"box_Bias")
        self.box_Bias.setGeometry(QRect(1016, 755, 41, 20))
        self.box_Bias.setFont(font11)
        self.box_Bias.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Bias.setAlignment(Qt.AlignCenter)
        self.plt_Camera = QLabel(self.Box)
        self.plt_Camera.setObjectName(u"plt_Camera")
        self.plt_Camera.setGeometry(QRect(600, 80, 411, 271))
        self.plt_Camera.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.plt_AnimalPerformance = QLabel(self.Box)
        self.plt_AnimalPerformance.setObjectName(u"plt_AnimalPerformance")
        self.plt_AnimalPerformance.setGeometry(QRect(1120, 40, 431, 231))
        self.plt_AnimalPerformance.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.plt_LickTrace_Right = QWidget(self.Box)
        self.plt_LickTrace_Right.setObjectName(u"plt_LickTrace_Right")
        self.plt_LickTrace_Right.setGeometry(QRect(1120, 328, 431, 211))
        self.plt_LickTrace_Right.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.plt_LickTrace_Left = QWidget(self.Box)
        self.plt_LickTrace_Left.setObjectName(u"plt_LickTrace_Left")
        self.plt_LickTrace_Left.setGeometry(QRect(1120, 597, 431, 211))
        self.plt_LickTrace_Left.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.lbl_LicksRight = QLabel(self.Box)
        self.lbl_LicksRight.setObjectName(u"lbl_LicksRight")
        self.lbl_LicksRight.setGeometry(QRect(943, 793, 71, 21))
        self.lbl_LicksRight.setFont(font)
        self.box_LicksRight = QLabel(self.Box)
        self.box_LicksRight.setObjectName(u"box_LicksRight")
        self.box_LicksRight.setGeometry(QRect(1017, 794, 40, 20))
        self.box_LicksRight.setFont(font11)
        self.box_LicksRight.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_LicksRight.setAlignment(Qt.AlignCenter)
        self.box_TotalLicks = QLabel(self.Box)
        self.box_TotalLicks.setObjectName(u"box_TotalLicks")
        self.box_TotalLicks.setGeometry(QRect(650, 792, 40, 20))
        self.box_TotalLicks.setFont(font11)
        self.box_TotalLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_TotalLicks.setAlignment(Qt.AlignCenter)
        self.lbl_TotalLicks = QLabel(self.Box)
        self.lbl_TotalLicks.setObjectName(u"lbl_TotalLicks")
        self.lbl_TotalLicks.setGeometry(QRect(570, 792, 70, 20))
        self.lbl_TotalLicks.setFont(font)
        self.lbl_LicksLeft = QLabel(self.Box)
        self.lbl_LicksLeft.setObjectName(u"lbl_LicksLeft")
        self.lbl_LicksLeft.setGeometry(QRect(770, 796, 61, 16))
        self.lbl_LicksLeft.setFont(font)
        self.box_LicksLeft = QLabel(self.Box)
        self.box_LicksLeft.setObjectName(u"box_LicksLeft")
        self.box_LicksLeft.setGeometry(QRect(838, 795, 40, 20))
        self.box_LicksLeft.setFont(font11)
        self.box_LicksLeft.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_LicksLeft.setAlignment(Qt.AlignCenter)
        self.lbl_TR_s = QLabel(self.Box)
        self.lbl_TR_s.setObjectName(u"lbl_TR_s")
        self.lbl_TR_s.setGeometry(QRect(1538, 303, 21, 20))
        self.lbl_TR_s.setFont(font5)
        self.lbl_ThresholdRight = QLabel(self.Box)
        self.lbl_ThresholdRight.setObjectName(u"lbl_ThresholdRight")
        self.lbl_ThresholdRight.setGeometry(QRect(1379, 303, 101, 20))
        self.lbl_ThresholdRight.setFont(font)
        self.lbl_ThresholdRight.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.txt_ThresholdRight = QLineEdit(self.Box)
        self.txt_ThresholdRight.setObjectName(u"txt_ThresholdRight")
        self.txt_ThresholdRight.setGeometry(QRect(1480, 302, 51, 22))
        self.txt_ThresholdRight.setFont(font5)
        self.lbl_TL_s = QLabel(self.Box)
        self.lbl_TL_s.setObjectName(u"lbl_TL_s")
        self.lbl_TL_s.setGeometry(QRect(1538, 573, 21, 20))
        self.lbl_TL_s.setFont(font5)
        self.txt_ThresholdLeft = QLineEdit(self.Box)
        self.txt_ThresholdLeft.setObjectName(u"txt_ThresholdLeft")
        self.txt_ThresholdLeft.setGeometry(QRect(1480, 572, 51, 22))
        self.txt_ThresholdLeft.setFont(font5)
        self.lbl_ThresholdLeft = QLabel(self.Box)
        self.lbl_ThresholdLeft.setObjectName(u"lbl_ThresholdLeft")
        self.lbl_ThresholdLeft.setGeometry(QRect(1387, 573, 91, 20))
        self.lbl_ThresholdLeft.setFont(font)
        self.lbl_ThresholdLeft.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.lbl_TrialDuration = QLabel(self.Box)
        self.lbl_TrialDuration.setObjectName(u"lbl_TrialDuration")
        self.lbl_TrialDuration.setGeometry(QRect(571, 596, 81, 16))
        font12 = QFont()
        font12.setPointSize(10)
        font12.setBold(False)
        font12.setUnderline(True)
        self.lbl_TrialDuration.setFont(font12)
        self.box_TrialDuration = QLabel(self.Box)
        self.box_TrialDuration.setObjectName(u"box_TrialDuration")
        self.box_TrialDuration.setGeometry(QRect(658, 596, 51, 20))
        self.box_TrialDuration.setFont(font11)
        self.box_TrialDuration.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_TrialDuration.setAlignment(Qt.AlignCenter)
        self.lbl_VO_ms_2 = QLabel(self.Box)
        self.lbl_VO_ms_2.setObjectName(u"lbl_VO_ms_2")
        self.lbl_VO_ms_2.setGeometry(QRect(717, 596, 16, 20))
        self.lbl_VO_ms_2.setFont(font5)
        self.box_5KHzTrials = QLabel(self.Box)
        self.box_5KHzTrials.setObjectName(u"box_5KHzTrials")
        self.box_5KHzTrials.setGeometry(QRect(835, 633, 41, 20))
        self.box_5KHzTrials.setFont(font11)
        self.box_5KHzTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_5KHzTrials.setAlignment(Qt.AlignCenter)
        self.lbl_10KHzTrials = QLabel(self.Box)
        self.lbl_10KHzTrials.setObjectName(u"lbl_10KHzTrials")
        self.lbl_10KHzTrials.setGeometry(QRect(931, 635, 81, 16))
        self.lbl_10KHzTrials.setFont(font)
        self.box_10KHzTrials = QLabel(self.Box)
        self.box_10KHzTrials.setObjectName(u"box_10KHzTrials")
        self.box_10KHzTrials.setGeometry(QRect(1014, 635, 41, 20))
        self.box_10KHzTrials.setFont(font11)
        self.box_10KHzTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_10KHzTrials.setAlignment(Qt.AlignCenter)
        self.lbl_5KHzTrials = QLabel(self.Box)
        self.lbl_5KHzTrials.setObjectName(u"lbl_5KHzTrials")
        self.lbl_5KHzTrials.setGeometry(QRect(755, 634, 71, 16))
        self.lbl_5KHzTrials.setFont(font)
        self.lbl_TotalTrials = QLabel(self.Box)
        self.lbl_TotalTrials.setObjectName(u"lbl_TotalTrials")
        self.lbl_TotalTrials.setGeometry(QRect(570, 633, 71, 16))
        self.lbl_TotalTrials.setFont(font)
        self.box_TotalTrials = QLabel(self.Box)
        self.box_TotalTrials.setObjectName(u"box_TotalTrials")
        self.box_TotalTrials.setGeometry(QRect(647, 633, 41, 20))
        self.box_TotalTrials.setFont(font11)
        self.box_TotalTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_TotalTrials.setAlignment(Qt.AlignCenter)
        self.Boxes.addTab(self.Box, "")
        self.bkg_Trials.raise_()
        self.TaskSettings.raise_()
        self.lbl_TaskSettings.raise_()
        self.lbl_Visualization.raise_()
        self.line.raise_()
        self.lbl_AnimalPerformance.raise_()
        self.lbl_LickTrace_right.raise_()
        self.lbl_LickTrace_left.raise_()
        self.lbl_Time.raise_()
        self.bkg_Blocks.raise_()
        self.bkg_LeftSpout.raise_()
        self.bkg_RightSpout.raise_()
        self.lbl_TrialMonitor.raise_()
        self.lbl_LegendTrialMonitor.raise_()
        self.lbl_Blocks.raise_()
        self.lbl_LeftSpout.raise_()
        self.lbl_RightSpout.raise_()
        self.lbl_Trials.raise_()
        self.lbl_AutomRewards.raise_()
        self.lbl_CorrectTrials.raise_()
        self.lbl_IncorrectTrials.raise_()
        self.box_Omissions.raise_()
        self.lbl_Omissions.raise_()
        self.lbl_EarlyLicks.raise_()
        self.box_EarlyLicks.raise_()
        self.box_AutomRewards.raise_()
        self.box_IncorrectTrials.raise_()
        self.box_CorrectTrials.raise_()
        self.box_SoundBlocks.raise_()
        self.lbl_SoundBlocks.raise_()
        self.box_Action_L_blocks.raise_()
        self.lbl_ActionLBlocks.raise_()
        self.box_Action_R_blocks.raise_()
        self.lbl_ActionRBlocks.raise_()
        self.txt_Chronometer.raise_()
        self.lbl_Bias.raise_()
        self.box_Bias.raise_()
        self.plt_Camera.raise_()
        self.plt_AnimalPerformance.raise_()
        self.plt_LickTrace_Right.raise_()
        self.plt_LickTrace_Left.raise_()
        self.lbl_LicksRight.raise_()
        self.box_LicksRight.raise_()
        self.box_TotalLicks.raise_()
        self.lbl_TotalLicks.raise_()
        self.lbl_LicksLeft.raise_()
        self.box_LicksLeft.raise_()
        self.lbl_TR_s.raise_()
        self.lbl_ThresholdRight.raise_()
        self.txt_ThresholdRight.raise_()
        self.lbl_TL_s.raise_()
        self.txt_ThresholdLeft.raise_()
        self.lbl_ThresholdLeft.raise_()
        self.lbl_TrialDuration.raise_()
        self.box_TrialDuration.raise_()
        self.lbl_VO_ms_2.raise_()
        self.box_5KHzTrials.raise_()
        self.lbl_10KHzTrials.raise_()
        self.box_10KHzTrials.raise_()
        self.lbl_5KHzTrials.raise_()
        self.lbl_TotalTrials.raise_()
        self.box_TotalTrials.raise_()
        self.Overview = QWidget()
        self.Overview.setObjectName(u"Overview")
        self.OV_Box = QGroupBox(self.Overview)
        self.OV_Box.setObjectName(u"OV_Box")
        self.OV_Box.setGeometry(QRect(10, 20, 301, 811))
        self.OV_Box.setFont(font7)
        self.OV_Box.setStyleSheet(u"border-color: rgb(81, 81, 81);\n"
"")
        self.OV_box_Chronometer = QLabel(self.OV_Box)
        self.OV_box_Chronometer.setObjectName(u"OV_box_Chronometer")
        self.OV_box_Chronometer.setGeometry(QRect(93, 69, 160, 21))
        self.OV_box_Chronometer.setFont(font1)
        self.OV_box_Chronometer.setAlignment(Qt.AlignCenter)
        self.OV_lbl_Time = QLabel(self.OV_Box)
        self.OV_lbl_Time.setObjectName(u"OV_lbl_Time")
        self.OV_lbl_Time.setGeometry(QRect(49, 70, 41, 20))
        self.OV_lbl_Time.setFont(font7)
        self.OV_lbl_Omissions = QLabel(self.OV_Box)
        self.OV_lbl_Omissions.setObjectName(u"OV_lbl_Omissions")
        self.OV_lbl_Omissions.setGeometry(QRect(100, 764, 71, 20))
        self.OV_lbl_Omissions.setFont(font)
        self.OV_box_CorrectTrials = QLabel(self.OV_Box)
        self.OV_box_CorrectTrials.setObjectName(u"OV_box_CorrectTrials")
        self.OV_box_CorrectTrials.setGeometry(QRect(180, 701, 41, 20))
        self.OV_box_CorrectTrials.setFont(font11)
        self.OV_box_CorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_CorrectTrials.setAlignment(Qt.AlignCenter)
        self.OV_box_IncorrectTrials = QLabel(self.OV_Box)
        self.OV_box_IncorrectTrials.setObjectName(u"OV_box_IncorrectTrials")
        self.OV_box_IncorrectTrials.setGeometry(QRect(180, 734, 41, 20))
        self.OV_box_IncorrectTrials.setFont(font11)
        self.OV_box_IncorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_IncorrectTrials.setAlignment(Qt.AlignCenter)
        self.OV_box_TotalTrials = QLabel(self.OV_Box)
        self.OV_box_TotalTrials.setObjectName(u"OV_box_TotalTrials")
        self.OV_box_TotalTrials.setGeometry(QRect(180, 640, 41, 20))
        self.OV_box_TotalTrials.setFont(font11)
        self.OV_box_TotalTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_TotalTrials.setAlignment(Qt.AlignCenter)
        self.OV_lbl_TotalTrials = QLabel(self.OV_Box)
        self.OV_lbl_TotalTrials.setObjectName(u"OV_lbl_TotalTrials")
        self.OV_lbl_TotalTrials.setGeometry(QRect(97, 639, 71, 16))
        self.OV_lbl_TotalTrials.setFont(font)
        self.OV_box_Omissions = QLabel(self.OV_Box)
        self.OV_box_Omissions.setObjectName(u"OV_box_Omissions")
        self.OV_box_Omissions.setGeometry(QRect(180, 767, 41, 20))
        self.OV_box_Omissions.setFont(font11)
        self.OV_box_Omissions.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_Omissions.setAlignment(Qt.AlignCenter)
        self.OV_lbl_IncorrectTrials = QLabel(self.OV_Box)
        self.OV_lbl_IncorrectTrials.setObjectName(u"OV_lbl_IncorrectTrials")
        self.OV_lbl_IncorrectTrials.setGeometry(QRect(73, 734, 91, 16))
        self.OV_lbl_IncorrectTrials.setFont(font)
        self.OV_lbl_CorrectTrials = QLabel(self.OV_Box)
        self.OV_lbl_CorrectTrials.setObjectName(u"OV_lbl_CorrectTrials")
        self.OV_lbl_CorrectTrials.setGeometry(QRect(81, 702, 81, 16))
        self.OV_lbl_CorrectTrials.setFont(font)
        self.OV_lbl_CurrentTrial = QLabel(self.OV_Box)
        self.OV_lbl_CurrentTrial.setObjectName(u"OV_lbl_CurrentTrial")
        self.OV_lbl_CurrentTrial.setGeometry(QRect(59, 600, 81, 16))
        self.OV_lbl_CurrentTrial.setFont(font)
        self.OV_lbl_CurrentTrial.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.OV_box_CurrentTrial = QLabel(self.OV_Box)
        self.OV_box_CurrentTrial.setObjectName(u"OV_box_CurrentTrial")
        self.OV_box_CurrentTrial.setGeometry(QRect(151, 600, 91, 20))
        self.OV_box_CurrentTrial.setFont(font)
        self.OV_box_CurrentTrial.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_CurrentTrial.setAlignment(Qt.AlignCenter)
        self.OV_plt_Camera = QLabel(self.OV_Box)
        self.OV_plt_Camera.setObjectName(u"OV_plt_Camera")
        self.OV_plt_Camera.setGeometry(QRect(15, 112, 271, 221))
        self.OV_plt_Camera.setStyleSheet(u"background-color: rgb(122, 122, 122);")
        self.OV_plt_AnimalPerformance = QLabel(self.OV_Box)
        self.OV_plt_AnimalPerformance.setObjectName(u"OV_plt_AnimalPerformance")
        self.OV_plt_AnimalPerformance.setGeometry(QRect(14, 347, 271, 221))
        self.OV_plt_AnimalPerformance.setStyleSheet(u"background-color: rgb(221, 255, 244);")
        self.OV_lbl_TotalLicks = QLabel(self.OV_Box)
        self.OV_lbl_TotalLicks.setObjectName(u"OV_lbl_TotalLicks")
        self.OV_lbl_TotalLicks.setGeometry(QRect(100, 671, 71, 16))
        self.OV_lbl_TotalLicks.setFont(font)
        self.OV_box_TotalLicks = QLabel(self.OV_Box)
        self.OV_box_TotalLicks.setObjectName(u"OV_box_TotalLicks")
        self.OV_box_TotalLicks.setGeometry(QRect(180, 670, 41, 20))
        self.OV_box_TotalLicks.setFont(font11)
        self.OV_box_TotalLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_TotalLicks.setAlignment(Qt.AlignCenter)
        self.OV_bkg_Task = QWidget(self.OV_Box)
        self.OV_bkg_Task.setObjectName(u"OV_bkg_Task")
        self.OV_bkg_Task.setGeometry(QRect(10, 30, 271, 21))
        self.OV_bkg_Task.setStyleSheet(u"background-color: rgb(255, 222, 206);")
        self.OV_lbl_Task = QLabel(self.OV_bkg_Task)
        self.OV_lbl_Task.setObjectName(u"OV_lbl_Task")
        self.OV_lbl_Task.setGeometry(QRect(6, 2, 31, 16))
        self.OV_lbl_Task.setFont(font8)
        self.OV_txt_Task = QLabel(self.OV_bkg_Task)
        self.OV_txt_Task.setObjectName(u"OV_txt_Task")
        self.OV_txt_Task.setGeometry(QRect(50, 0, 211, 20))
        self.OV_txt_Task.setFont(font2)
        self.OV_txt_Task.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.OV_bkg_AnimalID = QWidget(self.Overview)
        self.OV_bkg_AnimalID.setObjectName(u"OV_bkg_AnimalID")
        self.OV_bkg_AnimalID.setGeometry(QRect(20, 10, 170, 21))
        self.OV_bkg_AnimalID.setStyleSheet(u"background-color: rgb(220, 231, 255);")
        self.OV_lbl_AnimalID = QLabel(self.OV_bkg_AnimalID)
        self.OV_lbl_AnimalID.setObjectName(u"OV_lbl_AnimalID")
        self.OV_lbl_AnimalID.setGeometry(QRect(14, -1, 81, 21))
        self.OV_lbl_AnimalID.setFont(font8)
        self.OV_txt_AnimalID = QLabel(self.OV_bkg_AnimalID)
        self.OV_txt_AnimalID.setObjectName(u"OV_txt_AnimalID")
        self.OV_txt_AnimalID.setGeometry(QRect(79, -1, 71, 21))
        self.OV_txt_AnimalID.setFont(font)
        self.OV_bkg_Box = QWidget(self.Overview)
        self.OV_bkg_Box.setObjectName(u"OV_bkg_Box")
        self.OV_bkg_Box.setGeometry(QRect(200, 10, 101, 21))
        self.OV_bkg_Box.setStyleSheet(u"background-color: rgb(185, 217, 206);")
        self.OV_lbl_Box = QLabel(self.OV_bkg_Box)
        self.OV_lbl_Box.setObjectName(u"OV_lbl_Box")
        self.OV_lbl_Box.setGeometry(QRect(8, 2, 31, 16))
        self.OV_lbl_Box.setFont(font8)
        self.OV_txt_Box = QLabel(self.OV_bkg_Box)
        self.OV_txt_Box.setObjectName(u"OV_txt_Box")
        self.OV_txt_Box.setGeometry(QRect(40, 3, 51, 16))
        self.Boxes.addTab(self.Overview, "")
        TaskGui.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TaskGui)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1600, 22))
        self.menuAdaptive_sensorimotor_decision_making_task = QMenu(self.menubar)
        self.menuAdaptive_sensorimotor_decision_making_task.setObjectName(u"menuAdaptive_sensorimotor_decision_making_task")
        TaskGui.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TaskGui)
        self.statusbar.setObjectName(u"statusbar")
        TaskGui.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAdaptive_sensorimotor_decision_making_task.menuAction())

        self.retranslateUi(TaskGui)

        self.Boxes.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(TaskGui)
    # setupUi

    def retranslateUi(self, TaskGui):
        TaskGui.setWindowTitle(QCoreApplication.translate("TaskGui", u"TaskGui", None))
        self.actionAdaptive_sensorimotor_decision_making_task.setText(QCoreApplication.translate("TaskGui", u"Adaptive sensorimotor decision-making task", None))
        self.actionAdaptive_sensorimotor_decision_making_task_2.setText(QCoreApplication.translate("TaskGui", u"Adaptive sensorimotor decision-making task", None))
#if QT_CONFIG(accessibility)
        self.Box.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.lbl_AnimalID.setText(QCoreApplication.translate("TaskGui", u"Animal_ID :", None))
        self.btn_Start.setText(QCoreApplication.translate("TaskGui", u"START", None))
        self.btn_Stop.setText(QCoreApplication.translate("TaskGui", u"STOP", None))
        self.lbl_Task.setText(QCoreApplication.translate("TaskGui", u"Task :", None))
        self.lbl_TaskTimeline.setText(QCoreApplication.translate("TaskGui", u"Task Timeline Params :", None))
        self.lbl_RigParams.setText(QCoreApplication.translate("TaskGui", u"Test Rig Params :", None))
        self.chk_BlueLED.setText(QCoreApplication.translate("TaskGui", u"Blue LED", None))
        self.chk_WhiteLED_Left.setText(QCoreApplication.translate("TaskGui", u"White LED - Left", None))
        self.chk_10Tone.setText(QCoreApplication.translate("TaskGui", u"10KHz Tone", None))
        self.chk_5Tone.setText(QCoreApplication.translate("TaskGui", u"5KHz Tone", None))
        self.chk_Reward_right.setText(QCoreApplication.translate("TaskGui", u"Reward - right spout", None))
        self.chk_Punishment.setText(QCoreApplication.translate("TaskGui", u"WN - Punishment", None))
        self.lbl_QuietWindow.setText(QCoreApplication.translate("TaskGui", u"Quiet Window", None))
        self.lbl_QW_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_RW_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ResponseWindow.setText(QCoreApplication.translate("TaskGui", u"Response Window", None))
        self.lbl_ITI.setText(QCoreApplication.translate("TaskGui", u"ITI", None))
        self.lbl_TD_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_RewardParams.setText(QCoreApplication.translate("TaskGui", u"Reward Params :", None))
        self.lbl_VO_ms.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ValveOpening.setText(QCoreApplication.translate("TaskGui", u"Valve Opening", None))
        self.lbl_OptoProtocols.setText(QCoreApplication.translate("TaskGui", u"Optotagging Protocols :", None))
        self.chk_OptoShort.setText(QCoreApplication.translate("TaskGui", u"Short pulses protocol", None))
        self.chk_OptoLong.setText(QCoreApplication.translate("TaskGui", u"Long pulses protocol", None))
        self.chk_WhiteLED_Right.setText(QCoreApplication.translate("TaskGui", u"White LED - Right", None))
        self.txt_Date.setText(QCoreApplication.translate("TaskGui", u"TextLabel", None))
        self.lbl_Date.setText(QCoreApplication.translate("TaskGui", u"Date :", None))
        self.btn_Update.setText(QCoreApplication.translate("TaskGui", u"UPDATE", None))
        self.chk_Reward_left.setText(QCoreApplication.translate("TaskGui", u"Reward - left spout", None))
        self.lbl_AssociationTrials.setText(QCoreApplication.translate("TaskGui", u"Association trials :", None))
        self.chk_AutomaticRewards.setText(QCoreApplication.translate("TaskGui", u"Automatic Rewards", None))
        self.lbl_Box.setText(QCoreApplication.translate("TaskGui", u"Box:", None))
        self.chk_NoPunishment.setText(QCoreApplication.translate("TaskGui", u"No Punishment", None))
        self.lbl_AssociationTrials_2.setText(QCoreApplication.translate("TaskGui", u"Level 1", None))
        self.lbl_QuietWindow_2.setText(QCoreApplication.translate("TaskGui", u"Automatic Reward", None))
        self.lbl_QuietWindow_3.setText(QCoreApplication.translate("TaskGui", u"No punishment", None))
        self.lbl_QuietWindow_4.setText(QCoreApplication.translate("TaskGui", u"Ignore licks in WW", None))
        self.lbl_AssociationTrials_3.setText(QCoreApplication.translate("TaskGui", u"Level 2", None))
        self.lbl_QuietWindow_5.setText(QCoreApplication.translate("TaskGui", u"No punishment", None))
        self.lbl_QuietWindow_7.setText(QCoreApplication.translate("TaskGui", u"Ignore licks in WW", None))
        self.chk_IgnoreLicksWW.setText(QCoreApplication.translate("TaskGui", u"Ignore licks in Waiting Window", None))
        self.lbl_TrialDuration_2.setText(QCoreApplication.translate("TaskGui", u"min", None))
        self.lbl_TrialDuration_3.setText(QCoreApplication.translate("TaskGui", u"-", None))
        self.lbl_TD_s_2.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_TrialDuration_4.setText(QCoreApplication.translate("TaskGui", u"max", None))
        self.lbl_TaskSettings.setText(QCoreApplication.translate("TaskGui", u"Task Settings", None))
        self.lbl_Visualization.setText(QCoreApplication.translate("TaskGui", u"Visualization", None))
        self.lbl_AnimalPerformance.setText(QCoreApplication.translate("TaskGui", u"Animal's Performance", None))
        self.lbl_LickTrace_right.setText(QCoreApplication.translate("TaskGui", u"Lick Trace - Right Spout", None))
        self.lbl_LickTrace_left.setText(QCoreApplication.translate("TaskGui", u"Lick Trace - Left Spout", None))
        self.lbl_Time.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_58.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_59.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_60.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_91.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_92.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_93.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_94.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_95.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_96.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_97.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_98.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_99.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_100.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_101.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_102.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_76.setText("")
        self.label_77.setText("")
        self.label_78.setText("")
        self.label_79.setText("")
        self.label_80.setText("")
        self.label_81.setText("")
        self.label_82.setText("")
        self.label_83.setText("")
        self.label_84.setText("")
        self.label_85.setText("")
        self.label_86.setText("")
        self.label_87.setText("")
        self.label_88.setText("")
        self.label_89.setText("")
        self.label_90.setText("")
        self.label_61.setText("")
        self.label_62.setText("")
        self.label_63.setText("")
        self.label_64.setText("")
        self.label_65.setText("")
        self.label_66.setText("")
        self.label_67.setText("")
        self.label_68.setText("")
        self.label_69.setText("")
        self.label_70.setText("")
        self.label_71.setText("")
        self.label_72.setText("")
        self.label_73.setText("")
        self.label_74.setText("")
        self.label_75.setText("")
        self.label_103.setText(QCoreApplication.translate("TaskGui", u"1", None))
        self.label_104.setText(QCoreApplication.translate("TaskGui", u"2", None))
        self.label_105.setText(QCoreApplication.translate("TaskGui", u"3", None))
        self.label_106.setText(QCoreApplication.translate("TaskGui", u"4", None))
        self.label_107.setText(QCoreApplication.translate("TaskGui", u"5", None))
        self.label_108.setText(QCoreApplication.translate("TaskGui", u"6", None))
        self.label_109.setText(QCoreApplication.translate("TaskGui", u"7", None))
        self.label_110.setText(QCoreApplication.translate("TaskGui", u"8", None))
        self.label_111.setText(QCoreApplication.translate("TaskGui", u"9", None))
        self.label_112.setText(QCoreApplication.translate("TaskGui", u"10", None))
        self.label_113.setText(QCoreApplication.translate("TaskGui", u"11", None))
        self.label_114.setText(QCoreApplication.translate("TaskGui", u"12", None))
        self.label_115.setText(QCoreApplication.translate("TaskGui", u"13", None))
        self.label_116.setText(QCoreApplication.translate("TaskGui", u"14", None))
        self.label_117.setText(QCoreApplication.translate("TaskGui", u"15", None))
        self.lbl_TrialMonitor.setText(QCoreApplication.translate("TaskGui", u"Trial monitor", None))
        self.lbl_LegendTrialMonitor.setText(QCoreApplication.translate("TaskGui", u"B - Block type    L - Left spout    R- Right spout    T - Trial number    S - Sound    AL - Action left    AR - Action right", None))
        self.lbl_Blocks.setText(QCoreApplication.translate("TaskGui", u"B", None))
        self.lbl_LeftSpout.setText(QCoreApplication.translate("TaskGui", u"L", None))
        self.lbl_RightSpout.setText(QCoreApplication.translate("TaskGui", u"R", None))
        self.lbl_Trials.setText(QCoreApplication.translate("TaskGui", u"T", None))
        self.lbl_AutomRewards.setText(QCoreApplication.translate("TaskGui", u"Auto_Rew:", None))
        self.lbl_CorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.lbl_IncorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.box_Omissions.setText("")
        self.lbl_Omissions.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.lbl_EarlyLicks.setText(QCoreApplication.translate("TaskGui", u"Early licks:", None))
        self.box_EarlyLicks.setText("")
        self.box_AutomRewards.setText("")
        self.box_IncorrectTrials.setText("")
        self.box_CorrectTrials.setText("")
        self.box_SoundBlocks.setText("")
        self.lbl_SoundBlocks.setText(QCoreApplication.translate("TaskGui", u"Sound Blocks:", None))
        self.box_Action_L_blocks.setText("")
        self.lbl_ActionLBlocks.setText(QCoreApplication.translate("TaskGui", u"Action L Blocks:", None))
        self.box_Action_R_blocks.setText("")
        self.lbl_ActionRBlocks.setText(QCoreApplication.translate("TaskGui", u"Action R Blocks:", None))
        self.txt_Chronometer.setText("")
        self.lbl_Bias.setText(QCoreApplication.translate("TaskGui", u"Bias:", None))
        self.box_Bias.setText("")
        self.plt_Camera.setText("")
        self.plt_AnimalPerformance.setText("")
        self.lbl_LicksRight.setText(QCoreApplication.translate("TaskGui", u"Licks Right:", None))
        self.box_LicksRight.setText("")
        self.box_TotalLicks.setText("")
        self.lbl_TotalLicks.setText(QCoreApplication.translate("TaskGui", u"Total Licks: ", None))
        self.lbl_LicksLeft.setText(QCoreApplication.translate("TaskGui", u"Licks Left:", None))
        self.box_LicksLeft.setText("")
        self.lbl_TR_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ThresholdRight.setText(QCoreApplication.translate("TaskGui", u"Threshold Right", None))
        self.lbl_TL_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ThresholdLeft.setText(QCoreApplication.translate("TaskGui", u"Threshold Left", None))
        self.lbl_TrialDuration.setText(QCoreApplication.translate("TaskGui", u"Trial Duration:", None))
        self.box_TrialDuration.setText("")
        self.lbl_VO_ms_2.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.box_5KHzTrials.setText("")
        self.lbl_10KHzTrials.setText(QCoreApplication.translate("TaskGui", u"10KHz Trials:", None))
        self.box_10KHzTrials.setText("")
        self.lbl_5KHzTrials.setText(QCoreApplication.translate("TaskGui", u"5KHz Trials: ", None))
        self.lbl_TotalTrials.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.box_TotalTrials.setText("")
        self.Boxes.setTabText(self.Boxes.indexOf(self.Box), QCoreApplication.translate("TaskGui", u"GUI", None))
        self.OV_Box.setTitle("")
        self.OV_box_Chronometer.setText("")
        self.OV_lbl_Time.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.OV_lbl_Omissions.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.OV_box_CorrectTrials.setText("")
        self.OV_box_IncorrectTrials.setText("")
        self.OV_box_TotalTrials.setText("")
        self.OV_lbl_TotalTrials.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.OV_box_Omissions.setText("")
        self.OV_lbl_IncorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.OV_lbl_CorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.OV_lbl_CurrentTrial.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.OV_box_CurrentTrial.setText("")
        self.OV_plt_Camera.setText("")
        self.OV_plt_AnimalPerformance.setText("")
        self.OV_lbl_TotalLicks.setText(QCoreApplication.translate("TaskGui", u"Total Licks: ", None))
        self.OV_box_TotalLicks.setText("")
        self.OV_lbl_Task.setText(QCoreApplication.translate("TaskGui", u"Task:", None))
        self.OV_txt_Task.setText("")
        self.OV_lbl_AnimalID.setText(QCoreApplication.translate("TaskGui", u"Animal ID:", None))
        self.OV_txt_AnimalID.setText("")
        self.OV_lbl_Box.setText(QCoreApplication.translate("TaskGui", u"Box:", None))
        self.OV_txt_Box.setText("")
        self.Boxes.setTabText(self.Boxes.indexOf(self.Overview), QCoreApplication.translate("TaskGui", u"Overview", None))
        self.menuAdaptive_sensorimotor_decision_making_task.setTitle(QCoreApplication.translate("TaskGui", u"   Adaptive sensorimotor decision-making task  ", None))
    # retranslateUi

