# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QScrollBar, QSizePolicy,
    QStatusBar, QTabWidget, QWidget)

class Ui_TaskGui(object):
    def setupUi(self, TaskGui):
        if not TaskGui.objectName():
            TaskGui.setObjectName(u"TaskGui")
        TaskGui.resize(1600, 929)
        self.actionAdaptive_sensorimotor_decision_making_task = QAction(TaskGui)
        self.actionAdaptive_sensorimotor_decision_making_task.setObjectName(u"actionAdaptive_sensorimotor_decision_making_task")
        self.actionAdaptive_sensorimotor_decision_making_task_2 = QAction(TaskGui)
        self.actionAdaptive_sensorimotor_decision_making_task_2.setObjectName(u"actionAdaptive_sensorimotor_decision_making_task_2")
        self.centralwidget = QWidget(TaskGui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.Boxes = QTabWidget(self.centralwidget)
        self.Boxes.setObjectName(u"Boxes")
        self.Boxes.setGeometry(QRect(-1, 8, 1591, 901))
        font = QFont()
        font.setPointSize(10)
        self.Boxes.setFont(font)
        self.Box = QWidget()
        self.Box.setObjectName(u"Box")
        self.Box.setEnabled(True)
        font1 = QFont()
        font1.setPointSize(14)
        self.Box.setFont(font1)
        self.TaskSettings = QWidget(self.Box)
        self.TaskSettings.setObjectName(u"TaskSettings")
        self.TaskSettings.setGeometry(QRect(10, 30, 501, 831))
        self.TaskSettings.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.lbl_AnimalID = QLabel(self.TaskSettings)
        self.lbl_AnimalID.setObjectName(u"lbl_AnimalID")
        self.lbl_AnimalID.setGeometry(QRect(20, 78, 61, 20))
        font2 = QFont()
        font2.setPointSize(8)
        self.lbl_AnimalID.setFont(font2)
        self.btn_Start = QPushButton(self.TaskSettings)
        self.btn_Start.setObjectName(u"btn_Start")
        self.btn_Start.setGeometry(QRect(349, 20, 61, 31))
        self.btn_Start.setStyleSheet(u"background-color: rgb(216, 244, 211);\n"
"font: 700 8pt \"Segoe UI\";")
        self.btn_Stop = QPushButton(self.TaskSettings)
        self.btn_Stop.setObjectName(u"btn_Stop")
        self.btn_Stop.setGeometry(QRect(420, 20, 61, 31))
        self.btn_Stop.setStyleSheet(u"font: 700 8pt \"Segoe UI\";\n"
"background-color: rgb(255, 203, 198);")
        self.ddm_Animal_ID = QComboBox(self.TaskSettings)
        self.ddm_Animal_ID.setObjectName(u"ddm_Animal_ID")
        self.ddm_Animal_ID.setGeometry(QRect(100, 78, 110, 21))
        font3 = QFont()
        font3.setPointSize(12)
        self.ddm_Animal_ID.setFont(font3)
        self.ddm_Animal_ID.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ddm_Animal_ID.setEditable(True)
        self.ddm_Task = QComboBox(self.TaskSettings)
        self.ddm_Task.setObjectName(u"ddm_Task")
        self.ddm_Task.setGeometry(QRect(60, 119, 261, 31))
        self.ddm_Task.setFont(font3)
        self.ddm_Task.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ddm_Task.setEditable(True)
        self.ddm_Task.setFrame(True)
        self.lbl_Task = QLabel(self.TaskSettings)
        self.lbl_Task.setObjectName(u"lbl_Task")
        self.lbl_Task.setGeometry(QRect(20, 125, 41, 19))
        self.lbl_Task.setFont(font2)
        self.lbl_TaskTimeline = QLabel(self.TaskSettings)
        self.lbl_TaskTimeline.setObjectName(u"lbl_TaskTimeline")
        self.lbl_TaskTimeline.setGeometry(QRect(20, 324, 131, 19))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setUnderline(True)
        self.lbl_TaskTimeline.setFont(font4)
        self.lbl_TaskTimeline.setStyleSheet(u"")
        self.lbl_RigParams = QLabel(self.TaskSettings)
        self.lbl_RigParams.setObjectName(u"lbl_RigParams")
        self.lbl_RigParams.setGeometry(QRect(20, 177, 131, 19))
        self.lbl_RigParams.setFont(font4)
        self.chk_BlueLED = QRadioButton(self.TaskSettings)
        self.chk_BlueLED.setObjectName(u"chk_BlueLED")
        self.chk_BlueLED.setGeometry(QRect(20, 209, 89, 20))
        font5 = QFont()
        font5.setPointSize(9)
        self.chk_BlueLED.setFont(font5)
        self.chk_WhiteLED_Left = QRadioButton(self.TaskSettings)
        self.chk_WhiteLED_Left.setObjectName(u"chk_WhiteLED_Left")
        self.chk_WhiteLED_Left.setGeometry(QRect(20, 239, 111, 20))
        self.chk_WhiteLED_Left.setFont(font5)
        self.chk_16Tone = QRadioButton(self.TaskSettings)
        self.chk_16Tone.setObjectName(u"chk_16Tone")
        self.chk_16Tone.setGeometry(QRect(179, 209, 101, 20))
        self.chk_16Tone.setFont(font5)
        self.chk_8Tone = QRadioButton(self.TaskSettings)
        self.chk_8Tone.setObjectName(u"chk_8Tone")
        self.chk_8Tone.setGeometry(QRect(179, 239, 89, 20))
        self.chk_8Tone.setFont(font5)
        self.chk_Reward_right = QRadioButton(self.TaskSettings)
        self.chk_Reward_right.setObjectName(u"chk_Reward_right")
        self.chk_Reward_right.setGeometry(QRect(331, 209, 151, 20))
        self.chk_Reward_right.setFont(font5)
        self.chk_Punishment = QRadioButton(self.TaskSettings)
        self.chk_Punishment.setObjectName(u"chk_Punishment")
        self.chk_Punishment.setGeometry(QRect(331, 239, 121, 20))
        self.chk_Punishment.setFont(font5)
        self.lbl_QuietWindow = QLabel(self.TaskSettings)
        self.lbl_QuietWindow.setObjectName(u"lbl_QuietWindow")
        self.lbl_QuietWindow.setGeometry(QRect(23, 360, 90, 20))
        self.lbl_QuietWindow.setFont(font5)
        self.txt_QuietWindow = QLineEdit(self.TaskSettings)
        self.txt_QuietWindow.setObjectName(u"txt_QuietWindow")
        self.txt_QuietWindow.setGeometry(QRect(110, 359, 51, 22))
        self.txt_QuietWindow.setFont(font5)
        self.lbl_QW_s = QLabel(self.TaskSettings)
        self.lbl_QW_s.setObjectName(u"lbl_QW_s")
        self.lbl_QW_s.setGeometry(QRect(173, 360, 41, 20))
        self.lbl_QW_s.setFont(font5)
        self.lbl_RW_s = QLabel(self.TaskSettings)
        self.lbl_RW_s.setObjectName(u"lbl_RW_s")
        self.lbl_RW_s.setGeometry(QRect(193, 398, 41, 20))
        self.lbl_RW_s.setFont(font5)
        self.txt_ResponseWindow = QLineEdit(self.TaskSettings)
        self.txt_ResponseWindow.setObjectName(u"txt_ResponseWindow")
        self.txt_ResponseWindow.setGeometry(QRect(130, 397, 51, 22))
        self.txt_ResponseWindow.setFont(font5)
        self.lbl_ResponseWindow = QLabel(self.TaskSettings)
        self.lbl_ResponseWindow.setObjectName(u"lbl_ResponseWindow")
        self.lbl_ResponseWindow.setGeometry(QRect(24, 398, 101, 20))
        self.lbl_ResponseWindow.setFont(font5)
        self.txt_ITImin = QLineEdit(self.TaskSettings)
        self.txt_ITImin.setObjectName(u"txt_ITImin")
        self.txt_ITImin.setGeometry(QRect(80, 436, 51, 22))
        self.txt_ITImin.setFont(font5)
        self.lbl_ITI = QLabel(self.TaskSettings)
        self.lbl_ITI.setObjectName(u"lbl_ITI")
        self.lbl_ITI.setGeometry(QRect(25, 438, 21, 20))
        self.lbl_ITI.setFont(font5)
        self.lbl_TD_s = QLabel(self.TaskSettings)
        self.lbl_TD_s.setObjectName(u"lbl_TD_s")
        self.lbl_TD_s.setGeometry(QRect(134, 437, 16, 20))
        self.lbl_TD_s.setFont(font5)
        self.lbl_RewardParams = QLabel(self.TaskSettings)
        self.lbl_RewardParams.setObjectName(u"lbl_RewardParams")
        self.lbl_RewardParams.setGeometry(QRect(20, 609, 131, 19))
        self.lbl_RewardParams.setFont(font4)
        self.lbl_RewardParams.setStyleSheet(u"")
        self.lbl_VO_ms = QLabel(self.TaskSettings)
        self.lbl_VO_ms.setObjectName(u"lbl_VO_ms")
        self.lbl_VO_ms.setGeometry(QRect(173, 643, 41, 20))
        self.lbl_VO_ms.setFont(font5)
        self.txt_ValveOpening = QLineEdit(self.TaskSettings)
        self.txt_ValveOpening.setObjectName(u"txt_ValveOpening")
        self.txt_ValveOpening.setGeometry(QRect(110, 642, 51, 22))
        self.txt_ValveOpening.setFont(font5)
        self.lbl_ValveOpening = QLabel(self.TaskSettings)
        self.lbl_ValveOpening.setObjectName(u"lbl_ValveOpening")
        self.lbl_ValveOpening.setGeometry(QRect(23, 643, 90, 20))
        self.lbl_ValveOpening.setFont(font5)
        self.lbl_OptoProtocols = QLabel(self.TaskSettings)
        self.lbl_OptoProtocols.setObjectName(u"lbl_OptoProtocols")
        self.lbl_OptoProtocols.setGeometry(QRect(20, 692, 131, 19))
        self.lbl_OptoProtocols.setFont(font4)
        self.chk_WhiteLED_Right = QRadioButton(self.TaskSettings)
        self.chk_WhiteLED_Right.setObjectName(u"chk_WhiteLED_Right")
        self.chk_WhiteLED_Right.setGeometry(QRect(20, 270, 121, 20))
        self.chk_WhiteLED_Right.setFont(font5)
        self.txt_Date = QLabel(self.TaskSettings)
        self.txt_Date.setObjectName(u"txt_Date")
        self.txt_Date.setGeometry(QRect(60, 20, 91, 16))
        self.txt_Date.setFont(font2)
        self.lbl_Date = QLabel(self.TaskSettings)
        self.lbl_Date.setObjectName(u"lbl_Date")
        self.lbl_Date.setGeometry(QRect(20, 18, 31, 20))
        self.lbl_Date.setFont(font2)
        self.btn_Update = QPushButton(self.TaskSettings)
        self.btn_Update.setObjectName(u"btn_Update")
        self.btn_Update.setGeometry(QRect(378, 120, 71, 31))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(True)
        self.btn_Update.setFont(font6)
        self.btn_Update.setStyleSheet(u"background-color: rgb(255, 225, 205);\n"
"border-color: rgb(227, 153, 100);")
        self.chk_Reward_left = QRadioButton(self.TaskSettings)
        self.chk_Reward_left.setObjectName(u"chk_Reward_left")
        self.chk_Reward_left.setGeometry(QRect(179, 269, 141, 20))
        self.chk_Reward_left.setFont(font5)
        self.lbl_AssociationTrials = QLabel(self.TaskSettings)
        self.lbl_AssociationTrials.setObjectName(u"lbl_AssociationTrials")
        self.lbl_AssociationTrials.setGeometry(QRect(21, 498, 131, 19))
        self.lbl_AssociationTrials.setFont(font4)
        self.lbl_AssociationTrials.setStyleSheet(u"")
        self.lbl_Box = QLabel(self.TaskSettings)
        self.lbl_Box.setObjectName(u"lbl_Box")
        self.lbl_Box.setGeometry(QRect(251, 76, 31, 20))
        self.lbl_Box.setFont(font2)
        self.ddm_Box = QComboBox(self.TaskSettings)
        self.ddm_Box.setObjectName(u"ddm_Box")
        self.ddm_Box.setGeometry(QRect(281, 76, 71, 21))
        self.ddm_Box.setFont(font3)
        self.ddm_Box.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.ddm_Box.setEditable(True)
        self.chk_NoPunishment = QCheckBox(self.TaskSettings)
        self.chk_NoPunishment.setObjectName(u"chk_NoPunishment")
        self.chk_NoPunishment.setGeometry(QRect(22, 524, 160, 30))
        self.chk_NoPunishment.setFont(font5)
        self.lbl_AssociationTrials_3 = QLabel(self.TaskSettings)
        self.lbl_AssociationTrials_3.setObjectName(u"lbl_AssociationTrials_3")
        self.lbl_AssociationTrials_3.setGeometry(QRect(270, 506, 40, 19))
        self.lbl_AssociationTrials_3.setFont(font4)
        self.lbl_AssociationTrials_3.setStyleSheet(u"color: rgb(32, 95, 95);")
        self.lbl_QuietWindow_5 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_5.setObjectName(u"lbl_QuietWindow_5")
        self.lbl_QuietWindow_5.setGeometry(QRect(248, 529, 101, 21))
        self.lbl_QuietWindow_5.setFont(font2)
        self.lbl_QuietWindow_5.setStyleSheet(u"color: rgb(32, 95, 95);")
        self.lbl_QuietWindow_7 = QLabel(self.TaskSettings)
        self.lbl_QuietWindow_7.setObjectName(u"lbl_QuietWindow_7")
        self.lbl_QuietWindow_7.setGeometry(QRect(248, 549, 101, 21))
        self.lbl_QuietWindow_7.setFont(font2)
        self.lbl_QuietWindow_7.setStyleSheet(u"color: rgb(32, 95, 95);")
        self.chk_IgnoreLicksWW = QCheckBox(self.TaskSettings)
        self.chk_IgnoreLicksWW.setObjectName(u"chk_IgnoreLicksWW")
        self.chk_IgnoreLicksWW.setGeometry(QRect(23, 551, 191, 30))
        self.chk_IgnoreLicksWW.setFont(font5)
        self.lbl_TrialDuration_2 = QLabel(self.TaskSettings)
        self.lbl_TrialDuration_2.setObjectName(u"lbl_TrialDuration_2")
        self.lbl_TrialDuration_2.setGeometry(QRect(54, 437, 21, 20))
        self.lbl_TrialDuration_2.setFont(font5)
        self.lbl_TrialDuration_2.setStyleSheet(u"color: rgb(107, 107, 107);")
        self.lbl_TrialDuration_3 = QLabel(self.TaskSettings)
        self.lbl_TrialDuration_3.setObjectName(u"lbl_TrialDuration_3")
        self.lbl_TrialDuration_3.setGeometry(QRect(154, 437, 16, 20))
        self.lbl_TrialDuration_3.setFont(font5)
        self.lbl_TD_s_2 = QLabel(self.TaskSettings)
        self.lbl_TD_s_2.setObjectName(u"lbl_TD_s_2")
        self.lbl_TD_s_2.setGeometry(QRect(224, 437, 16, 20))
        self.lbl_TD_s_2.setFont(font5)
        self.txt_ITImax = QLineEdit(self.TaskSettings)
        self.txt_ITImax.setObjectName(u"txt_ITImax")
        self.txt_ITImax.setGeometry(QRect(170, 436, 51, 22))
        self.txt_ITImax.setFont(font5)
        self.lbl_TrialDuration_4 = QLabel(self.TaskSettings)
        self.lbl_TrialDuration_4.setObjectName(u"lbl_TrialDuration_4")
        self.lbl_TrialDuration_4.setGeometry(QRect(242, 437, 31, 20))
        self.lbl_TrialDuration_4.setFont(font5)
        self.lbl_TrialDuration_4.setStyleSheet(u"color: rgb(107, 107, 107);")
        self.btn_FlushWater_left = QPushButton(self.TaskSettings)
        self.btn_FlushWater_left.setObjectName(u"btn_FlushWater_left")
        self.btn_FlushWater_left.setGeometry(QRect(402, 673, 61, 31))
        self.btn_FlushWater_left.setFont(font2)
        self.btn_FlushWater_left.setStyleSheet(u"background-color: rgb(221, 241, 255);")
        self.btn_FlushWater_right = QPushButton(self.TaskSettings)
        self.btn_FlushWater_right.setObjectName(u"btn_FlushWater_right")
        self.btn_FlushWater_right.setGeometry(QRect(402, 633, 61, 31))
        self.btn_FlushWater_right.setFont(font2)
        self.btn_FlushWater_right.setStyleSheet(u"background-color: rgb(221, 241, 255);")
        self.lbl_FlushWater = QLabel(self.TaskSettings)
        self.lbl_FlushWater.setObjectName(u"lbl_FlushWater")
        self.lbl_FlushWater.setGeometry(QRect(399, 608, 71, 19))
        self.lbl_FlushWater.setFont(font4)
        self.btn_Calibration = QPushButton(self.TaskSettings)
        self.btn_Calibration.setObjectName(u"btn_Calibration")
        self.btn_Calibration.setGeometry(QRect(377, 765, 110, 31))
        self.btn_Calibration.setFont(font2)
        self.btn_Calibration.setStyleSheet(u"background-color: rgb(221, 241, 255);")
        self.lbl_Blocks_2 = QLabel(self.TaskSettings)
        self.lbl_Blocks_2.setObjectName(u"lbl_Blocks_2")
        self.lbl_Blocks_2.setGeometry(QRect(356, 361, 41, 20))
        self.lbl_Blocks_2.setFont(font5)
        self.txt_Blocks = QLineEdit(self.TaskSettings)
        self.txt_Blocks.setObjectName(u"txt_Blocks")
        self.txt_Blocks.setGeometry(QRect(397, 360, 51, 22))
        self.txt_Blocks.setFont(font5)
        self.btn_Opto10 = QPushButton(self.TaskSettings)
        self.btn_Opto10.setObjectName(u"btn_Opto10")
        self.btn_Opto10.setGeometry(QRect(20, 725, 131, 24))
        self.btn_Opto10.setFont(font2)
        self.btn_Opto100 = QPushButton(self.TaskSettings)
        self.btn_Opto100.setObjectName(u"btn_Opto100")
        self.btn_Opto100.setGeometry(QRect(20, 755, 131, 24))
        self.btn_Opto100.setFont(font2)
        self.chk_Manip_sound_lights = QRadioButton(self.TaskSettings)
        self.chk_Manip_sound_lights.setObjectName(u"chk_Manip_sound_lights")
        self.chk_Manip_sound_lights.setGeometry(QRect(331, 270, 140, 20))
        self.chk_Manip_sound_lights.setFont(font5)
        self.lbl_TaskSettings = QLabel(self.Box)
        self.lbl_TaskSettings.setObjectName(u"lbl_TaskSettings")
        self.lbl_TaskSettings.setGeometry(QRect(20, 6, 111, 20))
        font7 = QFont()
        font7.setPointSize(10)
        font7.setBold(True)
        self.lbl_TaskSettings.setFont(font7)
        self.lbl_TaskSettings.setStyleSheet(u"color: rgb(217, 112, 7);")
        self.lbl_TaskSettings.setFrameShape(QFrame.NoFrame)
        self.lbl_TaskSettings.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_Visualization = QLabel(self.Box)
        self.lbl_Visualization.setObjectName(u"lbl_Visualization")
        self.lbl_Visualization.setGeometry(QRect(559, 6, 111, 20))
        self.lbl_Visualization.setFont(font7)
        self.lbl_Visualization.setStyleSheet(u"\n"
"color: rgb(73, 192, 203);")
        self.lbl_Visualization.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.line = QFrame(self.Box)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(520, 10, 20, 821))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_AnimalPerformance = QLabel(self.Box)
        self.lbl_AnimalPerformance.setObjectName(u"lbl_AnimalPerformance")
        self.lbl_AnimalPerformance.setGeometry(QRect(1131, 15, 131, 20))
        self.lbl_AnimalPerformance.setFont(font)
        self.lbl_AnimalPerformance.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_LickTrace_right = QLabel(self.Box)
        self.lbl_LickTrace_right.setObjectName(u"lbl_LickTrace_right")
        self.lbl_LickTrace_right.setGeometry(QRect(1130, 302, 141, 20))
        self.lbl_LickTrace_right.setFont(font)
        self.lbl_LickTrace_right.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_LickTrace_left = QLabel(self.Box)
        self.lbl_LickTrace_left.setObjectName(u"lbl_LickTrace_left")
        self.lbl_LickTrace_left.setGeometry(QRect(1130, 570, 131, 20))
        self.lbl_LickTrace_left.setFont(font)
        self.lbl_LickTrace_left.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.lbl_Time = QLabel(self.Box)
        self.lbl_Time.setObjectName(u"lbl_Time")
        self.lbl_Time.setGeometry(QRect(693, 35, 41, 20))
        self.lbl_Time.setFont(font7)
        self.bkg_Blocks = QWidget(self.Box)
        self.bkg_Blocks.setObjectName(u"bkg_Blocks")
        self.bkg_Blocks.setGeometry(QRect(574, 413, 471, 31))
        self.bkg_Blocks.setStyleSheet(u"background-color: rgb(214, 236, 238);")
        self.layoutWidget_2 = QWidget(self.bkg_Blocks)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(8, 4, 451, 20))
        self.Layout_B1_Blocks = QHBoxLayout(self.layoutWidget_2)
        self.Layout_B1_Blocks.setSpacing(16)
        self.Layout_B1_Blocks.setObjectName(u"Layout_B1_Blocks")
        self.Layout_B1_Blocks.setContentsMargins(0, 0, 0, 0)
        self.lbl_B1 = QLabel(self.layoutWidget_2)
        self.lbl_B1.setObjectName(u"lbl_B1")
        self.lbl_B1.setFont(font)
        self.lbl_B1.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B1)

        self.lbl_B2 = QLabel(self.layoutWidget_2)
        self.lbl_B2.setObjectName(u"lbl_B2")
        self.lbl_B2.setFont(font)
        self.lbl_B2.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B2)

        self.lbl_B3 = QLabel(self.layoutWidget_2)
        self.lbl_B3.setObjectName(u"lbl_B3")
        self.lbl_B3.setFont(font)
        self.lbl_B3.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B3)

        self.lbl_B4 = QLabel(self.layoutWidget_2)
        self.lbl_B4.setObjectName(u"lbl_B4")
        self.lbl_B4.setFont(font)
        self.lbl_B4.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B4)

        self.lbl_B5 = QLabel(self.layoutWidget_2)
        self.lbl_B5.setObjectName(u"lbl_B5")
        self.lbl_B5.setFont(font)
        self.lbl_B5.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B5)

        self.lbl_B6 = QLabel(self.layoutWidget_2)
        self.lbl_B6.setObjectName(u"lbl_B6")
        self.lbl_B6.setFont(font)
        self.lbl_B6.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B6)

        self.lbl_B7 = QLabel(self.layoutWidget_2)
        self.lbl_B7.setObjectName(u"lbl_B7")
        self.lbl_B7.setFont(font)
        self.lbl_B7.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B7)

        self.lbl_B8 = QLabel(self.layoutWidget_2)
        self.lbl_B8.setObjectName(u"lbl_B8")
        self.lbl_B8.setFont(font)
        self.lbl_B8.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B8)

        self.lbl_B9 = QLabel(self.layoutWidget_2)
        self.lbl_B9.setObjectName(u"lbl_B9")
        self.lbl_B9.setFont(font)
        self.lbl_B9.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B9)

        self.lbl_B10 = QLabel(self.layoutWidget_2)
        self.lbl_B10.setObjectName(u"lbl_B10")
        self.lbl_B10.setFont(font)
        self.lbl_B10.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B10)

        self.lbl_B11 = QLabel(self.layoutWidget_2)
        self.lbl_B11.setObjectName(u"lbl_B11")
        self.lbl_B11.setFont(font)
        self.lbl_B11.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B11)

        self.lbl_B12 = QLabel(self.layoutWidget_2)
        self.lbl_B12.setObjectName(u"lbl_B12")
        self.lbl_B12.setFont(font)
        self.lbl_B12.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B12)

        self.lbl_B13 = QLabel(self.layoutWidget_2)
        self.lbl_B13.setObjectName(u"lbl_B13")
        self.lbl_B13.setFont(font)
        self.lbl_B13.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B13)

        self.lbl_B14 = QLabel(self.layoutWidget_2)
        self.lbl_B14.setObjectName(u"lbl_B14")
        self.lbl_B14.setFont(font)
        self.lbl_B14.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B14)

        self.lbl_B15 = QLabel(self.layoutWidget_2)
        self.lbl_B15.setObjectName(u"lbl_B15")
        self.lbl_B15.setFont(font)
        self.lbl_B15.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.lbl_B15)

        self.bkg_RightSpout = QWidget(self.Box)
        self.bkg_RightSpout.setObjectName(u"bkg_RightSpout")
        self.bkg_RightSpout.setGeometry(QRect(574, 450, 471, 31))
        self.bkg_RightSpout.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.layoutWidget = QWidget(self.bkg_RightSpout)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 5, 448, 20))
        self.Layout_B1_RightSpout = QHBoxLayout(self.layoutWidget)
        self.Layout_B1_RightSpout.setSpacing(19)
        self.Layout_B1_RightSpout.setObjectName(u"Layout_B1_RightSpout")
        self.Layout_B1_RightSpout.setSizeConstraint(QLayout.SetNoConstraint)
        self.Layout_B1_RightSpout.setContentsMargins(0, 0, 0, 0)
        self.lbl_O1 = QLabel(self.layoutWidget)
        self.lbl_O1.setObjectName(u"lbl_O1")
        self.lbl_O1.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O1)

        self.lbl_O2 = QLabel(self.layoutWidget)
        self.lbl_O2.setObjectName(u"lbl_O2")
        self.lbl_O2.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O2)

        self.lbl_O3 = QLabel(self.layoutWidget)
        self.lbl_O3.setObjectName(u"lbl_O3")
        self.lbl_O3.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O3)

        self.lbl_O4 = QLabel(self.layoutWidget)
        self.lbl_O4.setObjectName(u"lbl_O4")
        self.lbl_O4.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O4)

        self.lbl_O5 = QLabel(self.layoutWidget)
        self.lbl_O5.setObjectName(u"lbl_O5")
        self.lbl_O5.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O5)

        self.lbl_O6 = QLabel(self.layoutWidget)
        self.lbl_O6.setObjectName(u"lbl_O6")
        self.lbl_O6.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O6)

        self.lbl_O7 = QLabel(self.layoutWidget)
        self.lbl_O7.setObjectName(u"lbl_O7")
        self.lbl_O7.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O7)

        self.lbl_O8 = QLabel(self.layoutWidget)
        self.lbl_O8.setObjectName(u"lbl_O8")
        self.lbl_O8.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O8)

        self.lbl_O9 = QLabel(self.layoutWidget)
        self.lbl_O9.setObjectName(u"lbl_O9")
        self.lbl_O9.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O9)

        self.lbl_O10 = QLabel(self.layoutWidget)
        self.lbl_O10.setObjectName(u"lbl_O10")
        self.lbl_O10.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O10)

        self.lbl_O11 = QLabel(self.layoutWidget)
        self.lbl_O11.setObjectName(u"lbl_O11")
        self.lbl_O11.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O11)

        self.lbl_O12 = QLabel(self.layoutWidget)
        self.lbl_O12.setObjectName(u"lbl_O12")
        self.lbl_O12.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O12)

        self.lbl_O13 = QLabel(self.layoutWidget)
        self.lbl_O13.setObjectName(u"lbl_O13")
        self.lbl_O13.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O13)

        self.lbl_O14 = QLabel(self.layoutWidget)
        self.lbl_O14.setObjectName(u"lbl_O14")
        self.lbl_O14.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O14)

        self.lbl_O15 = QLabel(self.layoutWidget)
        self.lbl_O15.setObjectName(u"lbl_O15")
        self.lbl_O15.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.lbl_O15)

        self.bkg_Trials = QWidget(self.Box)
        self.bkg_Trials.setObjectName(u"bkg_Trials")
        self.bkg_Trials.setGeometry(QRect(574, 485, 471, 31))
        self.bkg_Trials.setStyleSheet(u"background-color: rgb(235, 235, 235);")
        self.line_3 = QFrame(self.bkg_Trials)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 0, 16, 10))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font8 = QFont()
        font8.setPointSize(9)
        font8.setBold(True)
        self.line_3.setFont(font8)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.bkg_Trials)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(40, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFont(font8)
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.bkg_Trials)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(70, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFont(font8)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.bkg_Trials)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(101, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFont(font8)
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(self.bkg_Trials)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(133, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFont(font8)
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(self.bkg_Trials)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(164, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFont(font8)
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(self.bkg_Trials)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(195, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFont(font8)
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_10 = QFrame(self.bkg_Trials)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(227, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFont(font8)
        self.line_10.setFrameShape(QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_11 = QFrame(self.bkg_Trials)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(258, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_11.sizePolicy().hasHeightForWidth())
        self.line_11.setSizePolicy(sizePolicy)
        self.line_11.setFont(font8)
        self.line_11.setFrameShape(QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_12 = QFrame(self.bkg_Trials)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(288, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setFont(font8)
        self.line_12.setFrameShape(QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_13 = QFrame(self.bkg_Trials)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(319, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setFont(font8)
        self.line_13.setFrameShape(QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_15 = QFrame(self.bkg_Trials)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(348, 0, 20, 11))
        sizePolicy.setHeightForWidth(self.line_15.sizePolicy().hasHeightForWidth())
        self.line_15.setSizePolicy(sizePolicy)
        self.line_15.setFont(font8)
        self.line_15.setFrameShape(QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_14 = QFrame(self.bkg_Trials)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(381, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_14.sizePolicy().hasHeightForWidth())
        self.line_14.setSizePolicy(sizePolicy)
        self.line_14.setFont(font8)
        self.line_14.setFrameShape(QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_16 = QFrame(self.bkg_Trials)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(413, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_16.sizePolicy().hasHeightForWidth())
        self.line_16.setSizePolicy(sizePolicy)
        self.line_16.setFont(font8)
        self.line_16.setFrameShape(QFrame.Shape.VLine)
        self.line_16.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_17 = QFrame(self.bkg_Trials)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(444, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        self.line_17.setFont(font8)
        self.line_17.setFrameShape(QFrame.Shape.VLine)
        self.line_17.setFrameShadow(QFrame.Shadow.Sunken)
        self.lbl_T1 = QLabel(self.bkg_Trials)
        self.lbl_T1.setObjectName(u"lbl_T1")
        self.lbl_T1.setGeometry(QRect(8, 10, 20, 20))
        self.lbl_T1.setFont(font)
        self.lbl_T1.setAlignment(Qt.AlignCenter)
        self.lbl_T2 = QLabel(self.bkg_Trials)
        self.lbl_T2.setObjectName(u"lbl_T2")
        self.lbl_T2.setGeometry(QRect(38, 10, 20, 20))
        self.lbl_T2.setFont(font)
        self.lbl_T2.setAlignment(Qt.AlignCenter)
        self.lbl_T3 = QLabel(self.bkg_Trials)
        self.lbl_T3.setObjectName(u"lbl_T3")
        self.lbl_T3.setGeometry(QRect(68, 10, 20, 20))
        self.lbl_T3.setFont(font)
        self.lbl_T3.setAlignment(Qt.AlignCenter)
        self.lbl_T4 = QLabel(self.bkg_Trials)
        self.lbl_T4.setObjectName(u"lbl_T4")
        self.lbl_T4.setGeometry(QRect(99, 10, 20, 20))
        self.lbl_T4.setFont(font)
        self.lbl_T4.setAlignment(Qt.AlignCenter)
        self.lbl_T5 = QLabel(self.bkg_Trials)
        self.lbl_T5.setObjectName(u"lbl_T5")
        self.lbl_T5.setGeometry(QRect(131, 10, 20, 20))
        self.lbl_T5.setFont(font)
        self.lbl_T5.setAlignment(Qt.AlignCenter)
        self.lbl_T6 = QLabel(self.bkg_Trials)
        self.lbl_T6.setObjectName(u"lbl_T6")
        self.lbl_T6.setGeometry(QRect(162, 10, 20, 20))
        self.lbl_T6.setFont(font)
        self.lbl_T6.setAlignment(Qt.AlignCenter)
        self.lbl_T12 = QLabel(self.bkg_Trials)
        self.lbl_T12.setObjectName(u"lbl_T12")
        self.lbl_T12.setGeometry(QRect(348, 10, 20, 20))
        self.lbl_T12.setFont(font)
        self.lbl_T12.setAlignment(Qt.AlignCenter)
        self.lbl_TrialMonitor = QLabel(self.Box)
        self.lbl_TrialMonitor.setObjectName(u"lbl_TrialMonitor")
        self.lbl_TrialMonitor.setGeometry(QRect(734, 358, 131, 20))
        font9 = QFont()
        font9.setPointSize(11)
        self.lbl_TrialMonitor.setFont(font9)
        self.lbl_TrialMonitor.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_LegendTrialMonitor = QLabel(self.Box)
        self.lbl_LegendTrialMonitor.setObjectName(u"lbl_LegendTrialMonitor")
        self.lbl_LegendTrialMonitor.setGeometry(QRect(580, 386, 451, 20))
        font10 = QFont()
        font10.setPointSize(7)
        self.lbl_LegendTrialMonitor.setFont(font10)
        self.lbl_LegendTrialMonitor.setStyleSheet(u"\n"
"color: rgb(112, 112, 112);")
        self.lbl_LegendTrialMonitor.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_Blocks = QLabel(self.Box)
        self.lbl_Blocks.setObjectName(u"lbl_Blocks")
        self.lbl_Blocks.setGeometry(QRect(550, 419, 20, 20))
        self.lbl_Blocks.setFont(font7)
        self.lbl_Blocks.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_Outcome = QLabel(self.Box)
        self.lbl_Outcome.setObjectName(u"lbl_Outcome")
        self.lbl_Outcome.setGeometry(QRect(551, 459, 20, 20))
        self.lbl_Outcome.setFont(font7)
        self.lbl_Outcome.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_Trials = QLabel(self.Box)
        self.lbl_Trials.setObjectName(u"lbl_Trials")
        self.lbl_Trials.setGeometry(QRect(551, 494, 20, 20))
        self.lbl_Trials.setFont(font7)
        self.lbl_Trials.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.lbl_CorrectTrials = QLabel(self.Box)
        self.lbl_CorrectTrials.setObjectName(u"lbl_CorrectTrials")
        self.lbl_CorrectTrials.setGeometry(QRect(744, 674, 81, 16))
        self.lbl_CorrectTrials.setFont(font)
        self.lbl_IncorrectTrials = QLabel(self.Box)
        self.lbl_IncorrectTrials.setObjectName(u"lbl_IncorrectTrials")
        self.lbl_IncorrectTrials.setGeometry(QRect(737, 715, 91, 16))
        self.lbl_IncorrectTrials.setFont(font)
        self.box_Omissions = QLabel(self.Box)
        self.box_Omissions.setObjectName(u"box_Omissions")
        self.box_Omissions.setGeometry(QRect(648, 674, 41, 20))
        font11 = QFont()
        font11.setPointSize(10)
        font11.setBold(False)
        self.box_Omissions.setFont(font11)
        self.box_Omissions.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Omissions.setAlignment(Qt.AlignCenter)
        self.lbl_Omissions = QLabel(self.Box)
        self.lbl_Omissions.setObjectName(u"lbl_Omissions")
        self.lbl_Omissions.setGeometry(QRect(571, 672, 71, 20))
        self.lbl_Omissions.setFont(font)
        self.lbl_EarlyLicks = QLabel(self.Box)
        self.lbl_EarlyLicks.setObjectName(u"lbl_EarlyLicks")
        self.lbl_EarlyLicks.setGeometry(QRect(573, 712, 61, 20))
        self.lbl_EarlyLicks.setFont(font)
        self.box_EarlyLicks = QLabel(self.Box)
        self.box_EarlyLicks.setObjectName(u"box_EarlyLicks")
        self.box_EarlyLicks.setGeometry(QRect(648, 714, 41, 20))
        self.box_EarlyLicks.setFont(font11)
        self.box_EarlyLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_EarlyLicks.setAlignment(Qt.AlignCenter)
        self.box_IncorrectTrials = QLabel(self.Box)
        self.box_IncorrectTrials.setObjectName(u"box_IncorrectTrials")
        self.box_IncorrectTrials.setGeometry(QRect(837, 715, 41, 20))
        self.box_IncorrectTrials.setFont(font11)
        self.box_IncorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_IncorrectTrials.setAlignment(Qt.AlignCenter)
        self.box_CorrectTrials = QLabel(self.Box)
        self.box_CorrectTrials.setObjectName(u"box_CorrectTrials")
        self.box_CorrectTrials.setGeometry(QRect(836, 673, 41, 20))
        self.box_CorrectTrials.setFont(font11)
        self.box_CorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_CorrectTrials.setAlignment(Qt.AlignCenter)
        self.box_SoundBlocks = QLabel(self.Box)
        self.box_SoundBlocks.setObjectName(u"box_SoundBlocks")
        self.box_SoundBlocks.setGeometry(QRect(837, 755, 41, 20))
        self.box_SoundBlocks.setFont(font11)
        self.box_SoundBlocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_SoundBlocks.setAlignment(Qt.AlignCenter)
        self.lbl_SoundBlocks = QLabel(self.Box)
        self.lbl_SoundBlocks.setObjectName(u"lbl_SoundBlocks")
        self.lbl_SoundBlocks.setGeometry(QRect(745, 755, 81, 16))
        self.lbl_SoundBlocks.setFont(font)
        self.box_Action_L_blocks = QLabel(self.Box)
        self.box_Action_L_blocks.setObjectName(u"box_Action_L_blocks")
        self.box_Action_L_blocks.setGeometry(QRect(1015, 675, 41, 20))
        self.box_Action_L_blocks.setFont(font11)
        self.box_Action_L_blocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Action_L_blocks.setAlignment(Qt.AlignCenter)
        self.lbl_ActionLBlocks = QLabel(self.Box)
        self.lbl_ActionLBlocks.setObjectName(u"lbl_ActionLBlocks")
        self.lbl_ActionLBlocks.setGeometry(QRect(917, 675, 91, 16))
        self.lbl_ActionLBlocks.setFont(font)
        self.box_Action_R_blocks = QLabel(self.Box)
        self.box_Action_R_blocks.setObjectName(u"box_Action_R_blocks")
        self.box_Action_R_blocks.setGeometry(QRect(1015, 715, 41, 20))
        self.box_Action_R_blocks.setFont(font11)
        self.box_Action_R_blocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Action_R_blocks.setAlignment(Qt.AlignCenter)
        self.lbl_ActionRBlocks = QLabel(self.Box)
        self.lbl_ActionRBlocks.setObjectName(u"lbl_ActionRBlocks")
        self.lbl_ActionRBlocks.setGeometry(QRect(917, 715, 91, 16))
        self.lbl_ActionRBlocks.setFont(font)
        self.txt_Chronometer = QLabel(self.Box)
        self.txt_Chronometer.setObjectName(u"txt_Chronometer")
        self.txt_Chronometer.setGeometry(QRect(737, 34, 160, 21))
        self.txt_Chronometer.setFont(font1)
        self.txt_Chronometer.setAlignment(Qt.AlignCenter)
        self.lbl_CatchTrials = QLabel(self.Box)
        self.lbl_CatchTrials.setObjectName(u"lbl_CatchTrials")
        self.lbl_CatchTrials.setGeometry(QRect(940, 755, 71, 20))
        self.lbl_CatchTrials.setFont(font)
        self.box_CatchTrials = QLabel(self.Box)
        self.box_CatchTrials.setObjectName(u"box_CatchTrials")
        self.box_CatchTrials.setGeometry(QRect(1016, 755, 41, 20))
        self.box_CatchTrials.setFont(font11)
        self.box_CatchTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_CatchTrials.setAlignment(Qt.AlignCenter)
        self.plt_Camera = QLabel(self.Box)
        self.plt_Camera.setObjectName(u"plt_Camera")
        self.plt_Camera.setGeometry(QRect(560, 80, 411, 251))
        self.plt_Camera.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.plt_AnimalPerformance = QLabel(self.Box)
        self.plt_AnimalPerformance.setObjectName(u"plt_AnimalPerformance")
        self.plt_AnimalPerformance.setGeometry(QRect(1120, 40, 431, 231))
        self.plt_AnimalPerformance.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.plt_LickTrace_Right = QWidget(self.Box)
        self.plt_LickTrace_Right.setObjectName(u"plt_LickTrace_Right")
        self.plt_LickTrace_Right.setGeometry(QRect(1120, 328, 431, 211))
        self.plt_LickTrace_Right.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.plt_LickTrace_Left = QWidget(self.Box)
        self.plt_LickTrace_Left.setObjectName(u"plt_LickTrace_Left")
        self.plt_LickTrace_Left.setGeometry(QRect(1120, 597, 431, 211))
        self.plt_LickTrace_Left.setStyleSheet(u"background-color: rgb(233, 237, 254);")
        self.lbl_LicksRight = QLabel(self.Box)
        self.lbl_LicksRight.setObjectName(u"lbl_LicksRight")
        self.lbl_LicksRight.setGeometry(QRect(761, 793, 71, 21))
        self.lbl_LicksRight.setFont(font)
        self.box_LicksRight = QLabel(self.Box)
        self.box_LicksRight.setObjectName(u"box_LicksRight")
        self.box_LicksRight.setGeometry(QRect(838, 794, 40, 20))
        self.box_LicksRight.setFont(font11)
        self.box_LicksRight.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_LicksRight.setAlignment(Qt.AlignCenter)
        self.box_TotalLicks = QLabel(self.Box)
        self.box_TotalLicks.setObjectName(u"box_TotalLicks")
        self.box_TotalLicks.setGeometry(QRect(650, 752, 40, 20))
        self.box_TotalLicks.setFont(font11)
        self.box_TotalLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_TotalLicks.setAlignment(Qt.AlignCenter)
        self.lbl_TotalLicks = QLabel(self.Box)
        self.lbl_TotalLicks.setObjectName(u"lbl_TotalLicks")
        self.lbl_TotalLicks.setGeometry(QRect(570, 752, 70, 20))
        self.lbl_TotalLicks.setFont(font)
        self.lbl_LicksLeft = QLabel(self.Box)
        self.lbl_LicksLeft.setObjectName(u"lbl_LicksLeft")
        self.lbl_LicksLeft.setGeometry(QRect(577, 796, 61, 16))
        self.lbl_LicksLeft.setFont(font)
        self.box_LicksLeft = QLabel(self.Box)
        self.box_LicksLeft.setObjectName(u"box_LicksLeft")
        self.box_LicksLeft.setGeometry(QRect(650, 795, 40, 20))
        self.box_LicksLeft.setFont(font11)
        self.box_LicksLeft.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_LicksLeft.setAlignment(Qt.AlignCenter)
        self.lbl_TR_s = QLabel(self.Box)
        self.lbl_TR_s.setObjectName(u"lbl_TR_s")
        self.lbl_TR_s.setGeometry(QRect(1538, 303, 21, 20))
        self.lbl_TR_s.setFont(font5)
        self.lbl_ThresholdRight = QLabel(self.Box)
        self.lbl_ThresholdRight.setObjectName(u"lbl_ThresholdRight")
        self.lbl_ThresholdRight.setGeometry(QRect(1379, 303, 101, 20))
        self.lbl_ThresholdRight.setFont(font)
        self.lbl_ThresholdRight.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.txt_ThresholdRight = QLineEdit(self.Box)
        self.txt_ThresholdRight.setObjectName(u"txt_ThresholdRight")
        self.txt_ThresholdRight.setGeometry(QRect(1480, 302, 51, 22))
        self.txt_ThresholdRight.setFont(font5)
        self.lbl_TL_s = QLabel(self.Box)
        self.lbl_TL_s.setObjectName(u"lbl_TL_s")
        self.lbl_TL_s.setGeometry(QRect(1538, 573, 21, 20))
        self.lbl_TL_s.setFont(font5)
        self.txt_ThresholdLeft = QLineEdit(self.Box)
        self.txt_ThresholdLeft.setObjectName(u"txt_ThresholdLeft")
        self.txt_ThresholdLeft.setGeometry(QRect(1480, 572, 51, 22))
        self.txt_ThresholdLeft.setFont(font5)
        self.lbl_ThresholdLeft = QLabel(self.Box)
        self.lbl_ThresholdLeft.setObjectName(u"lbl_ThresholdLeft")
        self.lbl_ThresholdLeft.setGeometry(QRect(1387, 573, 91, 20))
        self.lbl_ThresholdLeft.setFont(font)
        self.lbl_ThresholdLeft.setStyleSheet(u"color: rgb(0, 85, 127);")
        self.lbl_TrialDuration = QLabel(self.Box)
        self.lbl_TrialDuration.setObjectName(u"lbl_TrialDuration")
        self.lbl_TrialDuration.setGeometry(QRect(820, 560, 81, 16))
        font12 = QFont()
        font12.setPointSize(10)
        font12.setBold(False)
        font12.setUnderline(True)
        self.lbl_TrialDuration.setFont(font12)
        self.box_TrialDuration = QLabel(self.Box)
        self.box_TrialDuration.setObjectName(u"box_TrialDuration")
        self.box_TrialDuration.setGeometry(QRect(907, 560, 50, 20))
        self.box_TrialDuration.setFont(font11)
        self.box_TrialDuration.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_TrialDuration.setAlignment(Qt.AlignCenter)
        self.lbl_VO_ms_2 = QLabel(self.Box)
        self.lbl_VO_ms_2.setObjectName(u"lbl_VO_ms_2")
        self.lbl_VO_ms_2.setGeometry(QRect(960, 560, 16, 20))
        self.lbl_VO_ms_2.setFont(font5)
        self.box_8KHzTrials = QLabel(self.Box)
        self.box_8KHzTrials.setObjectName(u"box_8KHzTrials")
        self.box_8KHzTrials.setGeometry(QRect(835, 633, 41, 20))
        self.box_8KHzTrials.setFont(font11)
        self.box_8KHzTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_8KHzTrials.setAlignment(Qt.AlignCenter)
        self.lbl_16KHzTrials = QLabel(self.Box)
        self.lbl_16KHzTrials.setObjectName(u"lbl_16KHzTrials")
        self.lbl_16KHzTrials.setGeometry(QRect(931, 635, 81, 16))
        self.lbl_16KHzTrials.setFont(font)
        self.box_16KHzTrials = QLabel(self.Box)
        self.box_16KHzTrials.setObjectName(u"box_16KHzTrials")
        self.box_16KHzTrials.setGeometry(QRect(1014, 635, 41, 20))
        self.box_16KHzTrials.setFont(font11)
        self.box_16KHzTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_16KHzTrials.setAlignment(Qt.AlignCenter)
        self.lbl_8KHzTrials = QLabel(self.Box)
        self.lbl_8KHzTrials.setObjectName(u"lbl_8KHzTrials")
        self.lbl_8KHzTrials.setGeometry(QRect(755, 634, 71, 16))
        self.lbl_8KHzTrials.setFont(font)
        self.lbl_TotalTrials = QLabel(self.Box)
        self.lbl_TotalTrials.setObjectName(u"lbl_TotalTrials")
        self.lbl_TotalTrials.setGeometry(QRect(570, 633, 71, 16))
        self.lbl_TotalTrials.setFont(font)
        self.box_TotalTrials = QLabel(self.Box)
        self.box_TotalTrials.setObjectName(u"box_TotalTrials")
        self.box_TotalTrials.setGeometry(QRect(647, 633, 41, 20))
        self.box_TotalTrials.setFont(font11)
        self.box_TotalTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_TotalTrials.setAlignment(Qt.AlignCenter)
        self.box_CurrentTrial = QLabel(self.Box)
        self.box_CurrentTrial.setObjectName(u"box_CurrentTrial")
        self.box_CurrentTrial.setGeometry(QRect(744, 595, 311, 21))
        self.box_CurrentTrial.setFont(font11)
        self.box_CurrentTrial.setStyleSheet(u"background-color: rgb(214, 236, 238);")
        self.box_CurrentTrial.setAlignment(Qt.AlignCenter)
        self.lbl_TotalTrials_2 = QLabel(self.Box)
        self.lbl_TotalTrials_2.setObjectName(u"lbl_TotalTrials_2")
        self.lbl_TotalTrials_2.setGeometry(QRect(610, 597, 31, 16))
        self.lbl_TotalTrials_2.setFont(font)
        self.box_Bias = QLabel(self.Box)
        self.box_Bias.setObjectName(u"box_Bias")
        self.box_Bias.setGeometry(QRect(647, 595, 41, 20))
        self.box_Bias.setFont(font11)
        self.box_Bias.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.box_Bias.setAlignment(Qt.AlignCenter)
        self.label = QLabel(self.Box)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(630, 577, 41, 16))
        self.label.setFont(font10)
        self.label.setStyleSheet(u"color: rgb(170, 103, 138);")
        self.label_2 = QLabel(self.Box)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(670, 577, 51, 16))
        self.label_2.setFont(font10)
        self.label_2.setStyleSheet(u"color: rgb(10, 134, 136);")
        self.lbl_T7 = QLabel(self.Box)
        self.lbl_T7.setObjectName(u"lbl_T7")
        self.lbl_T7.setGeometry(QRect(767, 495, 20, 20))
        self.lbl_T7.setFont(font)
        self.lbl_T7.setAlignment(Qt.AlignCenter)
        self.lbl_T8 = QLabel(self.Box)
        self.lbl_T8.setObjectName(u"lbl_T8")
        self.lbl_T8.setGeometry(QRect(799, 495, 20, 20))
        self.lbl_T8.setFont(font)
        self.lbl_T8.setAlignment(Qt.AlignCenter)
        self.lbl_T9 = QLabel(self.Box)
        self.lbl_T9.setObjectName(u"lbl_T9")
        self.lbl_T9.setGeometry(QRect(830, 495, 20, 20))
        self.lbl_T9.setFont(font)
        self.lbl_T9.setAlignment(Qt.AlignCenter)
        self.lbl_T10 = QLabel(self.Box)
        self.lbl_T10.setObjectName(u"lbl_T10")
        self.lbl_T10.setGeometry(QRect(860, 495, 20, 20))
        self.lbl_T10.setFont(font)
        self.lbl_T10.setAlignment(Qt.AlignCenter)
        self.lbl_T11 = QLabel(self.Box)
        self.lbl_T11.setObjectName(u"lbl_T11")
        self.lbl_T11.setGeometry(QRect(891, 495, 20, 20))
        self.lbl_T11.setFont(font)
        self.lbl_T11.setAlignment(Qt.AlignCenter)
        self.lbl_T13 = QLabel(self.Box)
        self.lbl_T13.setObjectName(u"lbl_T13")
        self.lbl_T13.setGeometry(QRect(953, 495, 20, 20))
        self.lbl_T13.setFont(font)
        self.lbl_T13.setAlignment(Qt.AlignCenter)
        self.lbl_T14 = QLabel(self.Box)
        self.lbl_T14.setObjectName(u"lbl_T14")
        self.lbl_T14.setGeometry(QRect(985, 495, 20, 20))
        self.lbl_T14.setFont(font)
        self.lbl_T14.setAlignment(Qt.AlignCenter)
        self.lbl_T15 = QLabel(self.Box)
        self.lbl_T15.setObjectName(u"lbl_T15")
        self.lbl_T15.setGeometry(QRect(1016, 495, 20, 20))
        self.lbl_T15.setFont(font)
        self.lbl_T15.setAlignment(Qt.AlignCenter)
        self.bar_Exposure = QScrollBar(self.Box)
        self.bar_Exposure.setObjectName(u"bar_Exposure")
        self.bar_Exposure.setGeometry(QRect(990, 140, 71, 16))
        self.bar_Exposure.setMinimum(100)
        self.bar_Exposure.setMaximum(1000)
        self.bar_Exposure.setSliderPosition(500)
        self.bar_Exposure.setOrientation(Qt.Horizontal)
        self.bar_Brightness = QScrollBar(self.Box)
        self.bar_Brightness.setObjectName(u"bar_Brightness")
        self.bar_Brightness.setGeometry(QRect(990, 190, 71, 16))
        self.bar_Brightness.setMaximum(255)
        self.bar_Brightness.setSingleStep(5)
        self.bar_Brightness.setSliderPosition(128)
        self.bar_Brightness.setOrientation(Qt.Horizontal)
        self.bar_Contrast = QScrollBar(self.Box)
        self.bar_Contrast.setObjectName(u"bar_Contrast")
        self.bar_Contrast.setGeometry(QRect(990, 236, 71, 16))
        self.bar_Contrast.setMaximum(255)
        self.bar_Contrast.setSingleStep(5)
        self.bar_Contrast.setSliderPosition(128)
        self.bar_Contrast.setOrientation(Qt.Horizontal)
        self.lbl_CamSettings = QLabel(self.Box)
        self.lbl_CamSettings.setObjectName(u"lbl_CamSettings")
        self.lbl_CamSettings.setGeometry(QRect(986, 95, 81, 16))
        self.lbl_CamSettings.setFont(font12)
        self.lbl_Exposure = QLabel(self.Box)
        self.lbl_Exposure.setObjectName(u"lbl_Exposure")
        self.lbl_Exposure.setGeometry(QRect(1000, 120, 51, 16))
        self.lbl_Exposure.setFont(font2)
        self.lbl_Exposure.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.lbl_Brightness = QLabel(self.Box)
        self.lbl_Brightness.setObjectName(u"lbl_Brightness")
        self.lbl_Brightness.setGeometry(QRect(1000, 164, 61, 16))
        self.lbl_Brightness.setFont(font2)
        self.lbl_Brightness.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.lbl_Contrast = QLabel(self.Box)
        self.lbl_Contrast.setObjectName(u"lbl_Contrast")
        self.lbl_Contrast.setGeometry(QRect(1000, 210, 61, 16))
        self.lbl_Contrast.setFont(font2)
        self.lbl_Contrast.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.btn_cam_reset = QPushButton(self.Box)
        self.btn_cam_reset.setObjectName(u"btn_cam_reset")
        self.btn_cam_reset.setGeometry(QRect(997, 271, 61, 21))
        self.btn_cam_reset.setFont(font2)
        self.btn_cam_reset.setStyleSheet(u"background-color: rgb(221, 241, 255);")
        self.lbl_ArduinoStatus = QLabel(self.Box)
        self.lbl_ArduinoStatus.setObjectName(u"lbl_ArduinoStatus")
        self.lbl_ArduinoStatus.setGeometry(QRect(221, 5, 91, 16))
        self.lbl_ArduinoStatus.setFont(font5)
        self.lbl_ArduinoStatus.setStyleSheet(u"")
        self.lbl_Date_2 = QLabel(self.Box)
        self.lbl_Date_2.setObjectName(u"lbl_Date_2")
        self.lbl_Date_2.setGeometry(QRect(175, 4, 41, 16))
        self.lbl_Date_2.setFont(font2)
        self.lbl_Date_3 = QLabel(self.Box)
        self.lbl_Date_3.setObjectName(u"lbl_Date_3")
        self.lbl_Date_3.setGeometry(QRect(327, 4, 41, 16))
        self.lbl_Date_3.setFont(font2)
        self.lbl_CameraStatus = QLabel(self.Box)
        self.lbl_CameraStatus.setObjectName(u"lbl_CameraStatus")
        self.lbl_CameraStatus.setGeometry(QRect(371, 5, 91, 16))
        self.lbl_CameraStatus.setFont(font5)
        self.lbl_CameraStatus.setStyleSheet(u"")
        self.btn_CheckHardware = QPushButton(self.Box)
        self.btn_CheckHardware.setObjectName(u"btn_CheckHardware")
        self.btn_CheckHardware.setGeometry(QRect(481, 4, 41, 21))
        self.btn_CheckHardware.setFont(font2)
        self.btn_CheckHardware.setStyleSheet(u"background-color: rgb(221, 241, 255);")
        self.Boxes.addTab(self.Box, "")
        self.bkg_Trials.raise_()
        self.TaskSettings.raise_()
        self.lbl_TaskSettings.raise_()
        self.lbl_Visualization.raise_()
        self.line.raise_()
        self.lbl_AnimalPerformance.raise_()
        self.lbl_LickTrace_right.raise_()
        self.lbl_LickTrace_left.raise_()
        self.lbl_Time.raise_()
        self.bkg_Blocks.raise_()
        self.bkg_RightSpout.raise_()
        self.lbl_TrialMonitor.raise_()
        self.lbl_LegendTrialMonitor.raise_()
        self.lbl_Blocks.raise_()
        self.lbl_Outcome.raise_()
        self.lbl_Trials.raise_()
        self.lbl_CorrectTrials.raise_()
        self.lbl_IncorrectTrials.raise_()
        self.box_Omissions.raise_()
        self.lbl_Omissions.raise_()
        self.lbl_EarlyLicks.raise_()
        self.box_EarlyLicks.raise_()
        self.box_IncorrectTrials.raise_()
        self.box_CorrectTrials.raise_()
        self.box_SoundBlocks.raise_()
        self.lbl_SoundBlocks.raise_()
        self.box_Action_L_blocks.raise_()
        self.lbl_ActionLBlocks.raise_()
        self.box_Action_R_blocks.raise_()
        self.lbl_ActionRBlocks.raise_()
        self.txt_Chronometer.raise_()
        self.lbl_CatchTrials.raise_()
        self.box_CatchTrials.raise_()
        self.plt_Camera.raise_()
        self.plt_AnimalPerformance.raise_()
        self.plt_LickTrace_Right.raise_()
        self.plt_LickTrace_Left.raise_()
        self.lbl_LicksRight.raise_()
        self.box_LicksRight.raise_()
        self.box_TotalLicks.raise_()
        self.lbl_TotalLicks.raise_()
        self.lbl_LicksLeft.raise_()
        self.box_LicksLeft.raise_()
        self.lbl_TR_s.raise_()
        self.lbl_ThresholdRight.raise_()
        self.txt_ThresholdRight.raise_()
        self.lbl_TL_s.raise_()
        self.txt_ThresholdLeft.raise_()
        self.lbl_ThresholdLeft.raise_()
        self.lbl_TrialDuration.raise_()
        self.box_TrialDuration.raise_()
        self.lbl_VO_ms_2.raise_()
        self.box_8KHzTrials.raise_()
        self.lbl_16KHzTrials.raise_()
        self.box_16KHzTrials.raise_()
        self.lbl_8KHzTrials.raise_()
        self.lbl_TotalTrials.raise_()
        self.box_TotalTrials.raise_()
        self.box_CurrentTrial.raise_()
        self.lbl_TotalTrials_2.raise_()
        self.box_Bias.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.lbl_T7.raise_()
        self.lbl_T8.raise_()
        self.lbl_T9.raise_()
        self.lbl_T10.raise_()
        self.lbl_T11.raise_()
        self.lbl_T13.raise_()
        self.lbl_T14.raise_()
        self.lbl_T15.raise_()
        self.bar_Exposure.raise_()
        self.bar_Brightness.raise_()
        self.bar_Contrast.raise_()
        self.lbl_CamSettings.raise_()
        self.lbl_Exposure.raise_()
        self.lbl_Brightness.raise_()
        self.lbl_Contrast.raise_()
        self.btn_cam_reset.raise_()
        self.lbl_ArduinoStatus.raise_()
        self.lbl_Date_2.raise_()
        self.lbl_Date_3.raise_()
        self.lbl_CameraStatus.raise_()
        self.btn_CheckHardware.raise_()
        self.Overview = QWidget()
        self.Overview.setObjectName(u"Overview")
        self.OV_Box = QGroupBox(self.Overview)
        self.OV_Box.setObjectName(u"OV_Box")
        self.OV_Box.setGeometry(QRect(10, 20, 331, 811))
        self.OV_Box.setFont(font7)
        self.OV_Box.setStyleSheet(u"border-color: rgb(81, 81, 81);\n"
"")
        self.OV_box_Chronometer = QLabel(self.OV_Box)
        self.OV_box_Chronometer.setObjectName(u"OV_box_Chronometer")
        self.OV_box_Chronometer.setGeometry(QRect(93, 69, 160, 21))
        self.OV_box_Chronometer.setFont(font1)
        self.OV_box_Chronometer.setAlignment(Qt.AlignCenter)
        self.OV_lbl_Time = QLabel(self.OV_Box)
        self.OV_lbl_Time.setObjectName(u"OV_lbl_Time")
        self.OV_lbl_Time.setGeometry(QRect(49, 70, 41, 20))
        self.OV_lbl_Time.setFont(font7)
        self.OV_lbl_Omissions = QLabel(self.OV_Box)
        self.OV_lbl_Omissions.setObjectName(u"OV_lbl_Omissions")
        self.OV_lbl_Omissions.setGeometry(QRect(105, 764, 71, 20))
        self.OV_lbl_Omissions.setFont(font)
        self.OV_box_CorrectTrials = QLabel(self.OV_Box)
        self.OV_box_CorrectTrials.setObjectName(u"OV_box_CorrectTrials")
        self.OV_box_CorrectTrials.setGeometry(QRect(185, 701, 41, 20))
        self.OV_box_CorrectTrials.setFont(font11)
        self.OV_box_CorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_CorrectTrials.setAlignment(Qt.AlignCenter)
        self.OV_box_IncorrectTrials = QLabel(self.OV_Box)
        self.OV_box_IncorrectTrials.setObjectName(u"OV_box_IncorrectTrials")
        self.OV_box_IncorrectTrials.setGeometry(QRect(185, 734, 41, 20))
        self.OV_box_IncorrectTrials.setFont(font11)
        self.OV_box_IncorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_IncorrectTrials.setAlignment(Qt.AlignCenter)
        self.OV_box_TotalTrials = QLabel(self.OV_Box)
        self.OV_box_TotalTrials.setObjectName(u"OV_box_TotalTrials")
        self.OV_box_TotalTrials.setGeometry(QRect(185, 640, 41, 20))
        self.OV_box_TotalTrials.setFont(font11)
        self.OV_box_TotalTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_TotalTrials.setAlignment(Qt.AlignCenter)
        self.OV_lbl_TotalTrials = QLabel(self.OV_Box)
        self.OV_lbl_TotalTrials.setObjectName(u"OV_lbl_TotalTrials")
        self.OV_lbl_TotalTrials.setGeometry(QRect(102, 639, 71, 16))
        self.OV_lbl_TotalTrials.setFont(font)
        self.OV_box_Omissions = QLabel(self.OV_Box)
        self.OV_box_Omissions.setObjectName(u"OV_box_Omissions")
        self.OV_box_Omissions.setGeometry(QRect(185, 767, 41, 20))
        self.OV_box_Omissions.setFont(font11)
        self.OV_box_Omissions.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_Omissions.setAlignment(Qt.AlignCenter)
        self.OV_lbl_IncorrectTrials = QLabel(self.OV_Box)
        self.OV_lbl_IncorrectTrials.setObjectName(u"OV_lbl_IncorrectTrials")
        self.OV_lbl_IncorrectTrials.setGeometry(QRect(78, 734, 91, 16))
        self.OV_lbl_IncorrectTrials.setFont(font)
        self.OV_lbl_CorrectTrials = QLabel(self.OV_Box)
        self.OV_lbl_CorrectTrials.setObjectName(u"OV_lbl_CorrectTrials")
        self.OV_lbl_CorrectTrials.setGeometry(QRect(86, 702, 81, 16))
        self.OV_lbl_CorrectTrials.setFont(font)
        self.OV_lbl_CurrentTrial = QLabel(self.OV_Box)
        self.OV_lbl_CurrentTrial.setObjectName(u"OV_lbl_CurrentTrial")
        self.OV_lbl_CurrentTrial.setGeometry(QRect(18, 600, 80, 16))
        self.OV_lbl_CurrentTrial.setFont(font)
        self.OV_lbl_CurrentTrial.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.OV_box_CurrentTrial = QLabel(self.OV_Box)
        self.OV_box_CurrentTrial.setObjectName(u"OV_box_CurrentTrial")
        self.OV_box_CurrentTrial.setGeometry(QRect(101, 600, 200, 20))
        self.OV_box_CurrentTrial.setFont(font)
        self.OV_box_CurrentTrial.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_CurrentTrial.setAlignment(Qt.AlignCenter)
        self.OV_plt_Camera = QLabel(self.OV_Box)
        self.OV_plt_Camera.setObjectName(u"OV_plt_Camera")
        self.OV_plt_Camera.setGeometry(QRect(15, 112, 301, 221))
        self.OV_plt_Camera.setStyleSheet(u"background-color: rgb(122, 122, 122);")
        self.OV_plt_AnimalPerformance = QLabel(self.OV_Box)
        self.OV_plt_AnimalPerformance.setObjectName(u"OV_plt_AnimalPerformance")
        self.OV_plt_AnimalPerformance.setGeometry(QRect(14, 347, 301, 221))
        self.OV_plt_AnimalPerformance.setStyleSheet(u"background-color: rgb(221, 255, 244);")
        self.OV_lbl_TotalLicks = QLabel(self.OV_Box)
        self.OV_lbl_TotalLicks.setObjectName(u"OV_lbl_TotalLicks")
        self.OV_lbl_TotalLicks.setGeometry(QRect(105, 671, 71, 16))
        self.OV_lbl_TotalLicks.setFont(font)
        self.OV_box_TotalLicks = QLabel(self.OV_Box)
        self.OV_box_TotalLicks.setObjectName(u"OV_box_TotalLicks")
        self.OV_box_TotalLicks.setGeometry(QRect(185, 670, 41, 20))
        self.OV_box_TotalLicks.setFont(font11)
        self.OV_box_TotalLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.OV_box_TotalLicks.setAlignment(Qt.AlignCenter)
        self.OV_bkg_Task = QWidget(self.OV_Box)
        self.OV_bkg_Task.setObjectName(u"OV_bkg_Task")
        self.OV_bkg_Task.setGeometry(QRect(27, 30, 271, 21))
        self.OV_bkg_Task.setStyleSheet(u"background-color: rgb(255, 222, 206);")
        self.OV_lbl_Task = QLabel(self.OV_bkg_Task)
        self.OV_lbl_Task.setObjectName(u"OV_lbl_Task")
        self.OV_lbl_Task.setGeometry(QRect(6, 2, 31, 16))
        self.OV_lbl_Task.setFont(font8)
        self.OV_txt_Task = QLabel(self.OV_bkg_Task)
        self.OV_txt_Task.setObjectName(u"OV_txt_Task")
        self.OV_txt_Task.setGeometry(QRect(50, 0, 211, 20))
        self.OV_txt_Task.setFont(font2)
        self.OV_txt_Task.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.OV_bkg_AnimalID = QWidget(self.Overview)
        self.OV_bkg_AnimalID.setObjectName(u"OV_bkg_AnimalID")
        self.OV_bkg_AnimalID.setGeometry(QRect(20, 10, 170, 21))
        self.OV_bkg_AnimalID.setStyleSheet(u"background-color: rgb(220, 231, 255);")
        self.OV_lbl_AnimalID = QLabel(self.OV_bkg_AnimalID)
        self.OV_lbl_AnimalID.setObjectName(u"OV_lbl_AnimalID")
        self.OV_lbl_AnimalID.setGeometry(QRect(14, -1, 81, 21))
        self.OV_lbl_AnimalID.setFont(font8)
        self.OV_txt_AnimalID = QLabel(self.OV_bkg_AnimalID)
        self.OV_txt_AnimalID.setObjectName(u"OV_txt_AnimalID")
        self.OV_txt_AnimalID.setGeometry(QRect(79, -1, 71, 21))
        self.OV_txt_AnimalID.setFont(font)
        self.OV_bkg_Box = QWidget(self.Overview)
        self.OV_bkg_Box.setObjectName(u"OV_bkg_Box")
        self.OV_bkg_Box.setGeometry(QRect(200, 10, 101, 21))
        self.OV_bkg_Box.setStyleSheet(u"background-color: rgb(185, 217, 206);")
        self.OV_lbl_Box = QLabel(self.OV_bkg_Box)
        self.OV_lbl_Box.setObjectName(u"OV_lbl_Box")
        self.OV_lbl_Box.setGeometry(QRect(8, 2, 31, 16))
        self.OV_lbl_Box.setFont(font8)
        self.OV_txt_Box = QLabel(self.OV_bkg_Box)
        self.OV_txt_Box.setObjectName(u"OV_txt_Box")
        self.OV_txt_Box.setGeometry(QRect(40, 3, 51, 16))
        self.Boxes.addTab(self.Overview, "")
        TaskGui.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TaskGui)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1600, 22))
        self.menuAdaptive_sensorimotor_decision_making_task = QMenu(self.menubar)
        self.menuAdaptive_sensorimotor_decision_making_task.setObjectName(u"menuAdaptive_sensorimotor_decision_making_task")
        TaskGui.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TaskGui)
        self.statusbar.setObjectName(u"statusbar")
        TaskGui.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAdaptive_sensorimotor_decision_making_task.menuAction())

        self.retranslateUi(TaskGui)

        self.Boxes.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(TaskGui)
    # setupUi

    def retranslateUi(self, TaskGui):
        TaskGui.setWindowTitle(QCoreApplication.translate("TaskGui", u"TaskGui", None))
        self.actionAdaptive_sensorimotor_decision_making_task.setText(QCoreApplication.translate("TaskGui", u"Adaptive sensorimotor decision-making task", None))
        self.actionAdaptive_sensorimotor_decision_making_task_2.setText(QCoreApplication.translate("TaskGui", u"Adaptive sensorimotor decision-making task", None))
#if QT_CONFIG(accessibility)
        self.Box.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.lbl_AnimalID.setText(QCoreApplication.translate("TaskGui", u"Animal_ID :", None))
        self.btn_Start.setText(QCoreApplication.translate("TaskGui", u"START", None))
        self.btn_Stop.setText(QCoreApplication.translate("TaskGui", u"STOP", None))
        self.lbl_Task.setText(QCoreApplication.translate("TaskGui", u"Task :", None))
        self.lbl_TaskTimeline.setText(QCoreApplication.translate("TaskGui", u"Task Timeline Params :", None))
        self.lbl_RigParams.setText(QCoreApplication.translate("TaskGui", u"Test Rig Params :", None))
        self.chk_BlueLED.setText(QCoreApplication.translate("TaskGui", u"Blue LED", None))
        self.chk_WhiteLED_Left.setText(QCoreApplication.translate("TaskGui", u"White LED - Left", None))
        self.chk_16Tone.setText(QCoreApplication.translate("TaskGui", u"16KHz Tone", None))
        self.chk_8Tone.setText(QCoreApplication.translate("TaskGui", u"8KHz Tone", None))
        self.chk_Reward_right.setText(QCoreApplication.translate("TaskGui", u"Reward - right spout", None))
        self.chk_Punishment.setText(QCoreApplication.translate("TaskGui", u"WN - Punishment", None))
        self.lbl_QuietWindow.setText(QCoreApplication.translate("TaskGui", u"Quiet Window", None))
        self.lbl_QW_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_RW_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ResponseWindow.setText(QCoreApplication.translate("TaskGui", u"Response Window", None))
        self.lbl_ITI.setText(QCoreApplication.translate("TaskGui", u"ITI", None))
        self.lbl_TD_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_RewardParams.setText(QCoreApplication.translate("TaskGui", u"Reward Params :", None))
        self.lbl_VO_ms.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ValveOpening.setText(QCoreApplication.translate("TaskGui", u"Valve Opening", None))
        self.lbl_OptoProtocols.setText(QCoreApplication.translate("TaskGui", u"Optotagging Protocols :", None))
        self.chk_WhiteLED_Right.setText(QCoreApplication.translate("TaskGui", u"White LED - Right", None))
        self.txt_Date.setText(QCoreApplication.translate("TaskGui", u"TextLabel", None))
        self.lbl_Date.setText(QCoreApplication.translate("TaskGui", u"Date :", None))
        self.btn_Update.setText(QCoreApplication.translate("TaskGui", u"UPDATE", None))
        self.chk_Reward_left.setText(QCoreApplication.translate("TaskGui", u"Reward - left spout", None))
        self.lbl_AssociationTrials.setText(QCoreApplication.translate("TaskGui", u"Association trials :", None))
        self.lbl_Box.setText(QCoreApplication.translate("TaskGui", u"Box:", None))
        self.chk_NoPunishment.setText(QCoreApplication.translate("TaskGui", u"No Punishment", None))
        self.lbl_AssociationTrials_3.setText(QCoreApplication.translate("TaskGui", u"Level 1", None))
        self.lbl_QuietWindow_5.setText(QCoreApplication.translate("TaskGui", u"No punishment", None))
        self.lbl_QuietWindow_7.setText(QCoreApplication.translate("TaskGui", u"Ignore licks in WW", None))
        self.chk_IgnoreLicksWW.setText(QCoreApplication.translate("TaskGui", u"Ignore licks in Waiting Window", None))
        self.lbl_TrialDuration_2.setText(QCoreApplication.translate("TaskGui", u"min", None))
        self.lbl_TrialDuration_3.setText(QCoreApplication.translate("TaskGui", u"-", None))
        self.lbl_TD_s_2.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_TrialDuration_4.setText(QCoreApplication.translate("TaskGui", u"max", None))
        self.btn_FlushWater_left.setText(QCoreApplication.translate("TaskGui", u"Left", None))
        self.btn_FlushWater_right.setText(QCoreApplication.translate("TaskGui", u"Right", None))
        self.lbl_FlushWater.setText(QCoreApplication.translate("TaskGui", u"Flush Water", None))
        self.btn_Calibration.setText(QCoreApplication.translate("TaskGui", u"Calibration Pumps", None))
        self.lbl_Blocks_2.setText(QCoreApplication.translate("TaskGui", u"Blocks", None))
        self.btn_Opto10.setText(QCoreApplication.translate("TaskGui", u"Test 10ms Pulses", None))
        self.btn_Opto100.setText(QCoreApplication.translate("TaskGui", u"Test 100ms Pulses", None))
        self.chk_Manip_sound_lights.setText(QCoreApplication.translate("TaskGui", u"Manip. Sound + lights", None))
        self.lbl_TaskSettings.setText(QCoreApplication.translate("TaskGui", u"Task Settings", None))
        self.lbl_Visualization.setText(QCoreApplication.translate("TaskGui", u"Visualization", None))
        self.lbl_AnimalPerformance.setText(QCoreApplication.translate("TaskGui", u"Animal's Performance", None))
        self.lbl_LickTrace_right.setText(QCoreApplication.translate("TaskGui", u"Lick Trace - Right Spout", None))
        self.lbl_LickTrace_left.setText(QCoreApplication.translate("TaskGui", u"Lick Trace - Left Spout", None))
        self.lbl_Time.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.lbl_B1.setText("")
        self.lbl_B2.setText("")
        self.lbl_B3.setText("")
        self.lbl_B4.setText("")
        self.lbl_B5.setText("")
        self.lbl_B6.setText("")
        self.lbl_B7.setText("")
        self.lbl_B8.setText("")
        self.lbl_B9.setText("")
        self.lbl_B10.setText("")
        self.lbl_B11.setText("")
        self.lbl_B12.setText("")
        self.lbl_B13.setText("")
        self.lbl_B14.setText("")
        self.lbl_B15.setText("")
        self.lbl_O1.setText("")
        self.lbl_O2.setText("")
        self.lbl_O3.setText("")
        self.lbl_O4.setText("")
        self.lbl_O5.setText("")
        self.lbl_O6.setText("")
        self.lbl_O7.setText("")
        self.lbl_O8.setText("")
        self.lbl_O9.setText("")
        self.lbl_O10.setText("")
        self.lbl_O11.setText("")
        self.lbl_O12.setText("")
        self.lbl_O13.setText("")
        self.lbl_O14.setText("")
        self.lbl_O15.setText("")
        self.lbl_T1.setText("")
        self.lbl_T2.setText("")
        self.lbl_T3.setText("")
        self.lbl_T4.setText("")
        self.lbl_T5.setText("")
        self.lbl_T6.setText("")
        self.lbl_T12.setText("")
        self.lbl_TrialMonitor.setText(QCoreApplication.translate("TaskGui", u"Trial monitor", None))
        self.lbl_LegendTrialMonitor.setText(QCoreApplication.translate("TaskGui", u"B - Block type    O - Outcome   T - Trial number    S - Sound    AL - Action left    AR - Action right", None))
        self.lbl_Blocks.setText(QCoreApplication.translate("TaskGui", u"B", None))
        self.lbl_Outcome.setText(QCoreApplication.translate("TaskGui", u"O", None))
        self.lbl_Trials.setText(QCoreApplication.translate("TaskGui", u"T", None))
        self.lbl_CorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.lbl_IncorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.box_Omissions.setText("")
        self.lbl_Omissions.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.lbl_EarlyLicks.setText(QCoreApplication.translate("TaskGui", u"Early licks:", None))
        self.box_EarlyLicks.setText("")
        self.box_IncorrectTrials.setText("")
        self.box_CorrectTrials.setText("")
        self.box_SoundBlocks.setText("")
        self.lbl_SoundBlocks.setText(QCoreApplication.translate("TaskGui", u"Sound Blocks:", None))
        self.box_Action_L_blocks.setText("")
        self.lbl_ActionLBlocks.setText(QCoreApplication.translate("TaskGui", u"Action L Blocks:", None))
        self.box_Action_R_blocks.setText("")
        self.lbl_ActionRBlocks.setText(QCoreApplication.translate("TaskGui", u"Action R Blocks:", None))
        self.txt_Chronometer.setText("")
        self.lbl_CatchTrials.setText(QCoreApplication.translate("TaskGui", u"Catch Trials:", None))
        self.box_CatchTrials.setText("")
        self.plt_Camera.setText("")
        self.plt_AnimalPerformance.setText("")
        self.lbl_LicksRight.setText(QCoreApplication.translate("TaskGui", u"Licks Right:", None))
        self.box_LicksRight.setText("")
        self.box_TotalLicks.setText("")
        self.lbl_TotalLicks.setText(QCoreApplication.translate("TaskGui", u"Total Licks: ", None))
        self.lbl_LicksLeft.setText(QCoreApplication.translate("TaskGui", u"Licks Left:", None))
        self.box_LicksLeft.setText("")
        self.lbl_TR_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ThresholdRight.setText(QCoreApplication.translate("TaskGui", u"Threshold Right", None))
        self.lbl_TL_s.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.lbl_ThresholdLeft.setText(QCoreApplication.translate("TaskGui", u"Threshold Left", None))
        self.lbl_TrialDuration.setText(QCoreApplication.translate("TaskGui", u"Trial Duration:", None))
        self.box_TrialDuration.setText("")
        self.lbl_VO_ms_2.setText(QCoreApplication.translate("TaskGui", u"[s]", None))
        self.box_8KHzTrials.setText("")
        self.lbl_16KHzTrials.setText(QCoreApplication.translate("TaskGui", u"16KHz Trials:", None))
        self.box_16KHzTrials.setText("")
        self.lbl_8KHzTrials.setText(QCoreApplication.translate("TaskGui", u"8KHz Trials: ", None))
        self.lbl_TotalTrials.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.box_TotalTrials.setText("")
        self.box_CurrentTrial.setText("")
        self.lbl_TotalTrials_2.setText(QCoreApplication.translate("TaskGui", u"Bias:", None))
        self.box_Bias.setText("")
        self.label.setText(QCoreApplication.translate("TaskGui", u"<0.5 Left ", None))
        self.label_2.setText(QCoreApplication.translate("TaskGui", u">0.5 Right ", None))
        self.lbl_T7.setText("")
        self.lbl_T8.setText("")
        self.lbl_T9.setText("")
        self.lbl_T10.setText("")
        self.lbl_T11.setText("")
        self.lbl_T13.setText("")
        self.lbl_T14.setText("")
        self.lbl_T15.setText("")
        self.lbl_CamSettings.setText(QCoreApplication.translate("TaskGui", u"Cam settings:", None))
        self.lbl_Exposure.setText(QCoreApplication.translate("TaskGui", u"Exposure", None))
        self.lbl_Brightness.setText(QCoreApplication.translate("TaskGui", u"Brightness", None))
        self.lbl_Contrast.setText(QCoreApplication.translate("TaskGui", u"Contrast", None))
        self.btn_cam_reset.setText(QCoreApplication.translate("TaskGui", u"Reset", None))
        self.lbl_ArduinoStatus.setText("")
        self.lbl_Date_2.setText(QCoreApplication.translate("TaskGui", u"Arduino:", None))
        self.lbl_Date_3.setText(QCoreApplication.translate("TaskGui", u"Camera", None))
        self.lbl_CameraStatus.setText("")
        self.btn_CheckHardware.setText(QCoreApplication.translate("TaskGui", u"Check", None))
        self.Boxes.setTabText(self.Boxes.indexOf(self.Box), QCoreApplication.translate("TaskGui", u"GUI", None))
        self.OV_Box.setTitle("")
        self.OV_box_Chronometer.setText("")
        self.OV_lbl_Time.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.OV_lbl_Omissions.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.OV_box_CorrectTrials.setText("")
        self.OV_box_IncorrectTrials.setText("")
        self.OV_box_TotalTrials.setText("")
        self.OV_lbl_TotalTrials.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.OV_box_Omissions.setText("")
        self.OV_lbl_IncorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.OV_lbl_CorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.OV_lbl_CurrentTrial.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.OV_box_CurrentTrial.setText("")
        self.OV_plt_Camera.setText("")
        self.OV_plt_AnimalPerformance.setText("")
        self.OV_lbl_TotalLicks.setText(QCoreApplication.translate("TaskGui", u"Total Licks: ", None))
        self.OV_box_TotalLicks.setText("")
        self.OV_lbl_Task.setText(QCoreApplication.translate("TaskGui", u"Task:", None))
        self.OV_txt_Task.setText("")
        self.OV_lbl_AnimalID.setText(QCoreApplication.translate("TaskGui", u"Animal ID:", None))
        self.OV_txt_AnimalID.setText("")
        self.OV_lbl_Box.setText(QCoreApplication.translate("TaskGui", u"Box:", None))
        self.OV_txt_Box.setText("")
        self.Boxes.setTabText(self.Boxes.indexOf(self.Overview), QCoreApplication.translate("TaskGui", u"Overview", None))
        self.menuAdaptive_sensorimotor_decision_making_task.setTitle(QCoreApplication.translate("TaskGui", u"   Adaptive sensorimotor decision-making task  ", None))
    # retranslateUi

