# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'form.ui'
##
## Created by: Qt User Interface Compiler version 6.7.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGroupBox, QHBoxLayout, QLabel, QLayout,
    QLineEdit, QMainWindow, QMenu, QMenuBar,
    QPushButton, QRadioButton, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_TaskGui(object):
    def setupUi(self, TaskGui):
        if not TaskGui.objectName():
            TaskGui.setObjectName(u"TaskGui")
        TaskGui.resize(1600, 916)
        self.actionAdaptive_sensorimotor_decision_making_task = QAction(TaskGui)
        self.actionAdaptive_sensorimotor_decision_making_task.setObjectName(u"actionAdaptive_sensorimotor_decision_making_task")
        self.actionAdaptive_sensorimotor_decision_making_task_2 = QAction(TaskGui)
        self.actionAdaptive_sensorimotor_decision_making_task_2.setObjectName(u"actionAdaptive_sensorimotor_decision_making_task_2")
        self.centralwidget = QWidget(TaskGui)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        self.Boxes = QTabWidget(self.centralwidget)
        self.Boxes.setObjectName(u"Boxes")
        self.Boxes.setGeometry(QRect(-1, 9, 1591, 871))
        font = QFont()
        font.setPointSize(10)
        self.Boxes.setFont(font)
        self.Rbpi_Connection = QWidget()
        self.Rbpi_Connection.setObjectName(u"Rbpi_Connection")
        self.label_10 = QLabel(self.Rbpi_Connection)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 191, 51, 21))
        font1 = QFont()
        font1.setPointSize(11)
        font1.setBold(True)
        self.label_10.setFont(font1)
        self.pushButton = QPushButton(self.Rbpi_Connection)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(120, 185, 81, 31))
        self.pushButton_5 = QPushButton(self.Rbpi_Connection)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(220, 185, 81, 31))
        self.label_11 = QLabel(self.Rbpi_Connection)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 272, 51, 21))
        self.label_11.setFont(font1)
        self.pushButton_6 = QPushButton(self.Rbpi_Connection)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(220, 266, 81, 31))
        self.pushButton_7 = QPushButton(self.Rbpi_Connection)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(120, 266, 81, 31))
        self.label_12 = QLabel(self.Rbpi_Connection)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(60, 352, 51, 21))
        self.label_12.setFont(font1)
        self.pushButton_8 = QPushButton(self.Rbpi_Connection)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(220, 346, 81, 31))
        self.pushButton_9 = QPushButton(self.Rbpi_Connection)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(120, 346, 81, 31))
        self.label_13 = QLabel(self.Rbpi_Connection)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(470, 191, 51, 21))
        self.label_13.setFont(font1)
        self.pushButton_10 = QPushButton(self.Rbpi_Connection)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(630, 185, 81, 31))
        self.pushButton_11 = QPushButton(self.Rbpi_Connection)
        self.pushButton_11.setObjectName(u"pushButton_11")
        self.pushButton_11.setGeometry(QRect(530, 185, 81, 31))
        self.label_14 = QLabel(self.Rbpi_Connection)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(442, 271, 71, 21))
        self.label_14.setFont(font1)
        self.pushButton_12 = QPushButton(self.Rbpi_Connection)
        self.pushButton_12.setObjectName(u"pushButton_12")
        self.pushButton_12.setGeometry(QRect(630, 265, 81, 31))
        self.pushButton_13 = QPushButton(self.Rbpi_Connection)
        self.pushButton_13.setObjectName(u"pushButton_13")
        self.pushButton_13.setGeometry(QRect(530, 265, 81, 31))
        self.label_16 = QLabel(self.Rbpi_Connection)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 30, 711, 21))
        self.label_16.setFont(font)
        self.label_15 = QLabel(self.Rbpi_Connection)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(50, 97, 61, 21))
        self.label_15.setFont(font1)
        self.pushButton_14 = QPushButton(self.Rbpi_Connection)
        self.pushButton_14.setObjectName(u"pushButton_14")
        self.pushButton_14.setGeometry(QRect(220, 92, 81, 31))
        self.pushButton_2 = QPushButton(self.Rbpi_Connection)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(120, 92, 81, 31))
        self.Boxes.addTab(self.Rbpi_Connection, "")
        self.Box1 = QWidget()
        self.Box1.setObjectName(u"Box1")
        self.Box1.setEnabled(True)
        font2 = QFont()
        font2.setPointSize(14)
        self.Box1.setFont(font2)
        self.TaskSettings = QWidget(self.Box1)
        self.TaskSettings.setObjectName(u"TaskSettings")
        self.TaskSettings.setGeometry(QRect(10, 30, 501, 801))
        self.TaskSettings.setStyleSheet(u"background-color: rgb(231, 231, 231);")
        self.label_B1_AnimalID = QLabel(self.TaskSettings)
        self.label_B1_AnimalID.setObjectName(u"label_B1_AnimalID")
        self.label_B1_AnimalID.setGeometry(QRect(20, 57, 61, 20))
        font3 = QFont()
        font3.setPointSize(8)
        self.label_B1_AnimalID.setFont(font3)
        self.Box1_Start = QPushButton(self.TaskSettings)
        self.Box1_Start.setObjectName(u"Box1_Start")
        self.Box1_Start.setGeometry(QRect(349, 26, 61, 31))
        self.Box1_Start.setStyleSheet(u"background-color: rgb(216, 244, 211);\n"
"font: 700 8pt \"Segoe UI\";")
        self.Box1_Stop = QPushButton(self.TaskSettings)
        self.Box1_Stop.setObjectName(u"Box1_Stop")
        self.Box1_Stop.setGeometry(QRect(420, 26, 61, 31))
        self.Box1_Stop.setStyleSheet(u"font: 700 8pt \"Segoe UI\";\n"
"background-color: rgb(255, 203, 198);")
        self.Box1_Animal_ID = QComboBox(self.TaskSettings)
        self.Box1_Animal_ID.setObjectName(u"Box1_Animal_ID")
        self.Box1_Animal_ID.setGeometry(QRect(100, 57, 110, 21))
        self.Box1_Animal_ID.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.Box1_Animal_ID.setEditable(True)
        self.Box1_Task = QComboBox(self.TaskSettings)
        self.Box1_Task.addItem("")
        self.Box1_Task.addItem("")
        self.Box1_Task.addItem("")
        self.Box1_Task.addItem("")
        self.Box1_Task.addItem("")
        self.Box1_Task.addItem("")
        self.Box1_Task.addItem("")
        self.Box1_Task.setObjectName(u"Box1_Task")
        self.Box1_Task.setGeometry(QRect(60, 98, 261, 31))
        self.Box1_Task.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.Box1_Task.setEditable(True)
        self.Box1_Task.setFrame(True)
        self.label_B1_Task = QLabel(self.TaskSettings)
        self.label_B1_Task.setObjectName(u"label_B1_Task")
        self.label_B1_Task.setGeometry(QRect(20, 104, 41, 19))
        self.label_B1_Task.setFont(font3)
        self.label_B1_TaskTimeline = QLabel(self.TaskSettings)
        self.label_B1_TaskTimeline.setObjectName(u"label_B1_TaskTimeline")
        self.label_B1_TaskTimeline.setGeometry(QRect(20, 313, 131, 19))
        font4 = QFont()
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setUnderline(True)
        self.label_B1_TaskTimeline.setFont(font4)
        self.label_B1_TaskTimeline.setStyleSheet(u"")
        self.label_B1_RigParams = QLabel(self.TaskSettings)
        self.label_B1_RigParams.setObjectName(u"label_B1_RigParams")
        self.label_B1_RigParams.setGeometry(QRect(20, 166, 131, 19))
        self.label_B1_RigParams.setFont(font4)
        self.Box1_BlueLED = QRadioButton(self.TaskSettings)
        self.Box1_BlueLED.setObjectName(u"Box1_BlueLED")
        self.Box1_BlueLED.setGeometry(QRect(20, 198, 89, 20))
        font5 = QFont()
        font5.setPointSize(9)
        self.Box1_BlueLED.setFont(font5)
        self.Box1_WhiteLED_Left = QRadioButton(self.TaskSettings)
        self.Box1_WhiteLED_Left.setObjectName(u"Box1_WhiteLED_Left")
        self.Box1_WhiteLED_Left.setGeometry(QRect(20, 228, 111, 20))
        self.Box1_WhiteLED_Left.setFont(font5)
        self.Box1_10Tone = QRadioButton(self.TaskSettings)
        self.Box1_10Tone.setObjectName(u"Box1_10Tone")
        self.Box1_10Tone.setGeometry(QRect(179, 198, 89, 20))
        self.Box1_10Tone.setFont(font5)
        self.Box1_5Tone = QRadioButton(self.TaskSettings)
        self.Box1_5Tone.setObjectName(u"Box1_5Tone")
        self.Box1_5Tone.setGeometry(QRect(179, 228, 89, 20))
        self.Box1_5Tone.setFont(font5)
        self.Box1_Reward_right = QRadioButton(self.TaskSettings)
        self.Box1_Reward_right.setObjectName(u"Box1_Reward_right")
        self.Box1_Reward_right.setGeometry(QRect(331, 198, 131, 20))
        self.Box1_Reward_right.setFont(font5)
        self.Box1_Punishment = QRadioButton(self.TaskSettings)
        self.Box1_Punishment.setObjectName(u"Box1_Punishment")
        self.Box1_Punishment.setGeometry(QRect(331, 228, 121, 20))
        self.Box1_Punishment.setFont(font5)
        self.label_B1_QuietWindow = QLabel(self.TaskSettings)
        self.label_B1_QuietWindow.setObjectName(u"label_B1_QuietWindow")
        self.label_B1_QuietWindow.setGeometry(QRect(23, 349, 90, 20))
        self.label_B1_QuietWindow.setFont(font5)
        self.Box1_QuietWindow = QLineEdit(self.TaskSettings)
        self.Box1_QuietWindow.setObjectName(u"Box1_QuietWindow")
        self.Box1_QuietWindow.setGeometry(QRect(110, 348, 51, 22))
        self.Box1_QuietWindow.setFont(font5)
        self.label_B1_QW_ms = QLabel(self.TaskSettings)
        self.label_B1_QW_ms.setObjectName(u"label_B1_QW_ms")
        self.label_B1_QW_ms.setGeometry(QRect(173, 349, 41, 20))
        self.label_B1_QW_ms.setFont(font5)
        self.label_B1_RW_ms = QLabel(self.TaskSettings)
        self.label_B1_RW_ms.setObjectName(u"label_B1_RW_ms")
        self.label_B1_RW_ms.setGeometry(QRect(193, 387, 41, 20))
        self.label_B1_RW_ms.setFont(font5)
        self.Box1_ResponseWindow = QLineEdit(self.TaskSettings)
        self.Box1_ResponseWindow.setObjectName(u"Box1_ResponseWindow")
        self.Box1_ResponseWindow.setGeometry(QRect(130, 386, 51, 22))
        self.Box1_ResponseWindow.setFont(font5)
        self.label_B1_ResponseWindow = QLabel(self.TaskSettings)
        self.label_B1_ResponseWindow.setObjectName(u"label_B1_ResponseWindow")
        self.label_B1_ResponseWindow.setGeometry(QRect(24, 387, 101, 20))
        self.label_B1_ResponseWindow.setFont(font5)
        self.Box1_TrialDuration = QLineEdit(self.TaskSettings)
        self.Box1_TrialDuration.setObjectName(u"Box1_TrialDuration")
        self.Box1_TrialDuration.setGeometry(QRect(111, 423, 51, 22))
        self.Box1_TrialDuration.setFont(font5)
        self.label_B1_TrialDuration = QLabel(self.TaskSettings)
        self.label_B1_TrialDuration.setObjectName(u"label_B1_TrialDuration")
        self.label_B1_TrialDuration.setGeometry(QRect(24, 424, 81, 20))
        self.label_B1_TrialDuration.setFont(font5)
        self.label_B1_TD_ms = QLabel(self.TaskSettings)
        self.label_B1_TD_ms.setObjectName(u"label_B1_TD_ms")
        self.label_B1_TD_ms.setGeometry(QRect(174, 424, 41, 20))
        self.label_B1_TD_ms.setFont(font5)
        self.label_B1_RewardParams = QLabel(self.TaskSettings)
        self.label_B1_RewardParams.setObjectName(u"label_B1_RewardParams")
        self.label_B1_RewardParams.setGeometry(QRect(20, 489, 131, 19))
        self.label_B1_RewardParams.setFont(font4)
        self.label_B1_RewardParams.setStyleSheet(u"")
        self.label_B1_VO_ms = QLabel(self.TaskSettings)
        self.label_B1_VO_ms.setObjectName(u"label_B1_VO_ms")
        self.label_B1_VO_ms.setGeometry(QRect(173, 525, 41, 20))
        self.label_B1_VO_ms.setFont(font5)
        self.Box1_ValveOpening = QLineEdit(self.TaskSettings)
        self.Box1_ValveOpening.setObjectName(u"Box1_ValveOpening")
        self.Box1_ValveOpening.setGeometry(QRect(110, 524, 51, 22))
        self.Box1_ValveOpening.setFont(font5)
        self.label_B1_ValveOpening = QLabel(self.TaskSettings)
        self.label_B1_ValveOpening.setObjectName(u"label_B1_ValveOpening")
        self.label_B1_ValveOpening.setGeometry(QRect(23, 525, 90, 20))
        self.label_B1_ValveOpening.setFont(font5)
        self.label_B1_OptoProtocols = QLabel(self.TaskSettings)
        self.label_B1_OptoProtocols.setObjectName(u"label_B1_OptoProtocols")
        self.label_B1_OptoProtocols.setGeometry(QRect(20, 595, 131, 19))
        self.label_B1_OptoProtocols.setFont(font4)
        self.Box1_OptoShort = QCheckBox(self.TaskSettings)
        self.Box1_OptoShort.setObjectName(u"Box1_OptoShort")
        self.Box1_OptoShort.setGeometry(QRect(20, 635, 161, 20))
        self.Box1_OptoShort.setFont(font5)
        self.Box1_OptoLong = QCheckBox(self.TaskSettings)
        self.Box1_OptoLong.setObjectName(u"Box1_OptoLong")
        self.Box1_OptoLong.setGeometry(QRect(21, 665, 161, 20))
        self.Box1_OptoLong.setFont(font5)
        self.Box1_WhiteLED_Right = QRadioButton(self.TaskSettings)
        self.Box1_WhiteLED_Right.setObjectName(u"Box1_WhiteLED_Right")
        self.Box1_WhiteLED_Right.setGeometry(QRect(20, 259, 121, 20))
        self.Box1_WhiteLED_Right.setFont(font5)
        self.Box1_Date = QLabel(self.TaskSettings)
        self.Box1_Date.setObjectName(u"Box1_Date")
        self.Box1_Date.setGeometry(QRect(60, 20, 91, 16))
        self.Box1_Date.setFont(font3)
        self.label_B1_Date = QLabel(self.TaskSettings)
        self.label_B1_Date.setObjectName(u"label_B1_Date")
        self.label_B1_Date.setGeometry(QRect(20, 18, 31, 20))
        self.label_B1_Date.setFont(font3)
        self.pushButton_3 = QPushButton(self.TaskSettings)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(378, 99, 71, 31))
        font6 = QFont()
        font6.setPointSize(8)
        font6.setBold(True)
        self.pushButton_3.setFont(font6)
        self.pushButton_3.setStyleSheet(u"background-color: rgb(255, 225, 205);\n"
"border-color: rgb(227, 153, 100);")
        self.Box1_Reward_left = QRadioButton(self.TaskSettings)
        self.Box1_Reward_left.setObjectName(u"Box1_Reward_left")
        self.Box1_Reward_left.setGeometry(QRect(179, 258, 121, 20))
        self.Box1_Reward_left.setFont(font5)
        self.label_TaskSettings = QLabel(self.Box1)
        self.label_TaskSettings.setObjectName(u"label_TaskSettings")
        self.label_TaskSettings.setGeometry(QRect(20, 6, 111, 20))
        font7 = QFont()
        font7.setPointSize(10)
        font7.setBold(True)
        self.label_TaskSettings.setFont(font7)
        self.label_TaskSettings.setStyleSheet(u"color: rgb(217, 112, 7);")
        self.label_TaskSettings.setFrameShape(QFrame.NoFrame)
        self.label_TaskSettings.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_Visualization = QLabel(self.Box1)
        self.label_Visualization.setObjectName(u"label_Visualization")
        self.label_Visualization.setGeometry(QRect(559, 6, 111, 20))
        self.label_Visualization.setFont(font7)
        self.label_Visualization.setStyleSheet(u"\n"
"color: rgb(73, 192, 203);")
        self.label_Visualization.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.line = QFrame(self.Box1)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(520, 10, 20, 821))
        self.line.setFrameShape(QFrame.Shape.VLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)
        self.Box1_Camera = QWidget(self.Box1)
        self.Box1_Camera.setObjectName(u"Box1_Camera")
        self.Box1_Camera.setGeometry(QRect(590, 90, 421, 281))
        self.Box1_Camera.setStyleSheet(u"background-color: rgb(234, 238, 255);")
        self.Box1_AnimalsPerfomance = QWidget(self.Box1)
        self.Box1_AnimalsPerfomance.setObjectName(u"Box1_AnimalsPerfomance")
        self.Box1_AnimalsPerfomance.setGeometry(QRect(1120, 50, 441, 211))
        self.Box1_AnimalsPerfomance.setStyleSheet(u"background-color: rgb(234, 238, 255);")
        self.Box1_LickTrace_Right = QWidget(self.Box1)
        self.Box1_LickTrace_Right.setObjectName(u"Box1_LickTrace_Right")
        self.Box1_LickTrace_Right.setGeometry(QRect(1120, 322, 441, 211))
        self.Box1_LickTrace_Right.setStyleSheet(u"background-color: rgb(234, 238, 255);")
        self.Box1_LickTrace_Left = QWidget(self.Box1)
        self.Box1_LickTrace_Left.setObjectName(u"Box1_LickTrace_Left")
        self.Box1_LickTrace_Left.setGeometry(QRect(1120, 594, 441, 211))
        self.Box1_LickTrace_Left.setStyleSheet(u"background-color: rgb(234, 238, 255);")
        self.label_B1_AnimalPerformance = QLabel(self.Box1)
        self.label_B1_AnimalPerformance.setObjectName(u"label_B1_AnimalPerformance")
        self.label_B1_AnimalPerformance.setGeometry(QRect(1131, 25, 131, 20))
        self.label_B1_AnimalPerformance.setFont(font)
        self.label_B1_AnimalPerformance.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_B1_LickTrace_right = QLabel(self.Box1)
        self.label_B1_LickTrace_right.setObjectName(u"label_B1_LickTrace_right")
        self.label_B1_LickTrace_right.setGeometry(QRect(1130, 298, 141, 20))
        self.label_B1_LickTrace_right.setFont(font)
        self.label_B1_LickTrace_right.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_B1_LickTrace_left = QLabel(self.Box1)
        self.label_B1_LickTrace_left.setObjectName(u"label_B1_LickTrace_left")
        self.label_B1_LickTrace_left.setGeometry(QRect(1130, 570, 131, 20))
        self.label_B1_LickTrace_left.setFont(font)
        self.label_B1_LickTrace_left.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.label_B1_Time = QLabel(self.Box1)
        self.label_B1_Time.setObjectName(u"label_B1_Time")
        self.label_B1_Time.setGeometry(QRect(693, 43, 41, 20))
        self.label_B1_Time.setFont(font7)
        self.Background_B1_Blocks = QWidget(self.Box1)
        self.Background_B1_Blocks.setObjectName(u"Background_B1_Blocks")
        self.Background_B1_Blocks.setGeometry(QRect(574, 468, 471, 31))
        self.Background_B1_Blocks.setStyleSheet(u"background-color: rgb(214, 236, 238);")
        self.layoutWidget_2 = QWidget(self.Background_B1_Blocks)
        self.layoutWidget_2.setObjectName(u"layoutWidget_2")
        self.layoutWidget_2.setGeometry(QRect(8, 4, 451, 20))
        self.Layout_B1_Blocks = QHBoxLayout(self.layoutWidget_2)
        self.Layout_B1_Blocks.setSpacing(16)
        self.Layout_B1_Blocks.setObjectName(u"Layout_B1_Blocks")
        self.Layout_B1_Blocks.setContentsMargins(0, 0, 0, 0)
        self.label_58 = QLabel(self.layoutWidget_2)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setFont(font)
        self.label_58.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_58)

        self.label_59 = QLabel(self.layoutWidget_2)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setFont(font)
        self.label_59.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_59)

        self.label_60 = QLabel(self.layoutWidget_2)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setFont(font)
        self.label_60.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_60)

        self.label_91 = QLabel(self.layoutWidget_2)
        self.label_91.setObjectName(u"label_91")
        self.label_91.setFont(font)
        self.label_91.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_91)

        self.label_92 = QLabel(self.layoutWidget_2)
        self.label_92.setObjectName(u"label_92")
        self.label_92.setFont(font)
        self.label_92.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_92)

        self.label_93 = QLabel(self.layoutWidget_2)
        self.label_93.setObjectName(u"label_93")
        self.label_93.setFont(font)
        self.label_93.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_93)

        self.label_94 = QLabel(self.layoutWidget_2)
        self.label_94.setObjectName(u"label_94")
        self.label_94.setFont(font)
        self.label_94.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_94)

        self.label_95 = QLabel(self.layoutWidget_2)
        self.label_95.setObjectName(u"label_95")
        self.label_95.setFont(font)
        self.label_95.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_95)

        self.label_96 = QLabel(self.layoutWidget_2)
        self.label_96.setObjectName(u"label_96")
        self.label_96.setFont(font)
        self.label_96.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_96)

        self.label_97 = QLabel(self.layoutWidget_2)
        self.label_97.setObjectName(u"label_97")
        self.label_97.setFont(font)
        self.label_97.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_97)

        self.label_98 = QLabel(self.layoutWidget_2)
        self.label_98.setObjectName(u"label_98")
        self.label_98.setFont(font)
        self.label_98.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_98)

        self.label_99 = QLabel(self.layoutWidget_2)
        self.label_99.setObjectName(u"label_99")
        self.label_99.setFont(font)
        self.label_99.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_99)

        self.label_100 = QLabel(self.layoutWidget_2)
        self.label_100.setObjectName(u"label_100")
        self.label_100.setFont(font)
        self.label_100.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_100)

        self.label_101 = QLabel(self.layoutWidget_2)
        self.label_101.setObjectName(u"label_101")
        self.label_101.setFont(font)
        self.label_101.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_101)

        self.label_102 = QLabel(self.layoutWidget_2)
        self.label_102.setObjectName(u"label_102")
        self.label_102.setFont(font)
        self.label_102.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Blocks.addWidget(self.label_102)

        self.Background_B1_LeftSpout = QWidget(self.Box1)
        self.Background_B1_LeftSpout.setObjectName(u"Background_B1_LeftSpout")
        self.Background_B1_LeftSpout.setGeometry(QRect(574, 502, 471, 30))
        self.Background_B1_LeftSpout.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.layoutWidget = QWidget(self.Background_B1_LeftSpout)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.layoutWidget.setGeometry(QRect(10, 9, 448, 20))
        self.Layout_B1_LeftSpout = QHBoxLayout(self.layoutWidget)
        self.Layout_B1_LeftSpout.setSpacing(19)
        self.Layout_B1_LeftSpout.setObjectName(u"Layout_B1_LeftSpout")
        self.Layout_B1_LeftSpout.setSizeConstraint(QLayout.SetNoConstraint)
        self.Layout_B1_LeftSpout.setContentsMargins(0, 0, 0, 0)
        self.label_76 = QLabel(self.layoutWidget)
        self.label_76.setObjectName(u"label_76")
        self.label_76.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_76)

        self.label_77 = QLabel(self.layoutWidget)
        self.label_77.setObjectName(u"label_77")
        self.label_77.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_77)

        self.label_78 = QLabel(self.layoutWidget)
        self.label_78.setObjectName(u"label_78")
        self.label_78.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_78)

        self.label_79 = QLabel(self.layoutWidget)
        self.label_79.setObjectName(u"label_79")
        self.label_79.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_79)

        self.label_80 = QLabel(self.layoutWidget)
        self.label_80.setObjectName(u"label_80")
        self.label_80.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_80)

        self.label_81 = QLabel(self.layoutWidget)
        self.label_81.setObjectName(u"label_81")
        self.label_81.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_81)

        self.label_82 = QLabel(self.layoutWidget)
        self.label_82.setObjectName(u"label_82")
        self.label_82.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_82)

        self.label_83 = QLabel(self.layoutWidget)
        self.label_83.setObjectName(u"label_83")
        self.label_83.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_83)

        self.label_84 = QLabel(self.layoutWidget)
        self.label_84.setObjectName(u"label_84")
        self.label_84.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_84)

        self.label_85 = QLabel(self.layoutWidget)
        self.label_85.setObjectName(u"label_85")
        self.label_85.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_85)

        self.label_86 = QLabel(self.layoutWidget)
        self.label_86.setObjectName(u"label_86")
        self.label_86.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_86)

        self.label_87 = QLabel(self.layoutWidget)
        self.label_87.setObjectName(u"label_87")
        self.label_87.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_87)

        self.label_88 = QLabel(self.layoutWidget)
        self.label_88.setObjectName(u"label_88")
        self.label_88.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_88)

        self.label_89 = QLabel(self.layoutWidget)
        self.label_89.setObjectName(u"label_89")
        self.label_89.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_89)

        self.label_90 = QLabel(self.layoutWidget)
        self.label_90.setObjectName(u"label_90")
        self.label_90.setFrameShape(QFrame.Box)

        self.Layout_B1_LeftSpout.addWidget(self.label_90)

        self.Background_B1_RightSpout = QWidget(self.Box1)
        self.Background_B1_RightSpout.setObjectName(u"Background_B1_RightSpout")
        self.Background_B1_RightSpout.setGeometry(QRect(574, 537, 471, 31))
        self.Background_B1_RightSpout.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.layoutWidget1 = QWidget(self.Background_B1_RightSpout)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.layoutWidget1.setGeometry(QRect(10, 9, 448, 20))
        self.Layout_B1_RightSpout = QHBoxLayout(self.layoutWidget1)
        self.Layout_B1_RightSpout.setSpacing(19)
        self.Layout_B1_RightSpout.setObjectName(u"Layout_B1_RightSpout")
        self.Layout_B1_RightSpout.setSizeConstraint(QLayout.SetNoConstraint)
        self.Layout_B1_RightSpout.setContentsMargins(0, 0, 0, 0)
        self.label_61 = QLabel(self.layoutWidget1)
        self.label_61.setObjectName(u"label_61")
        self.label_61.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_61)

        self.label_62 = QLabel(self.layoutWidget1)
        self.label_62.setObjectName(u"label_62")
        self.label_62.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_62)

        self.label_63 = QLabel(self.layoutWidget1)
        self.label_63.setObjectName(u"label_63")
        self.label_63.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_63)

        self.label_64 = QLabel(self.layoutWidget1)
        self.label_64.setObjectName(u"label_64")
        self.label_64.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_64)

        self.label_65 = QLabel(self.layoutWidget1)
        self.label_65.setObjectName(u"label_65")
        self.label_65.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_65)

        self.label_66 = QLabel(self.layoutWidget1)
        self.label_66.setObjectName(u"label_66")
        self.label_66.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_66)

        self.label_67 = QLabel(self.layoutWidget1)
        self.label_67.setObjectName(u"label_67")
        self.label_67.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_67)

        self.label_68 = QLabel(self.layoutWidget1)
        self.label_68.setObjectName(u"label_68")
        self.label_68.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_68)

        self.label_69 = QLabel(self.layoutWidget1)
        self.label_69.setObjectName(u"label_69")
        self.label_69.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_69)

        self.label_70 = QLabel(self.layoutWidget1)
        self.label_70.setObjectName(u"label_70")
        self.label_70.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_70)

        self.label_71 = QLabel(self.layoutWidget1)
        self.label_71.setObjectName(u"label_71")
        self.label_71.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_71)

        self.label_72 = QLabel(self.layoutWidget1)
        self.label_72.setObjectName(u"label_72")
        self.label_72.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_72)

        self.label_73 = QLabel(self.layoutWidget1)
        self.label_73.setObjectName(u"label_73")
        self.label_73.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_73)

        self.label_74 = QLabel(self.layoutWidget1)
        self.label_74.setObjectName(u"label_74")
        self.label_74.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_74)

        self.label_75 = QLabel(self.layoutWidget1)
        self.label_75.setObjectName(u"label_75")
        self.label_75.setFrameShape(QFrame.Box)

        self.Layout_B1_RightSpout.addWidget(self.label_75)

        self.Background_B1_Trials = QWidget(self.Box1)
        self.Background_B1_Trials.setObjectName(u"Background_B1_Trials")
        self.Background_B1_Trials.setGeometry(QRect(574, 572, 471, 31))
        self.Background_B1_Trials.setStyleSheet(u"background-color: rgb(235, 235, 235);")
        self.layoutWidget_3 = QWidget(self.Background_B1_Trials)
        self.layoutWidget_3.setObjectName(u"layoutWidget_3")
        self.layoutWidget_3.setGeometry(QRect(9, 8, 451, 20))
        self.Layout_B1_Trials = QHBoxLayout(self.layoutWidget_3)
        self.Layout_B1_Trials.setSpacing(17)
        self.Layout_B1_Trials.setObjectName(u"Layout_B1_Trials")
        self.Layout_B1_Trials.setContentsMargins(0, 0, 0, 0)
        self.label_103 = QLabel(self.layoutWidget_3)
        self.label_103.setObjectName(u"label_103")
        self.label_103.setFont(font)
        self.label_103.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_103)

        self.label_104 = QLabel(self.layoutWidget_3)
        self.label_104.setObjectName(u"label_104")
        self.label_104.setFont(font)
        self.label_104.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_104)

        self.label_105 = QLabel(self.layoutWidget_3)
        self.label_105.setObjectName(u"label_105")
        self.label_105.setFont(font)
        self.label_105.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_105)

        self.label_106 = QLabel(self.layoutWidget_3)
        self.label_106.setObjectName(u"label_106")
        self.label_106.setFont(font)
        self.label_106.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_106)

        self.label_107 = QLabel(self.layoutWidget_3)
        self.label_107.setObjectName(u"label_107")
        self.label_107.setFont(font)
        self.label_107.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_107)

        self.label_108 = QLabel(self.layoutWidget_3)
        self.label_108.setObjectName(u"label_108")
        self.label_108.setFont(font)
        self.label_108.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_108)

        self.label_109 = QLabel(self.layoutWidget_3)
        self.label_109.setObjectName(u"label_109")
        self.label_109.setFont(font)
        self.label_109.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_109)

        self.label_110 = QLabel(self.layoutWidget_3)
        self.label_110.setObjectName(u"label_110")
        self.label_110.setFont(font)
        self.label_110.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_110)

        self.label_111 = QLabel(self.layoutWidget_3)
        self.label_111.setObjectName(u"label_111")
        self.label_111.setFont(font)
        self.label_111.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_111)

        self.label_112 = QLabel(self.layoutWidget_3)
        self.label_112.setObjectName(u"label_112")
        self.label_112.setFont(font)
        self.label_112.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_112)

        self.label_113 = QLabel(self.layoutWidget_3)
        self.label_113.setObjectName(u"label_113")
        self.label_113.setFont(font)
        self.label_113.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_113)

        self.label_114 = QLabel(self.layoutWidget_3)
        self.label_114.setObjectName(u"label_114")
        self.label_114.setFont(font)
        self.label_114.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_114)

        self.label_115 = QLabel(self.layoutWidget_3)
        self.label_115.setObjectName(u"label_115")
        self.label_115.setFont(font)
        self.label_115.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_115)

        self.label_116 = QLabel(self.layoutWidget_3)
        self.label_116.setObjectName(u"label_116")
        self.label_116.setFont(font)
        self.label_116.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_116)

        self.label_117 = QLabel(self.layoutWidget_3)
        self.label_117.setObjectName(u"label_117")
        self.label_117.setFont(font)
        self.label_117.setAlignment(Qt.AlignCenter)

        self.Layout_B1_Trials.addWidget(self.label_117)

        self.line_3 = QFrame(self.Background_B1_Trials)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setGeometry(QRect(10, 0, 16, 10))
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        font8 = QFont()
        font8.setPointSize(9)
        font8.setBold(True)
        self.line_3.setFont(font8)
        self.line_3.setFrameShape(QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_4 = QFrame(self.Background_B1_Trials)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setGeometry(QRect(40, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy)
        self.line_4.setFont(font8)
        self.line_4.setFrameShape(QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_5 = QFrame(self.Background_B1_Trials)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setGeometry(QRect(70, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_5.sizePolicy().hasHeightForWidth())
        self.line_5.setSizePolicy(sizePolicy)
        self.line_5.setFont(font8)
        self.line_5.setFrameShape(QFrame.Shape.VLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_6 = QFrame(self.Background_B1_Trials)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setGeometry(QRect(101, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_6.sizePolicy().hasHeightForWidth())
        self.line_6.setSizePolicy(sizePolicy)
        self.line_6.setFont(font8)
        self.line_6.setFrameShape(QFrame.Shape.VLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_7 = QFrame(self.Background_B1_Trials)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setGeometry(QRect(133, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_7.sizePolicy().hasHeightForWidth())
        self.line_7.setSizePolicy(sizePolicy)
        self.line_7.setFont(font8)
        self.line_7.setFrameShape(QFrame.Shape.VLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_8 = QFrame(self.Background_B1_Trials)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setGeometry(QRect(164, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_8.sizePolicy().hasHeightForWidth())
        self.line_8.setSizePolicy(sizePolicy)
        self.line_8.setFont(font8)
        self.line_8.setFrameShape(QFrame.Shape.VLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_9 = QFrame(self.Background_B1_Trials)
        self.line_9.setObjectName(u"line_9")
        self.line_9.setGeometry(QRect(195, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_9.sizePolicy().hasHeightForWidth())
        self.line_9.setSizePolicy(sizePolicy)
        self.line_9.setFont(font8)
        self.line_9.setFrameShape(QFrame.Shape.VLine)
        self.line_9.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_10 = QFrame(self.Background_B1_Trials)
        self.line_10.setObjectName(u"line_10")
        self.line_10.setGeometry(QRect(227, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_10.sizePolicy().hasHeightForWidth())
        self.line_10.setSizePolicy(sizePolicy)
        self.line_10.setFont(font8)
        self.line_10.setFrameShape(QFrame.Shape.VLine)
        self.line_10.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_11 = QFrame(self.Background_B1_Trials)
        self.line_11.setObjectName(u"line_11")
        self.line_11.setGeometry(QRect(258, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_11.sizePolicy().hasHeightForWidth())
        self.line_11.setSizePolicy(sizePolicy)
        self.line_11.setFont(font8)
        self.line_11.setFrameShape(QFrame.Shape.VLine)
        self.line_11.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_12 = QFrame(self.Background_B1_Trials)
        self.line_12.setObjectName(u"line_12")
        self.line_12.setGeometry(QRect(288, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_12.sizePolicy().hasHeightForWidth())
        self.line_12.setSizePolicy(sizePolicy)
        self.line_12.setFont(font8)
        self.line_12.setFrameShape(QFrame.Shape.VLine)
        self.line_12.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_13 = QFrame(self.Background_B1_Trials)
        self.line_13.setObjectName(u"line_13")
        self.line_13.setGeometry(QRect(319, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_13.sizePolicy().hasHeightForWidth())
        self.line_13.setSizePolicy(sizePolicy)
        self.line_13.setFont(font8)
        self.line_13.setFrameShape(QFrame.Shape.VLine)
        self.line_13.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_15 = QFrame(self.Background_B1_Trials)
        self.line_15.setObjectName(u"line_15")
        self.line_15.setGeometry(QRect(348, 0, 20, 11))
        sizePolicy.setHeightForWidth(self.line_15.sizePolicy().hasHeightForWidth())
        self.line_15.setSizePolicy(sizePolicy)
        self.line_15.setFont(font8)
        self.line_15.setFrameShape(QFrame.Shape.VLine)
        self.line_15.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_14 = QFrame(self.Background_B1_Trials)
        self.line_14.setObjectName(u"line_14")
        self.line_14.setGeometry(QRect(381, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_14.sizePolicy().hasHeightForWidth())
        self.line_14.setSizePolicy(sizePolicy)
        self.line_14.setFont(font8)
        self.line_14.setFrameShape(QFrame.Shape.VLine)
        self.line_14.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_16 = QFrame(self.Background_B1_Trials)
        self.line_16.setObjectName(u"line_16")
        self.line_16.setGeometry(QRect(413, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_16.sizePolicy().hasHeightForWidth())
        self.line_16.setSizePolicy(sizePolicy)
        self.line_16.setFont(font8)
        self.line_16.setFrameShape(QFrame.Shape.VLine)
        self.line_16.setFrameShadow(QFrame.Shadow.Sunken)
        self.line_17 = QFrame(self.Background_B1_Trials)
        self.line_17.setObjectName(u"line_17")
        self.line_17.setGeometry(QRect(444, 0, 16, 11))
        sizePolicy.setHeightForWidth(self.line_17.sizePolicy().hasHeightForWidth())
        self.line_17.setSizePolicy(sizePolicy)
        self.line_17.setFont(font8)
        self.line_17.setFrameShape(QFrame.Shape.VLine)
        self.line_17.setFrameShadow(QFrame.Shadow.Sunken)
        self.label_B1_TrialMonitor = QLabel(self.Box1)
        self.label_B1_TrialMonitor.setObjectName(u"label_B1_TrialMonitor")
        self.label_B1_TrialMonitor.setGeometry(QRect(734, 413, 131, 20))
        font9 = QFont()
        font9.setPointSize(11)
        self.label_B1_TrialMonitor.setFont(font9)
        self.label_B1_TrialMonitor.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_B1_TrialMonitor_Legend = QLabel(self.Box1)
        self.label_B1_TrialMonitor_Legend.setObjectName(u"label_B1_TrialMonitor_Legend")
        self.label_B1_TrialMonitor_Legend.setGeometry(QRect(580, 441, 451, 20))
        font10 = QFont()
        font10.setPointSize(7)
        self.label_B1_TrialMonitor_Legend.setFont(font10)
        self.label_B1_TrialMonitor_Legend.setStyleSheet(u"\n"
"color: rgb(112, 112, 112);")
        self.label_B1_TrialMonitor_Legend.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_B1_Blocks = QLabel(self.Box1)
        self.label_B1_Blocks.setObjectName(u"label_B1_Blocks")
        self.label_B1_Blocks.setGeometry(QRect(550, 474, 20, 20))
        self.label_B1_Blocks.setFont(font7)
        self.label_B1_Blocks.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_B1_LeftSpout = QLabel(self.Box1)
        self.label_B1_LeftSpout.setObjectName(u"label_B1_LeftSpout")
        self.label_B1_LeftSpout.setGeometry(QRect(556, 508, 10, 20))
        self.label_B1_LeftSpout.setFont(font7)
        self.label_B1_LeftSpout.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_B1_RightSpout = QLabel(self.Box1)
        self.label_B1_RightSpout.setObjectName(u"label_B1_RightSpout")
        self.label_B1_RightSpout.setGeometry(QRect(551, 544, 20, 20))
        self.label_B1_RightSpout.setFont(font7)
        self.label_B1_RightSpout.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_B1_Trials = QLabel(self.Box1)
        self.label_B1_Trials.setObjectName(u"label_B1_Trials")
        self.label_B1_Trials.setGeometry(QRect(551, 581, 20, 20))
        self.label_B1_Trials.setFont(font7)
        self.label_B1_Trials.setAlignment(Qt.AlignHCenter|Qt.AlignTop)
        self.label_B1_TotalTrials = QLabel(self.Box1)
        self.label_B1_TotalTrials.setObjectName(u"label_B1_TotalTrials")
        self.label_B1_TotalTrials.setGeometry(QRect(571, 656, 71, 16))
        self.label_B1_TotalTrials.setFont(font)
        self.label_B1_CorrectTrials = QLabel(self.Box1)
        self.label_B1_CorrectTrials.setObjectName(u"label_B1_CorrectTrials")
        self.label_B1_CorrectTrials.setGeometry(QRect(738, 656, 81, 16))
        self.label_B1_CorrectTrials.setFont(font)
        self.label_B1_IncorrectTrials = QLabel(self.Box1)
        self.label_B1_IncorrectTrials.setObjectName(u"label_B1_IncorrectTrials")
        self.label_B1_IncorrectTrials.setGeometry(QRect(737, 697, 91, 16))
        self.label_B1_IncorrectTrials.setFont(font)
        self.Box1_Omissions = QLabel(self.Box1)
        self.Box1_Omissions.setObjectName(u"Box1_Omissions")
        self.Box1_Omissions.setGeometry(QRect(648, 696, 41, 20))
        self.Box1_Omissions.setFont(font)
        self.Box1_Omissions.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Omissions.setAlignment(Qt.AlignCenter)
        self.label_B1_Omissions = QLabel(self.Box1)
        self.label_B1_Omissions.setObjectName(u"label_B1_Omissions")
        self.label_B1_Omissions.setGeometry(QRect(571, 694, 71, 20))
        self.label_B1_Omissions.setFont(font)
        self.label_B1_EarlyLicks = QLabel(self.Box1)
        self.label_B1_EarlyLicks.setObjectName(u"label_B1_EarlyLicks")
        self.label_B1_EarlyLicks.setGeometry(QRect(573, 734, 61, 20))
        self.label_B1_EarlyLicks.setFont(font)
        self.Box1_EarlyLicks = QLabel(self.Box1)
        self.Box1_EarlyLicks.setObjectName(u"Box1_EarlyLicks")
        self.Box1_EarlyLicks.setGeometry(QRect(648, 736, 41, 20))
        self.Box1_EarlyLicks.setFont(font)
        self.Box1_EarlyLicks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_EarlyLicks.setAlignment(Qt.AlignCenter)
        self.Box1_TotalTrials = QLabel(self.Box1)
        self.Box1_TotalTrials.setObjectName(u"Box1_TotalTrials")
        self.Box1_TotalTrials.setGeometry(QRect(648, 656, 41, 20))
        self.Box1_TotalTrials.setFont(font)
        self.Box1_TotalTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials.setAlignment(Qt.AlignCenter)
        self.Box1_IncorrectTrials = QLabel(self.Box1)
        self.Box1_IncorrectTrials.setObjectName(u"Box1_IncorrectTrials")
        self.Box1_IncorrectTrials.setGeometry(QRect(837, 697, 41, 20))
        self.Box1_IncorrectTrials.setFont(font)
        self.Box1_IncorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_IncorrectTrials.setAlignment(Qt.AlignCenter)
        self.Box1_CorrectTrials = QLabel(self.Box1)
        self.Box1_CorrectTrials.setObjectName(u"Box1_CorrectTrials")
        self.Box1_CorrectTrials.setGeometry(QRect(836, 655, 41, 20))
        self.Box1_CorrectTrials.setFont(font)
        self.Box1_CorrectTrials.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_CorrectTrials.setAlignment(Qt.AlignCenter)
        self.Box1_SoundBlocks = QLabel(self.Box1)
        self.Box1_SoundBlocks.setObjectName(u"Box1_SoundBlocks")
        self.Box1_SoundBlocks.setGeometry(QRect(837, 737, 41, 20))
        self.Box1_SoundBlocks.setFont(font)
        self.Box1_SoundBlocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_SoundBlocks.setAlignment(Qt.AlignCenter)
        self.label_B1_SoundBlocks = QLabel(self.Box1)
        self.label_B1_SoundBlocks.setObjectName(u"label_B1_SoundBlocks")
        self.label_B1_SoundBlocks.setGeometry(QRect(739, 737, 91, 16))
        self.label_B1_SoundBlocks.setFont(font)
        self.Box1_Action_L_blocks = QLabel(self.Box1)
        self.Box1_Action_L_blocks.setObjectName(u"Box1_Action_L_blocks")
        self.Box1_Action_L_blocks.setGeometry(QRect(1015, 657, 41, 20))
        self.Box1_Action_L_blocks.setFont(font)
        self.Box1_Action_L_blocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Action_L_blocks.setAlignment(Qt.AlignCenter)
        self.label_B1_ActionLBlocks = QLabel(self.Box1)
        self.label_B1_ActionLBlocks.setObjectName(u"label_B1_ActionLBlocks")
        self.label_B1_ActionLBlocks.setGeometry(QRect(917, 657, 91, 16))
        self.label_B1_ActionLBlocks.setFont(font)
        self.Box1_Action_R_blocks = QLabel(self.Box1)
        self.Box1_Action_R_blocks.setObjectName(u"Box1_Action_R_blocks")
        self.Box1_Action_R_blocks.setGeometry(QRect(1015, 697, 41, 20))
        self.Box1_Action_R_blocks.setFont(font)
        self.Box1_Action_R_blocks.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Action_R_blocks.setAlignment(Qt.AlignCenter)
        self.label_B1_ActionRBlocks = QLabel(self.Box1)
        self.label_B1_ActionRBlocks.setObjectName(u"label_B1_ActionRBlocks")
        self.label_B1_ActionRBlocks.setGeometry(QRect(917, 697, 91, 16))
        self.label_B1_ActionRBlocks.setFont(font)
        self.Box1_Chronometer = QLabel(self.Box1)
        self.Box1_Chronometer.setObjectName(u"Box1_Chronometer")
        self.Box1_Chronometer.setGeometry(QRect(737, 42, 160, 21))
        self.Box1_Chronometer.setFont(font2)
        self.Box1_Chronometer.setAlignment(Qt.AlignCenter)
        self.Boxes.addTab(self.Box1, "")
        self.Background_B1_Trials.raise_()
        self.TaskSettings.raise_()
        self.label_TaskSettings.raise_()
        self.label_Visualization.raise_()
        self.line.raise_()
        self.Box1_Camera.raise_()
        self.Box1_AnimalsPerfomance.raise_()
        self.Box1_LickTrace_Right.raise_()
        self.Box1_LickTrace_Left.raise_()
        self.label_B1_AnimalPerformance.raise_()
        self.label_B1_LickTrace_right.raise_()
        self.label_B1_LickTrace_left.raise_()
        self.label_B1_Time.raise_()
        self.Background_B1_Blocks.raise_()
        self.Background_B1_LeftSpout.raise_()
        self.Background_B1_RightSpout.raise_()
        self.label_B1_TrialMonitor.raise_()
        self.label_B1_TrialMonitor_Legend.raise_()
        self.label_B1_Blocks.raise_()
        self.label_B1_LeftSpout.raise_()
        self.label_B1_RightSpout.raise_()
        self.label_B1_Trials.raise_()
        self.label_B1_TotalTrials.raise_()
        self.label_B1_CorrectTrials.raise_()
        self.label_B1_IncorrectTrials.raise_()
        self.Box1_Omissions.raise_()
        self.label_B1_Omissions.raise_()
        self.label_B1_EarlyLicks.raise_()
        self.Box1_EarlyLicks.raise_()
        self.Box1_TotalTrials.raise_()
        self.Box1_IncorrectTrials.raise_()
        self.Box1_CorrectTrials.raise_()
        self.Box1_SoundBlocks.raise_()
        self.label_B1_SoundBlocks.raise_()
        self.Box1_Action_L_blocks.raise_()
        self.label_B1_ActionLBlocks.raise_()
        self.Box1_Action_R_blocks.raise_()
        self.label_B1_ActionRBlocks.raise_()
        self.Box1_Chronometer.raise_()
        self.Box2 = QWidget()
        self.Box2.setObjectName(u"Box2")
        self.Boxes.addTab(self.Box2, "")
        self.Box3 = QWidget()
        self.Box3.setObjectName(u"Box3")
        self.Boxes.addTab(self.Box3, "")
        self.Box4 = QWidget()
        self.Box4.setObjectName(u"Box4")
        self.Boxes.addTab(self.Box4, "")
        self.Ephys_Rig = QWidget()
        self.Ephys_Rig.setObjectName(u"Ephys_Rig")
        self.Boxes.addTab(self.Ephys_Rig, "")
        self.Overview = QWidget()
        self.Overview.setObjectName(u"Overview")
        self.OV_Box1 = QGroupBox(self.Overview)
        self.OV_Box1.setObjectName(u"OV_Box1")
        self.OV_Box1.setGeometry(QRect(10, 20, 301, 801))
        self.OV_Box1.setFont(font7)
        self.OV_Box1.setStyleSheet(u"border-color: rgb(112, 255, 122);\n"
"")
        self.widget = QWidget(self.OV_Box1)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(15, 100, 271, 221))
        self.widget.setStyleSheet(u"background-color: rgb(189, 189, 189);")
        self.widget_6 = QWidget(self.OV_Box1)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(16, 339, 271, 221))
        self.widget_6.setStyleSheet(u"background-color: rgb(230, 248, 255);")
        self.OV1_Chronometer = QLabel(self.OV_Box1)
        self.OV1_Chronometer.setObjectName(u"OV1_Chronometer")
        self.OV1_Chronometer.setGeometry(QRect(93, 44, 160, 21))
        self.OV1_Chronometer.setFont(font2)
        self.OV1_Chronometer.setAlignment(Qt.AlignCenter)
        self.label_OV1_Time = QLabel(self.OV_Box1)
        self.label_OV1_Time.setObjectName(u"label_OV1_Time")
        self.label_OV1_Time.setGeometry(QRect(49, 45, 41, 20))
        self.label_OV1_Time.setFont(font7)
        self.label_B1_Omissions_2 = QLabel(self.OV_Box1)
        self.label_B1_Omissions_2.setObjectName(u"label_B1_Omissions_2")
        self.label_B1_Omissions_2.setGeometry(QRect(98, 753, 71, 20))
        self.label_B1_Omissions_2.setFont(font)
        self.Box1_CorrectTrials_2 = QLabel(self.OV_Box1)
        self.Box1_CorrectTrials_2.setObjectName(u"Box1_CorrectTrials_2")
        self.Box1_CorrectTrials_2.setGeometry(QRect(182, 675, 41, 20))
        self.Box1_CorrectTrials_2.setFont(font)
        self.Box1_CorrectTrials_2.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_CorrectTrials_2.setAlignment(Qt.AlignCenter)
        self.Box1_IncorrectTrials_2 = QLabel(self.OV_Box1)
        self.Box1_IncorrectTrials_2.setObjectName(u"Box1_IncorrectTrials_2")
        self.Box1_IncorrectTrials_2.setGeometry(QRect(182, 716, 41, 20))
        self.Box1_IncorrectTrials_2.setFont(font)
        self.Box1_IncorrectTrials_2.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_IncorrectTrials_2.setAlignment(Qt.AlignCenter)
        self.Box1_TotalTrials_2 = QLabel(self.OV_Box1)
        self.Box1_TotalTrials_2.setObjectName(u"Box1_TotalTrials_2")
        self.Box1_TotalTrials_2.setGeometry(QRect(182, 637, 41, 20))
        self.Box1_TotalTrials_2.setFont(font)
        self.Box1_TotalTrials_2.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_2.setAlignment(Qt.AlignCenter)
        self.label_B1_TotalTrials_2 = QLabel(self.OV_Box1)
        self.label_B1_TotalTrials_2.setObjectName(u"label_B1_TotalTrials_2")
        self.label_B1_TotalTrials_2.setGeometry(QRect(97, 637, 71, 16))
        self.label_B1_TotalTrials_2.setFont(font)
        self.Box1_Omissions_2 = QLabel(self.OV_Box1)
        self.Box1_Omissions_2.setObjectName(u"Box1_Omissions_2")
        self.Box1_Omissions_2.setGeometry(QRect(182, 755, 41, 20))
        self.Box1_Omissions_2.setFont(font)
        self.Box1_Omissions_2.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Omissions_2.setAlignment(Qt.AlignCenter)
        self.label_B1_IncorrectTrials_2 = QLabel(self.OV_Box1)
        self.label_B1_IncorrectTrials_2.setObjectName(u"label_B1_IncorrectTrials_2")
        self.label_B1_IncorrectTrials_2.setGeometry(QRect(73, 716, 91, 16))
        self.label_B1_IncorrectTrials_2.setFont(font)
        self.label_B1_CorrectTrials_2 = QLabel(self.OV_Box1)
        self.label_B1_CorrectTrials_2.setObjectName(u"label_B1_CorrectTrials_2")
        self.label_B1_CorrectTrials_2.setGeometry(QRect(81, 676, 81, 16))
        self.label_B1_CorrectTrials_2.setFont(font)
        self.label_B1_TotalTrials_3 = QLabel(self.OV_Box1)
        self.label_B1_TotalTrials_3.setObjectName(u"label_B1_TotalTrials_3")
        self.label_B1_TotalTrials_3.setGeometry(QRect(59, 600, 81, 16))
        self.label_B1_TotalTrials_3.setFont(font)
        self.label_B1_TotalTrials_3.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.Box1_TotalTrials_3 = QLabel(self.OV_Box1)
        self.Box1_TotalTrials_3.setObjectName(u"Box1_TotalTrials_3")
        self.Box1_TotalTrials_3.setGeometry(QRect(151, 600, 91, 20))
        self.Box1_TotalTrials_3.setFont(font)
        self.Box1_TotalTrials_3.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_3.setAlignment(Qt.AlignCenter)
        self.OV_Box2 = QGroupBox(self.Overview)
        self.OV_Box2.setObjectName(u"OV_Box2")
        self.OV_Box2.setGeometry(QRect(324, 19, 301, 801))
        self.OV_Box2.setFont(font7)
        self.OV_Box2.setStyleSheet(u"\n"
"border-color: rgb(112, 255, 122);")
        self.widget_2 = QWidget(self.OV_Box2)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(15, 100, 271, 221))
        self.widget_2.setStyleSheet(u"background-color: rgb(189, 189, 189);")
        self.widget_7 = QWidget(self.OV_Box2)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(16, 339, 271, 221))
        self.widget_7.setStyleSheet(u"background-color: rgb(230, 248, 255);")
        self.Box1_Chronometer_3 = QLabel(self.OV_Box2)
        self.Box1_Chronometer_3.setObjectName(u"Box1_Chronometer_3")
        self.Box1_Chronometer_3.setGeometry(QRect(93, 44, 160, 21))
        self.Box1_Chronometer_3.setFont(font2)
        self.Box1_Chronometer_3.setAlignment(Qt.AlignCenter)
        self.label_B1_Time_3 = QLabel(self.OV_Box2)
        self.label_B1_Time_3.setObjectName(u"label_B1_Time_3")
        self.label_B1_Time_3.setGeometry(QRect(49, 45, 41, 20))
        self.label_B1_Time_3.setFont(font7)
        self.label_B1_Omissions_3 = QLabel(self.OV_Box2)
        self.label_B1_Omissions_3.setObjectName(u"label_B1_Omissions_3")
        self.label_B1_Omissions_3.setGeometry(QRect(98, 753, 71, 20))
        self.label_B1_Omissions_3.setFont(font)
        self.Box1_CorrectTrials_3 = QLabel(self.OV_Box2)
        self.Box1_CorrectTrials_3.setObjectName(u"Box1_CorrectTrials_3")
        self.Box1_CorrectTrials_3.setGeometry(QRect(182, 675, 41, 20))
        self.Box1_CorrectTrials_3.setFont(font)
        self.Box1_CorrectTrials_3.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_CorrectTrials_3.setAlignment(Qt.AlignCenter)
        self.Box1_IncorrectTrials_3 = QLabel(self.OV_Box2)
        self.Box1_IncorrectTrials_3.setObjectName(u"Box1_IncorrectTrials_3")
        self.Box1_IncorrectTrials_3.setGeometry(QRect(182, 716, 41, 20))
        self.Box1_IncorrectTrials_3.setFont(font)
        self.Box1_IncorrectTrials_3.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_IncorrectTrials_3.setAlignment(Qt.AlignCenter)
        self.Box1_TotalTrials_4 = QLabel(self.OV_Box2)
        self.Box1_TotalTrials_4.setObjectName(u"Box1_TotalTrials_4")
        self.Box1_TotalTrials_4.setGeometry(QRect(182, 637, 41, 20))
        self.Box1_TotalTrials_4.setFont(font)
        self.Box1_TotalTrials_4.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_4.setAlignment(Qt.AlignCenter)
        self.label_B1_TotalTrials_4 = QLabel(self.OV_Box2)
        self.label_B1_TotalTrials_4.setObjectName(u"label_B1_TotalTrials_4")
        self.label_B1_TotalTrials_4.setGeometry(QRect(97, 637, 71, 16))
        self.label_B1_TotalTrials_4.setFont(font)
        self.Box1_Omissions_3 = QLabel(self.OV_Box2)
        self.Box1_Omissions_3.setObjectName(u"Box1_Omissions_3")
        self.Box1_Omissions_3.setGeometry(QRect(182, 755, 41, 20))
        self.Box1_Omissions_3.setFont(font)
        self.Box1_Omissions_3.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Omissions_3.setAlignment(Qt.AlignCenter)
        self.label_B1_IncorrectTrials_3 = QLabel(self.OV_Box2)
        self.label_B1_IncorrectTrials_3.setObjectName(u"label_B1_IncorrectTrials_3")
        self.label_B1_IncorrectTrials_3.setGeometry(QRect(73, 716, 91, 16))
        self.label_B1_IncorrectTrials_3.setFont(font)
        self.label_B1_CorrectTrials_3 = QLabel(self.OV_Box2)
        self.label_B1_CorrectTrials_3.setObjectName(u"label_B1_CorrectTrials_3")
        self.label_B1_CorrectTrials_3.setGeometry(QRect(81, 676, 81, 16))
        self.label_B1_CorrectTrials_3.setFont(font)
        self.label_B1_TotalTrials_5 = QLabel(self.OV_Box2)
        self.label_B1_TotalTrials_5.setObjectName(u"label_B1_TotalTrials_5")
        self.label_B1_TotalTrials_5.setGeometry(QRect(59, 600, 81, 16))
        self.label_B1_TotalTrials_5.setFont(font)
        self.label_B1_TotalTrials_5.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.Box1_TotalTrials_5 = QLabel(self.OV_Box2)
        self.Box1_TotalTrials_5.setObjectName(u"Box1_TotalTrials_5")
        self.Box1_TotalTrials_5.setGeometry(QRect(151, 600, 91, 20))
        self.Box1_TotalTrials_5.setFont(font)
        self.Box1_TotalTrials_5.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_5.setAlignment(Qt.AlignCenter)
        self.OV_Box3 = QGroupBox(self.Overview)
        self.OV_Box3.setObjectName(u"OV_Box3")
        self.OV_Box3.setGeometry(QRect(638, 19, 301, 801))
        self.OV_Box3.setFont(font7)
        self.OV_Box3.setStyleSheet(u"\n"
"border-color: rgb(112, 255, 122);")
        self.widget_3 = QWidget(self.OV_Box3)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(15, 100, 271, 221))
        self.widget_3.setStyleSheet(u"background-color: rgb(189, 189, 189);")
        self.widget_8 = QWidget(self.OV_Box3)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(16, 339, 271, 221))
        self.widget_8.setStyleSheet(u"background-color: rgb(230, 248, 255);")
        self.Box1_Chronometer_4 = QLabel(self.OV_Box3)
        self.Box1_Chronometer_4.setObjectName(u"Box1_Chronometer_4")
        self.Box1_Chronometer_4.setGeometry(QRect(93, 44, 160, 21))
        self.Box1_Chronometer_4.setFont(font2)
        self.Box1_Chronometer_4.setAlignment(Qt.AlignCenter)
        self.label_B1_Time_4 = QLabel(self.OV_Box3)
        self.label_B1_Time_4.setObjectName(u"label_B1_Time_4")
        self.label_B1_Time_4.setGeometry(QRect(49, 45, 41, 20))
        self.label_B1_Time_4.setFont(font7)
        self.label_B1_Omissions_4 = QLabel(self.OV_Box3)
        self.label_B1_Omissions_4.setObjectName(u"label_B1_Omissions_4")
        self.label_B1_Omissions_4.setGeometry(QRect(98, 753, 71, 20))
        self.label_B1_Omissions_4.setFont(font)
        self.Box1_CorrectTrials_4 = QLabel(self.OV_Box3)
        self.Box1_CorrectTrials_4.setObjectName(u"Box1_CorrectTrials_4")
        self.Box1_CorrectTrials_4.setGeometry(QRect(182, 675, 41, 20))
        self.Box1_CorrectTrials_4.setFont(font)
        self.Box1_CorrectTrials_4.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_CorrectTrials_4.setAlignment(Qt.AlignCenter)
        self.Box1_IncorrectTrials_4 = QLabel(self.OV_Box3)
        self.Box1_IncorrectTrials_4.setObjectName(u"Box1_IncorrectTrials_4")
        self.Box1_IncorrectTrials_4.setGeometry(QRect(182, 716, 41, 20))
        self.Box1_IncorrectTrials_4.setFont(font)
        self.Box1_IncorrectTrials_4.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_IncorrectTrials_4.setAlignment(Qt.AlignCenter)
        self.Box1_TotalTrials_6 = QLabel(self.OV_Box3)
        self.Box1_TotalTrials_6.setObjectName(u"Box1_TotalTrials_6")
        self.Box1_TotalTrials_6.setGeometry(QRect(182, 637, 41, 20))
        self.Box1_TotalTrials_6.setFont(font)
        self.Box1_TotalTrials_6.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_6.setAlignment(Qt.AlignCenter)
        self.label_B1_TotalTrials_6 = QLabel(self.OV_Box3)
        self.label_B1_TotalTrials_6.setObjectName(u"label_B1_TotalTrials_6")
        self.label_B1_TotalTrials_6.setGeometry(QRect(97, 637, 71, 16))
        self.label_B1_TotalTrials_6.setFont(font)
        self.Box1_Omissions_4 = QLabel(self.OV_Box3)
        self.Box1_Omissions_4.setObjectName(u"Box1_Omissions_4")
        self.Box1_Omissions_4.setGeometry(QRect(182, 755, 41, 20))
        self.Box1_Omissions_4.setFont(font)
        self.Box1_Omissions_4.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Omissions_4.setAlignment(Qt.AlignCenter)
        self.label_B1_IncorrectTrials_4 = QLabel(self.OV_Box3)
        self.label_B1_IncorrectTrials_4.setObjectName(u"label_B1_IncorrectTrials_4")
        self.label_B1_IncorrectTrials_4.setGeometry(QRect(73, 716, 91, 16))
        self.label_B1_IncorrectTrials_4.setFont(font)
        self.label_B1_CorrectTrials_4 = QLabel(self.OV_Box3)
        self.label_B1_CorrectTrials_4.setObjectName(u"label_B1_CorrectTrials_4")
        self.label_B1_CorrectTrials_4.setGeometry(QRect(81, 676, 81, 16))
        self.label_B1_CorrectTrials_4.setFont(font)
        self.label_B1_TotalTrials_7 = QLabel(self.OV_Box3)
        self.label_B1_TotalTrials_7.setObjectName(u"label_B1_TotalTrials_7")
        self.label_B1_TotalTrials_7.setGeometry(QRect(59, 600, 81, 16))
        self.label_B1_TotalTrials_7.setFont(font)
        self.label_B1_TotalTrials_7.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.Box1_TotalTrials_7 = QLabel(self.OV_Box3)
        self.Box1_TotalTrials_7.setObjectName(u"Box1_TotalTrials_7")
        self.Box1_TotalTrials_7.setGeometry(QRect(151, 600, 91, 20))
        self.Box1_TotalTrials_7.setFont(font)
        self.Box1_TotalTrials_7.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_7.setAlignment(Qt.AlignCenter)
        self.OV_Box4 = QGroupBox(self.Overview)
        self.OV_Box4.setObjectName(u"OV_Box4")
        self.OV_Box4.setGeometry(QRect(952, 19, 301, 801))
        self.OV_Box4.setFont(font7)
        self.OV_Box4.setStyleSheet(u"\n"
"border-color: rgb(112, 255, 122);")
        self.widget_5 = QWidget(self.OV_Box4)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(15, 100, 271, 221))
        self.widget_5.setStyleSheet(u"background-color: rgb(189, 189, 189);")
        self.widget_10 = QWidget(self.OV_Box4)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setGeometry(QRect(16, 339, 271, 221))
        self.widget_10.setStyleSheet(u"background-color: rgb(230, 248, 255);")
        self.Box1_Chronometer_6 = QLabel(self.OV_Box4)
        self.Box1_Chronometer_6.setObjectName(u"Box1_Chronometer_6")
        self.Box1_Chronometer_6.setGeometry(QRect(93, 44, 160, 21))
        self.Box1_Chronometer_6.setFont(font2)
        self.Box1_Chronometer_6.setAlignment(Qt.AlignCenter)
        self.label_B1_Time_6 = QLabel(self.OV_Box4)
        self.label_B1_Time_6.setObjectName(u"label_B1_Time_6")
        self.label_B1_Time_6.setGeometry(QRect(49, 45, 41, 20))
        self.label_B1_Time_6.setFont(font7)
        self.label_B1_Omissions_6 = QLabel(self.OV_Box4)
        self.label_B1_Omissions_6.setObjectName(u"label_B1_Omissions_6")
        self.label_B1_Omissions_6.setGeometry(QRect(98, 753, 71, 20))
        self.label_B1_Omissions_6.setFont(font)
        self.Box1_CorrectTrials_6 = QLabel(self.OV_Box4)
        self.Box1_CorrectTrials_6.setObjectName(u"Box1_CorrectTrials_6")
        self.Box1_CorrectTrials_6.setGeometry(QRect(182, 675, 41, 20))
        self.Box1_CorrectTrials_6.setFont(font)
        self.Box1_CorrectTrials_6.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_CorrectTrials_6.setAlignment(Qt.AlignCenter)
        self.Box1_IncorrectTrials_6 = QLabel(self.OV_Box4)
        self.Box1_IncorrectTrials_6.setObjectName(u"Box1_IncorrectTrials_6")
        self.Box1_IncorrectTrials_6.setGeometry(QRect(182, 716, 41, 20))
        self.Box1_IncorrectTrials_6.setFont(font)
        self.Box1_IncorrectTrials_6.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_IncorrectTrials_6.setAlignment(Qt.AlignCenter)
        self.Box1_TotalTrials_10 = QLabel(self.OV_Box4)
        self.Box1_TotalTrials_10.setObjectName(u"Box1_TotalTrials_10")
        self.Box1_TotalTrials_10.setGeometry(QRect(182, 637, 41, 20))
        self.Box1_TotalTrials_10.setFont(font)
        self.Box1_TotalTrials_10.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_10.setAlignment(Qt.AlignCenter)
        self.label_B1_TotalTrials_10 = QLabel(self.OV_Box4)
        self.label_B1_TotalTrials_10.setObjectName(u"label_B1_TotalTrials_10")
        self.label_B1_TotalTrials_10.setGeometry(QRect(97, 637, 71, 16))
        self.label_B1_TotalTrials_10.setFont(font)
        self.Box1_Omissions_6 = QLabel(self.OV_Box4)
        self.Box1_Omissions_6.setObjectName(u"Box1_Omissions_6")
        self.Box1_Omissions_6.setGeometry(QRect(182, 755, 41, 20))
        self.Box1_Omissions_6.setFont(font)
        self.Box1_Omissions_6.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Omissions_6.setAlignment(Qt.AlignCenter)
        self.label_B1_IncorrectTrials_6 = QLabel(self.OV_Box4)
        self.label_B1_IncorrectTrials_6.setObjectName(u"label_B1_IncorrectTrials_6")
        self.label_B1_IncorrectTrials_6.setGeometry(QRect(73, 716, 91, 16))
        self.label_B1_IncorrectTrials_6.setFont(font)
        self.label_B1_CorrectTrials_6 = QLabel(self.OV_Box4)
        self.label_B1_CorrectTrials_6.setObjectName(u"label_B1_CorrectTrials_6")
        self.label_B1_CorrectTrials_6.setGeometry(QRect(81, 676, 81, 16))
        self.label_B1_CorrectTrials_6.setFont(font)
        self.label_B1_TotalTrials_11 = QLabel(self.OV_Box4)
        self.label_B1_TotalTrials_11.setObjectName(u"label_B1_TotalTrials_11")
        self.label_B1_TotalTrials_11.setGeometry(QRect(59, 600, 81, 16))
        self.label_B1_TotalTrials_11.setFont(font)
        self.label_B1_TotalTrials_11.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.Box1_TotalTrials_11 = QLabel(self.OV_Box4)
        self.Box1_TotalTrials_11.setObjectName(u"Box1_TotalTrials_11")
        self.Box1_TotalTrials_11.setGeometry(QRect(151, 600, 91, 20))
        self.Box1_TotalTrials_11.setFont(font)
        self.Box1_TotalTrials_11.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_11.setAlignment(Qt.AlignCenter)
        self.OV_Ephys = QGroupBox(self.Overview)
        self.OV_Ephys.setObjectName(u"OV_Ephys")
        self.OV_Ephys.setGeometry(QRect(1264, 19, 301, 801))
        self.OV_Ephys.setFont(font7)
        self.OV_Ephys.setStyleSheet(u"\n"
"border-color: rgb(112, 255, 122);")
        self.widget_13 = QWidget(self.OV_Ephys)
        self.widget_13.setObjectName(u"widget_13")
        self.widget_13.setGeometry(QRect(15, 100, 271, 221))
        self.widget_13.setStyleSheet(u"background-color: rgb(189, 189, 189);")
        self.widget_14 = QWidget(self.OV_Ephys)
        self.widget_14.setObjectName(u"widget_14")
        self.widget_14.setGeometry(QRect(16, 339, 271, 221))
        self.widget_14.setStyleSheet(u"background-color: rgb(230, 248, 255);")
        self.Box1_Chronometer_8 = QLabel(self.OV_Ephys)
        self.Box1_Chronometer_8.setObjectName(u"Box1_Chronometer_8")
        self.Box1_Chronometer_8.setGeometry(QRect(93, 44, 160, 21))
        self.Box1_Chronometer_8.setFont(font2)
        self.Box1_Chronometer_8.setAlignment(Qt.AlignCenter)
        self.label_B1_Time_8 = QLabel(self.OV_Ephys)
        self.label_B1_Time_8.setObjectName(u"label_B1_Time_8")
        self.label_B1_Time_8.setGeometry(QRect(49, 45, 41, 20))
        self.label_B1_Time_8.setFont(font7)
        self.label_B1_Omissions_8 = QLabel(self.OV_Ephys)
        self.label_B1_Omissions_8.setObjectName(u"label_B1_Omissions_8")
        self.label_B1_Omissions_8.setGeometry(QRect(98, 753, 71, 20))
        self.label_B1_Omissions_8.setFont(font)
        self.Box1_CorrectTrials_8 = QLabel(self.OV_Ephys)
        self.Box1_CorrectTrials_8.setObjectName(u"Box1_CorrectTrials_8")
        self.Box1_CorrectTrials_8.setGeometry(QRect(182, 675, 41, 20))
        self.Box1_CorrectTrials_8.setFont(font)
        self.Box1_CorrectTrials_8.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_CorrectTrials_8.setAlignment(Qt.AlignCenter)
        self.Box1_IncorrectTrials_8 = QLabel(self.OV_Ephys)
        self.Box1_IncorrectTrials_8.setObjectName(u"Box1_IncorrectTrials_8")
        self.Box1_IncorrectTrials_8.setGeometry(QRect(182, 716, 41, 20))
        self.Box1_IncorrectTrials_8.setFont(font)
        self.Box1_IncorrectTrials_8.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_IncorrectTrials_8.setAlignment(Qt.AlignCenter)
        self.Box1_TotalTrials_14 = QLabel(self.OV_Ephys)
        self.Box1_TotalTrials_14.setObjectName(u"Box1_TotalTrials_14")
        self.Box1_TotalTrials_14.setGeometry(QRect(182, 637, 41, 20))
        self.Box1_TotalTrials_14.setFont(font)
        self.Box1_TotalTrials_14.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_14.setAlignment(Qt.AlignCenter)
        self.label_B1_TotalTrials_14 = QLabel(self.OV_Ephys)
        self.label_B1_TotalTrials_14.setObjectName(u"label_B1_TotalTrials_14")
        self.label_B1_TotalTrials_14.setGeometry(QRect(97, 637, 71, 16))
        self.label_B1_TotalTrials_14.setFont(font)
        self.Box1_Omissions_8 = QLabel(self.OV_Ephys)
        self.Box1_Omissions_8.setObjectName(u"Box1_Omissions_8")
        self.Box1_Omissions_8.setGeometry(QRect(182, 755, 41, 20))
        self.Box1_Omissions_8.setFont(font)
        self.Box1_Omissions_8.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_Omissions_8.setAlignment(Qt.AlignCenter)
        self.label_B1_IncorrectTrials_8 = QLabel(self.OV_Ephys)
        self.label_B1_IncorrectTrials_8.setObjectName(u"label_B1_IncorrectTrials_8")
        self.label_B1_IncorrectTrials_8.setGeometry(QRect(73, 716, 91, 16))
        self.label_B1_IncorrectTrials_8.setFont(font)
        self.label_B1_CorrectTrials_8 = QLabel(self.OV_Ephys)
        self.label_B1_CorrectTrials_8.setObjectName(u"label_B1_CorrectTrials_8")
        self.label_B1_CorrectTrials_8.setGeometry(QRect(81, 676, 81, 16))
        self.label_B1_CorrectTrials_8.setFont(font)
        self.label_B1_TotalTrials_15 = QLabel(self.OV_Ephys)
        self.label_B1_TotalTrials_15.setObjectName(u"label_B1_TotalTrials_15")
        self.label_B1_TotalTrials_15.setGeometry(QRect(59, 600, 81, 16))
        self.label_B1_TotalTrials_15.setFont(font)
        self.label_B1_TotalTrials_15.setStyleSheet(u"color: rgb(255, 113, 85);")
        self.Box1_TotalTrials_15 = QLabel(self.OV_Ephys)
        self.Box1_TotalTrials_15.setObjectName(u"Box1_TotalTrials_15")
        self.Box1_TotalTrials_15.setGeometry(QRect(151, 600, 91, 20))
        self.Box1_TotalTrials_15.setFont(font)
        self.Box1_TotalTrials_15.setStyleSheet(u"background-color: rgb(234, 234, 234);")
        self.Box1_TotalTrials_15.setAlignment(Qt.AlignCenter)
        self.Boxes.addTab(self.Overview, "")
        TaskGui.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(TaskGui)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1600, 22))
        self.menuAdaptive_sensorimotor_decision_making_task = QMenu(self.menubar)
        self.menuAdaptive_sensorimotor_decision_making_task.setObjectName(u"menuAdaptive_sensorimotor_decision_making_task")
        TaskGui.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(TaskGui)
        self.statusbar.setObjectName(u"statusbar")
        TaskGui.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuAdaptive_sensorimotor_decision_making_task.menuAction())

        self.retranslateUi(TaskGui)

        self.Boxes.setCurrentIndex(6)


        QMetaObject.connectSlotsByName(TaskGui)
    # setupUi

    def retranslateUi(self, TaskGui):
        TaskGui.setWindowTitle(QCoreApplication.translate("TaskGui", u"TaskGui", None))
        self.actionAdaptive_sensorimotor_decision_making_task.setText(QCoreApplication.translate("TaskGui", u"Adaptive sensorimotor decision-making task", None))
        self.actionAdaptive_sensorimotor_decision_making_task_2.setText(QCoreApplication.translate("TaskGui", u"Adaptive sensorimotor decision-making task", None))
        self.label_10.setText(QCoreApplication.translate("TaskGui", u"BOX 1", None))
        self.pushButton.setText(QCoreApplication.translate("TaskGui", u"Connect", None))
        self.pushButton_5.setText(QCoreApplication.translate("TaskGui", u"Disconnect", None))
        self.label_11.setText(QCoreApplication.translate("TaskGui", u"BOX 2", None))
        self.pushButton_6.setText(QCoreApplication.translate("TaskGui", u"Disconnect", None))
        self.pushButton_7.setText(QCoreApplication.translate("TaskGui", u"Connect", None))
        self.label_12.setText(QCoreApplication.translate("TaskGui", u"BOX 3", None))
        self.pushButton_8.setText(QCoreApplication.translate("TaskGui", u"Disconnect", None))
        self.pushButton_9.setText(QCoreApplication.translate("TaskGui", u"Connect", None))
        self.label_13.setText(QCoreApplication.translate("TaskGui", u"BOX 4", None))
        self.pushButton_10.setText(QCoreApplication.translate("TaskGui", u"Disconnect", None))
        self.pushButton_11.setText(QCoreApplication.translate("TaskGui", u"Connect", None))
        self.label_14.setText(QCoreApplication.translate("TaskGui", u"Ephys Rig", None))
        self.pushButton_12.setText(QCoreApplication.translate("TaskGui", u"Disconnect", None))
        self.pushButton_13.setText(QCoreApplication.translate("TaskGui", u"Connect", None))
        self.label_16.setText(QCoreApplication.translate("TaskGui", u"1) Start by connecting the Server        2) Connect the server to the raspberry pi controlling each behavior box", None))
        self.label_15.setText(QCoreApplication.translate("TaskGui", u"SERVER", None))
        self.pushButton_14.setText(QCoreApplication.translate("TaskGui", u"Disconnect", None))
        self.pushButton_2.setText(QCoreApplication.translate("TaskGui", u"Connect", None))
        self.Boxes.setTabText(self.Boxes.indexOf(self.Rbpi_Connection), QCoreApplication.translate("TaskGui", u"Rbpi connection", None))
#if QT_CONFIG(accessibility)
        self.Box1.setAccessibleName("")
#endif // QT_CONFIG(accessibility)
        self.label_B1_AnimalID.setText(QCoreApplication.translate("TaskGui", u"Animal_ID :", None))
        self.Box1_Start.setText(QCoreApplication.translate("TaskGui", u"START", None))
        self.Box1_Stop.setText(QCoreApplication.translate("TaskGui", u"STOP", None))
        self.Box1_Task.setItemText(0, QCoreApplication.translate("TaskGui", u"---", None))
        self.Box1_Task.setItemText(1, QCoreApplication.translate("TaskGui", u"Test rig", None))
        self.Box1_Task.setItemText(2, QCoreApplication.translate("TaskGui", u"Free Licking", None))
        self.Box1_Task.setItemText(3, QCoreApplication.translate("TaskGui", u"Spout Sampling", None))
        self.Box1_Task.setItemText(4, QCoreApplication.translate("TaskGui", u"Two-Choice Auditory Task", None))
        self.Box1_Task.setItemText(5, QCoreApplication.translate("TaskGui", u"Adaptive Sensorimotor Task", None))
        self.Box1_Task.setItemText(6, QCoreApplication.translate("TaskGui", u"Adaptive Sensorimotor Task w/ Distractor", None))

        self.label_B1_Task.setText(QCoreApplication.translate("TaskGui", u"Task :", None))
        self.label_B1_TaskTimeline.setText(QCoreApplication.translate("TaskGui", u"Task Timeline Params :", None))
        self.label_B1_RigParams.setText(QCoreApplication.translate("TaskGui", u"Test Rig Params :", None))
        self.Box1_BlueLED.setText(QCoreApplication.translate("TaskGui", u"Blue LED", None))
        self.Box1_WhiteLED_Left.setText(QCoreApplication.translate("TaskGui", u"White LED - Left", None))
        self.Box1_10Tone.setText(QCoreApplication.translate("TaskGui", u"10KHz Tone", None))
        self.Box1_5Tone.setText(QCoreApplication.translate("TaskGui", u"5KHz Tone", None))
        self.Box1_Reward_right.setText(QCoreApplication.translate("TaskGui", u"Reward - right spout", None))
        self.Box1_Punishment.setText(QCoreApplication.translate("TaskGui", u"WN - Punishment", None))
        self.label_B1_QuietWindow.setText(QCoreApplication.translate("TaskGui", u"Quiet Window", None))
        self.label_B1_QW_ms.setText(QCoreApplication.translate("TaskGui", u"[ms]", None))
        self.label_B1_RW_ms.setText(QCoreApplication.translate("TaskGui", u"[ms]", None))
        self.label_B1_ResponseWindow.setText(QCoreApplication.translate("TaskGui", u"Response Window", None))
        self.label_B1_TrialDuration.setText(QCoreApplication.translate("TaskGui", u"Trial Duration", None))
        self.label_B1_TD_ms.setText(QCoreApplication.translate("TaskGui", u"[ms]", None))
        self.label_B1_RewardParams.setText(QCoreApplication.translate("TaskGui", u"Reward Params :", None))
        self.label_B1_VO_ms.setText(QCoreApplication.translate("TaskGui", u"[ms]", None))
        self.label_B1_ValveOpening.setText(QCoreApplication.translate("TaskGui", u"Valve Opening", None))
        self.label_B1_OptoProtocols.setText(QCoreApplication.translate("TaskGui", u"Optotagging Protocols :", None))
        self.Box1_OptoShort.setText(QCoreApplication.translate("TaskGui", u"Short pulses protocol", None))
        self.Box1_OptoLong.setText(QCoreApplication.translate("TaskGui", u"Long pulses protocol", None))
        self.Box1_WhiteLED_Right.setText(QCoreApplication.translate("TaskGui", u"White LED - Right", None))
        self.Box1_Date.setText(QCoreApplication.translate("TaskGui", u"TextLabel", None))
        self.label_B1_Date.setText(QCoreApplication.translate("TaskGui", u"Date :", None))
        self.pushButton_3.setText(QCoreApplication.translate("TaskGui", u"UPDATE", None))
        self.Box1_Reward_left.setText(QCoreApplication.translate("TaskGui", u"Reward - left spout", None))
        self.label_TaskSettings.setText(QCoreApplication.translate("TaskGui", u"Task Settings", None))
        self.label_Visualization.setText(QCoreApplication.translate("TaskGui", u"Visualization", None))
        self.label_B1_AnimalPerformance.setText(QCoreApplication.translate("TaskGui", u"Animal's Performance", None))
        self.label_B1_LickTrace_right.setText(QCoreApplication.translate("TaskGui", u"Lick Trace - Right Spout", None))
        self.label_B1_LickTrace_left.setText(QCoreApplication.translate("TaskGui", u"Lick Trace - Left Spout", None))
        self.label_B1_Time.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_58.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_59.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_60.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_91.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_92.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_93.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_94.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_95.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_96.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_97.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_98.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_99.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_100.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_101.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_102.setText(QCoreApplication.translate("TaskGui", u"S", None))
        self.label_76.setText("")
        self.label_77.setText("")
        self.label_78.setText("")
        self.label_79.setText("")
        self.label_80.setText("")
        self.label_81.setText("")
        self.label_82.setText("")
        self.label_83.setText("")
        self.label_84.setText("")
        self.label_85.setText("")
        self.label_86.setText("")
        self.label_87.setText("")
        self.label_88.setText("")
        self.label_89.setText("")
        self.label_90.setText("")
        self.label_61.setText("")
        self.label_62.setText("")
        self.label_63.setText("")
        self.label_64.setText("")
        self.label_65.setText("")
        self.label_66.setText("")
        self.label_67.setText("")
        self.label_68.setText("")
        self.label_69.setText("")
        self.label_70.setText("")
        self.label_71.setText("")
        self.label_72.setText("")
        self.label_73.setText("")
        self.label_74.setText("")
        self.label_75.setText("")
        self.label_103.setText(QCoreApplication.translate("TaskGui", u"1", None))
        self.label_104.setText(QCoreApplication.translate("TaskGui", u"2", None))
        self.label_105.setText(QCoreApplication.translate("TaskGui", u"3", None))
        self.label_106.setText(QCoreApplication.translate("TaskGui", u"4", None))
        self.label_107.setText(QCoreApplication.translate("TaskGui", u"5", None))
        self.label_108.setText(QCoreApplication.translate("TaskGui", u"6", None))
        self.label_109.setText(QCoreApplication.translate("TaskGui", u"7", None))
        self.label_110.setText(QCoreApplication.translate("TaskGui", u"8", None))
        self.label_111.setText(QCoreApplication.translate("TaskGui", u"9", None))
        self.label_112.setText(QCoreApplication.translate("TaskGui", u"10", None))
        self.label_113.setText(QCoreApplication.translate("TaskGui", u"11", None))
        self.label_114.setText(QCoreApplication.translate("TaskGui", u"12", None))
        self.label_115.setText(QCoreApplication.translate("TaskGui", u"13", None))
        self.label_116.setText(QCoreApplication.translate("TaskGui", u"14", None))
        self.label_117.setText(QCoreApplication.translate("TaskGui", u"15", None))
        self.label_B1_TrialMonitor.setText(QCoreApplication.translate("TaskGui", u"Trial monitor", None))
        self.label_B1_TrialMonitor_Legend.setText(QCoreApplication.translate("TaskGui", u"B - Block type    L - Left spout    R- Right spout    T - Trial number    S - Sound    AL - Action left    AR - Action right", None))
        self.label_B1_Blocks.setText(QCoreApplication.translate("TaskGui", u"B", None))
        self.label_B1_LeftSpout.setText(QCoreApplication.translate("TaskGui", u"L", None))
        self.label_B1_RightSpout.setText(QCoreApplication.translate("TaskGui", u"R", None))
        self.label_B1_Trials.setText(QCoreApplication.translate("TaskGui", u"T", None))
        self.label_B1_TotalTrials.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.label_B1_CorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.label_B1_IncorrectTrials.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.Box1_Omissions.setText("")
        self.label_B1_Omissions.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.label_B1_EarlyLicks.setText(QCoreApplication.translate("TaskGui", u"Early licks:", None))
        self.Box1_EarlyLicks.setText("")
        self.Box1_TotalTrials.setText("")
        self.Box1_IncorrectTrials.setText("")
        self.Box1_CorrectTrials.setText("")
        self.Box1_SoundBlocks.setText("")
        self.label_B1_SoundBlocks.setText(QCoreApplication.translate("TaskGui", u"Sound Blocks:", None))
        self.Box1_Action_L_blocks.setText("")
        self.label_B1_ActionLBlocks.setText(QCoreApplication.translate("TaskGui", u"Action L Blocks:", None))
        self.Box1_Action_R_blocks.setText("")
        self.label_B1_ActionRBlocks.setText(QCoreApplication.translate("TaskGui", u"Action R Blocks:", None))
        self.Box1_Chronometer.setText("")
        self.Boxes.setTabText(self.Boxes.indexOf(self.Box1), QCoreApplication.translate("TaskGui", u"BOX 1", None))
        self.Boxes.setTabText(self.Boxes.indexOf(self.Box2), QCoreApplication.translate("TaskGui", u"BOX 2", None))
        self.Boxes.setTabText(self.Boxes.indexOf(self.Box3), QCoreApplication.translate("TaskGui", u"BOX 3", None))
        self.Boxes.setTabText(self.Boxes.indexOf(self.Box4), QCoreApplication.translate("TaskGui", u"BOX 4", None))
        self.Boxes.setTabText(self.Boxes.indexOf(self.Ephys_Rig), QCoreApplication.translate("TaskGui", u"Ephys Rig", None))
        self.OV_Box1.setTitle(QCoreApplication.translate("TaskGui", u"Box 1", None))
        self.OV1_Chronometer.setText("")
        self.label_OV1_Time.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_B1_Omissions_2.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.Box1_CorrectTrials_2.setText("")
        self.Box1_IncorrectTrials_2.setText("")
        self.Box1_TotalTrials_2.setText("")
        self.label_B1_TotalTrials_2.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.Box1_Omissions_2.setText("")
        self.label_B1_IncorrectTrials_2.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.label_B1_CorrectTrials_2.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.label_B1_TotalTrials_3.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.Box1_TotalTrials_3.setText("")
        self.OV_Box2.setTitle(QCoreApplication.translate("TaskGui", u"Box 2", None))
        self.Box1_Chronometer_3.setText("")
        self.label_B1_Time_3.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_B1_Omissions_3.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.Box1_CorrectTrials_3.setText("")
        self.Box1_IncorrectTrials_3.setText("")
        self.Box1_TotalTrials_4.setText("")
        self.label_B1_TotalTrials_4.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.Box1_Omissions_3.setText("")
        self.label_B1_IncorrectTrials_3.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.label_B1_CorrectTrials_3.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.label_B1_TotalTrials_5.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.Box1_TotalTrials_5.setText("")
        self.OV_Box3.setTitle(QCoreApplication.translate("TaskGui", u"Box 3", None))
        self.Box1_Chronometer_4.setText("")
        self.label_B1_Time_4.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_B1_Omissions_4.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.Box1_CorrectTrials_4.setText("")
        self.Box1_IncorrectTrials_4.setText("")
        self.Box1_TotalTrials_6.setText("")
        self.label_B1_TotalTrials_6.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.Box1_Omissions_4.setText("")
        self.label_B1_IncorrectTrials_4.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.label_B1_CorrectTrials_4.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.label_B1_TotalTrials_7.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.Box1_TotalTrials_7.setText("")
        self.OV_Box4.setTitle(QCoreApplication.translate("TaskGui", u"Box 4", None))
        self.Box1_Chronometer_6.setText("")
        self.label_B1_Time_6.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_B1_Omissions_6.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.Box1_CorrectTrials_6.setText("")
        self.Box1_IncorrectTrials_6.setText("")
        self.Box1_TotalTrials_10.setText("")
        self.label_B1_TotalTrials_10.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.Box1_Omissions_6.setText("")
        self.label_B1_IncorrectTrials_6.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.label_B1_CorrectTrials_6.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.label_B1_TotalTrials_11.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.Box1_TotalTrials_11.setText("")
        self.OV_Ephys.setTitle(QCoreApplication.translate("TaskGui", u"Ephys Rig", None))
        self.Box1_Chronometer_8.setText("")
        self.label_B1_Time_8.setText(QCoreApplication.translate("TaskGui", u"TIME :", None))
        self.label_B1_Omissions_8.setText(QCoreApplication.translate("TaskGui", u"Omissions: ", None))
        self.Box1_CorrectTrials_8.setText("")
        self.Box1_IncorrectTrials_8.setText("")
        self.Box1_TotalTrials_14.setText("")
        self.label_B1_TotalTrials_14.setText(QCoreApplication.translate("TaskGui", u"Total Trials: ", None))
        self.Box1_Omissions_8.setText("")
        self.label_B1_IncorrectTrials_8.setText(QCoreApplication.translate("TaskGui", u"Incorrect Trials: ", None))
        self.label_B1_CorrectTrials_8.setText(QCoreApplication.translate("TaskGui", u"Correct Trials: ", None))
        self.label_B1_TotalTrials_15.setText(QCoreApplication.translate("TaskGui", u"Current Trial:", None))
        self.Box1_TotalTrials_15.setText("")
        self.Boxes.setTabText(self.Boxes.indexOf(self.Overview), QCoreApplication.translate("TaskGui", u"Overview", None))
        self.menuAdaptive_sensorimotor_decision_making_task.setTitle(QCoreApplication.translate("TaskGui", u"   Adaptive sensorimotor decision-making task  ", None))
    # retranslateUi

